### ISSUE TITLE
PR #87 reverted UI

### ISSUE THREAD

**Issue by doxxx** [Andrewthe13th/Inventory_Kamera#100]
PR #87 appears to have reverted the UI in some respects:

1. The titlebar has gone back to "Genshin Impact Scanner v0.9"
2. There are checkboxes instead of radio buttons for the format selection, and selecting both only results in the GOOD format being produced.

There may be other problems but these are the ones I noticed.

**Comment by Andrewthe13th** [comment]
yea thats the production version. We will getting rid of the SEELIE toggle as seelie will also support GOOD format for materials. Maybe i should have made a development branch. Not really used to using github so much.

**Comment by doxxx** [comment]
Development branches for each significant feature, that are only merged to master once complete, would be nice. But for small changes that you can do in one or two commits, they're not necessary. The idea would be to always keep master as up to date as possible, while still in a working state.

**Comment by doxxx** [comment]
If you want any advice, feel free to ask. I'm a senior software dev by day, gamer by night. ;)

**Comment by doxxx** [comment]
This is fixed as of v1.1.
