### ISSUE TITLE
No Export (GOOD) File Generated

### ISSUE THREAD

**Issue by itsmerai** [Andrewthe13th/Inventory_Kamera#102]
Kamera doesn't generate the GOOD file for importing. Tested it with all items ticked, just weapons, just artifacts, and just characters. Error log just indicates that it couldn't scan weapon enhancement material. Scan seems to proceed smoothly up until the very end, and then Kamera just closes and no file is generated in the provided file location.

Testing with Seelie format. That worked fine, though -- the Seelie JSON file was generated in the file location.

**Comment by kwm1800** [comment]
I have same issue. The program crashes without making any error report. It seems inclusion of new characters causing the crash?

**Comment by Cupcak3** [comment]
In the release builds, new things were hardcoded in as they became available in the game. Kamera also only exported after it had scanned *everything* that was checked. If it found something new it would crash completely. Some of this and more is already on this repo's main branch, it just hasn't been made into a release yet. It should be stable enough to clone and run if you do not want to wait for the next release.

**Comment by itsmerai** [comment]
Hi, thanks for the quick reply on this! I'm not familiar with how most of this works but I was able to create a build with the stuff that was in the main branch, like you mentioned. And that worked (after a couple of Google queries)!

Thanks a bunch!
