### ISSUE TITLE
Data won't be exported after scan

### ISSUE THREAD

**Issue by vinnyy88** [Andrewthe13th/Inventory_Kamera#103]
Previously with the GenshinGuide, I had no issues.
Just downloaded and used the Kamera and the scan is ok.
After the scan, the program closes and the (GOOD) file won't be exported.

I have installed the latest VC_redist x64.

**Comment by SenorChipotle** [comment]
ive got the same issue around 10 min ago, i tried adjusting the delay and still no luck

**Comment by Cupcak3** [comment]
Crashes are probably related to Itto, Gorou, and the new weapon. An update is hopefully coming later today.

**Comment by Andrewthe13th** [comment]
yea

**Comment by danx-x** [comment]
Have the same issue, and after reading your reply I decided to scan only the artifacts to try to avoid the crash that could've been due to the new characters/weapons, but it still crashed. Looking forward to the update soon.

**Comment by Andrewthe13th** [comment]
new release has been made public

**Comment by SenorChipotle** [comment]
is it working fine now? cuz i dont have any new character since Raiden and it didnt work still.

**Comment by bigfatjoe87** [comment]
> is it working fine now?

nope

**Comment by vinnyy88** [comment]
I still have the same problem.
Curiously, the 0.9 Genshin guide doesn't recognize the new artifacts, but it does export the data.

**Comment by Cupcak3** [comment]
Currently Kamera does not export unless it completes a scan. It's possibly dangerous to export mid-scan given the way the scanner can abruptly stop, without the need to excessively export. I can look into this after we've ironed out some key bugs. 

V1.0 and older will not work with new items as they used to be hard coded in to work. V1.0 has up to Thoma, and V1.1 should have semi-automatic support for new things.

**Comment by Cupcak3** [comment]
This is an old issue and has likely been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
