### ISSUE TITLE
Weapon and Artifact counts are less than max after scan finishes

### ISSUE THREAD

**Issue by doxxx** [Andrewthe13th/Inventory_Kamera#105]
Using v1.1, I ran a full scan. After the scan finished, the weapon and artifact counts in the lower left corner are less than their max:

![image](https://user-images.githubusercontent.com/677940/146471550-8e3177e8-6f60-48d1-a405-ed6cfdefeb89.png)

I'm not sure what this means...

**Comment by Cupcak3** [comment]
Those are your 5 and 4 star weapons and artifacts.

**Comment by Andrewthe13th** [comment]
We will be adding more filters/toggles in the future to make this more clear.
