### ISSUE TITLE
Not all weapons and artifacts are scanned

### ISSUE THREAD

**Issue by Nalikiller** [Andrewthe13th/Inventory_Kamera#108]
Weapon scanning starts missing weapons at around 500+ because the cursor is shifted down slightly with each new page.
<br/><img src="https://user-images.githubusercontent.com/95504545/146495934-0fd65c4b-ccc9-42e3-988d-b23de32153d1.gif" width="50%" height="50%">
<br/>Artifact scanning skips the 5th column entirely.
<br/><img src="https://user-images.githubusercontent.com/95504545/146497418-2543c67d-2b3e-4d9e-8bd2-7cbca6f62573.gif" width="50%" height="50%">

**Comment by Cupcak3** [comment]
The weapon scrolling will be fixed.

As for artifacts, try moving around in the world and scan again. The scanner tries its best to find where items are on the screen but sometimes the background of the inventory messes with it.

**Comment by Nalikiller** [comment]
Just tried scanning in a bunch of different locations, at different times of day. Same issue. It always skips the 5th column. Also, this only happens with version 1.1

**Comment by Cupcak3** [comment]
Please take a screenshot of your window at the first page of artifacts. 

V1.1 uses an algorithm to determine what to click instead of having positions hardcoded. It isn't perfect but it does have a fall back that appears to be failing in your case.

**Comment by Nalikiller** [comment]
![artifactscreen](https://user-images.githubusercontent.com/95504545/146521581-f7368c5e-ed7a-492c-a013-74fc7bdc1881.png)

**Comment by Nalikiller** [comment]
So for whatever reason, unequipping certain artifacts from the 5th column fixes the issue.

If I remove the artifacts on either Venti, Mona, or Hu Tao, it works. If I equip them again, it goes back to skipping the 5th column. Oddly, removing the artifacts from Thoma and Xingqiu does nothing.

**Comment by Cupcak3** [comment]
Hmm. Alright thanks for the screenshot and extra details.

It looks like the character icons are throwing off the rectangle detection. I suppose a workaround for now is to have at least one unequipped artifact in every row and column on the first page.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by Nalikiller** [comment]
Fixed
