### ISSUE TITLE
Character scanning doesn't recognize Kokomi.

### ISSUE THREAD

**Issue by PLN** [Andrewthe13th/Inventory_Kamera#111]
Character scanning stops on Kokomi.

Screenshots of where it stops:
![2021-12-17 18_44_12-Genshin Impact](https://user-images.githubusercontent.com/78331/146587090-fee3578d-97b7-4903-88f6-2c0833d443de.png)
![2021-12-17 18_49_49-Inventory Kamera V1 1](https://user-images.githubusercontent.com/78331/146587125-fad45d64-f5ba-43a5-adbc-dd2e6b1bc07e.png)

Error message:
Could not determine character's name or element
Object reference not set to an instance of an object.
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 23
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

I've tried several times, on both 1280x720 and 1600x900. The error message is the same every time. Raiden and Diona are both scanned correctly as far as I can tell.

**Comment by Andrewthe13th** [comment]
I dont think the new name grabber was ready to grab names like kokomi lol. Thanks for the report.

**Comment by Cupcak3** [comment]
Thanks for the screenshot. I don’t actually have any of the long name characters so I was unable to test them very much. I did not expect them to suddenly wrap around at larger window sizes.

**Comment by PLN** [comment]
I went through my character list, and Sangonomiya Kokomi is the only one I have that wraps. Kamisato Ayaka is the second longest on my roster, but she's still on one line. I don't have Kaedehara Kazuha, who would probably be the second longest after Kokomi.

**Comment by sennafaris28** [comment]
I second this, mine also fails when scanning kokomi, with only `Could not determine character's name or element` as the error

**Comment by Cupcak3** [comment]
Apologies for the oversight. A possible fix is on the dev branch, but I was not able to test it further as I don't have characters with long names. Hopefully the fix is enough and it can find its way into a release soon.

**Comment by PLN** [comment]
No apologies needed, man. We appreciate you working on this wonderful tool as much as you are.

With most characters just having names like Sayu and Yanfei, it's weird Mihoyo even chose to put the whole Sangonomiya in Kokomi's name.

**Comment by PLN** [comment]
I just tried the development branch, and it scans Kokomi correctly:
[genshinData_GOOD_2021_12_19_20_37.json.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/7741473/genshinData_GOOD_2021_12_19_20_37.json.txt)

**Comment by Thaucri** [comment]
I have Kokomi, Ayaka, and Kazuha. Ayaka and Kazuha do not cause problems, but I am having the same problem as others in this thread with the program not recognizing Kokomi. This stops the scan altogether. How do you skip characters in the scan to allow it to continue? Alternatively, are there experimental versions that work?

**Comment by PLN** [comment]
I use the development branch for scanning the characters, then scan artifacts and weapons with the 1.1 release, and manually copy/paste the character data into the 1.1 json file, to get a file that works with Genshin Optimizer. That does require Visual Studio, some jiggering with dll files, and a working knowledge of json files though.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by PLN** [comment]
v1.1.1 worked perfectly for me, including scanning Kokomi, and the whole inventory.

[genshinData_GOOD_2022_01_11_02_35.json.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/7851200/genshinData_GOOD_2022_01_11_02_35.json.txt)

Thank you for all your work!
