### ISSUE TITLE
Scanner unable to validate (almost) all of my artifacts

### ISSUE THREAD

**Issue by Paws26** [Andrewthe13th/Inventory_Kamera#114]
I was using 1280x720 Windowed as suggested and the scanner was only able to validate 15 out of 328 artifacts.
I've also tried different Scan Delay settings with no difference.

![image](https://user-images.githubusercontent.com/81721382/146596787-de417671-3731-4eb5-b5b2-cb7d25e344ad.png)

**Comment by Andrewthe13th** [comment]
Have you tried restarting genshin at the same resolution? There are known issues with resizing the window that messes up the UI a bit.

**Comment by Paws26** [comment]
I have done that just now, closed and opened Genshin at 1280x720 but It had the same result. 
It's weird that it only works for a very few artifacts.

**Comment by Cupcak3** [comment]
You're right that it is strange that it can scan some artifacts but not nearly a significant percent. I will have to write some better error output to be able to tell exactly what's causing the validation to fail.

**Comment by Ame55** [comment]
Hi i had the same problem and on Genshin Optimizer i have notice that only artefact with only FLAT sub stat, none of them have  a percent stat. I don't know if it help.
![image](https://user-images.githubusercontent.com/96357932/146657819-4c242129-fd44-4053-b982-8ba0fb00ff74.png)

**Comment by Cupcak3** [comment]
@Ame55 this seems to be a different issue. Please open a new issue. Additionally if you can provide a screenshot of at least one of the artifacts in-game that should have % substats and how it appears in GO it would be much appreciated.

**Comment by Dranixx** [comment]
I do think it's the same issue, I also get `Unable to validate information for artifact #329` for every artifacts that have a % substats. 

![image](https://puu.sh/IxbIC/91904d5a02.png)

During the scan it didn't show anything in the output artifacts windows, so don't know what causing the validation to fail.

**Comment by Ame55** [comment]
Sorry, I misspoke, I meant that like Paws26, and now Dranixx, only a small part of my artifacts were scanned. The Error `Unable to validate information for artifact #`

![image](https://user-images.githubusercontent.com/96357932/146671640-23f89597-07de-4869-bd18-36e7fc9dca74.png)

And that after transferring the data to GO, I noticed that the scanned artifacts only had flat substat.

![image](https://user-images.githubusercontent.com/96357932/146671676-a1d84448-e49b-41c3-bb8f-f34fc3a33a82.png)

I apologize for not having correctly explained the problem previously.

**Comment by reloxx13** [comment]
same here, worked fine with 1.0. since 1.1 substats are missing

**Comment by tolukolvi** [comment]
I managed to get all scanned after pulling the development version from git, building it with Visual Studio and then replacing v1.1 version files with the newly built files. However, I can't import anything to seelie.me even thou the json-file has all the data in it.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

@tolukolvi : There are two places you can import to [seelie.me](https://seelie.me), one in the `Inventory` panel and one in the `Settings` panel. I believe you need to use the `Inventory` panel's import button and use the GOOD option.

**Comment by Cupcak3** [comment]
I am going to close this issue as one user has reported it being fixed and the other users in the thread have not replied in a while. Please feel free to reopen this issue or to open a new issue should any problems come up.
