### ISSUE TITLE
"1366x768 Unsupported"?

### ISSUE THREAD

**Issue by JohnJillky** [Andrewthe13th/Inventory_Kamera#115]
I'm using V1.1, and encountering this error and unsure if it's a result of the limitations of my device or an error with the Kamera. My genshin unfortunately does not allow 1366x768 to be windowed, but I can set it to windowed mode (or what seems to be as far as I know) with Alt+Enter. E.g., if I alt tab to the Kamera, it will appear on top of the game. Is this sufficient for reaching the 16:9 windowed criteria?
![image](https://user-images.githubusercontent.com/37197441/146612918-e1d45919-b525-44e8-a1c6-90eea49ca685.png)

**Comment by Andrewthe13th** [comment]
the game needs to be windowed to work. But your right 1366x768 is not working. I thought that resolution was a perfect 16:9 resolution but it just slightly off so the code doesn't work. I'll see if this code will work once I try to add the resolution in.

**Comment by JohnJillky** [comment]
So would the Alt+Enter method theoretically be sufficient then? Assuming that resolution was indeed supported

**Comment by Andrewthe13th** [comment]
yes

**Comment by JohnJillky** [comment]
Back to patiently waiting ig lol
