### ISSUE TITLE
Option to limit scanning to high rarity weapon/artifacts

### ISSUE THREAD

**Issue by jesmores** [Andrewthe13th/Inventory_Kamera#117]
Not really a bug, more a feature request. Is it possible to make the scanner stop scanning when it gets to lower rarity weapons/artifacts? It would save a lot of time scanning, since most of the time we only care about 4 and 5* weapons, and usually just 5* artifacts, the rest being XP fodder.

**Comment by jesmores** [comment]
Thinking about it more ... it might even be useful to limit scanning to just weapons that are above a certain level, although I understand that something has to be scanned before the level can be determined anyway. Maybe we can make certain assumptions based on the sorting of items in the inventory screens ...

**Comment by Cupcak3** [comment]
It is certainly possible to add rarity filtering and even level filtering. 

You are correct in that obviously a weapon's level must be at least scanned before an action can be taken on it. Processing is done in the background while an inventory is clicked through. So Kamera may have clicked 2-3 items beyond what the threshold could be by the time the first beyond the threshold is finally processed. This sounds like a suitable compromise.

**Comment by Cupcak3** [comment]
This feature has been added to the [v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease) version.
