### ISSUE TITLE
couldn't determine rarity for artifact

### ISSUE THREAD

**Issue by captainduna** [Andrewthe13th/Inventory_Kamera#121]
inventory scanner clicked through all my artis and exported the GOOD json file but the json file is empty; this is the error i got
![image](https://user-images.githubusercontent.com/89864523/146653771-90806488-2e04-4ebe-b6f2-a5d62d3c1344.png)

**Comment by captainduna** [comment]
i don't have nvidia filters or any sort of color filter that i know of

**Comment by Cupcak3** [comment]
Can you take a screenshot of Genshin open to your artifacts inventory please?

**Comment by captainduna** [comment]
here it is
![image](https://user-images.githubusercontent.com/89864523/146655064-5a04c006-549b-47b2-9ae9-e2b23226db31.png)

**Comment by Cupcak3** [comment]
Is that the full size of the window while you're scanning? It looks like it is 1920x1080 (which I have not tested for as the game window extends a typical monitor's screen region) but it seems oddly blurry for such a high resolution. The blurriness might be why the scanner cannot find the artifact's rarity.

**Comment by captainduna** [comment]
yes that is the full size- in settings i set it to be 1280 x 720 but in order to have genshin impact and the scanner open at once i have to alt-enter. i think this might be the cause of the blurriness

**Comment by captainduna** [comment]
not sure if there is a way to have both genshin and the scanner open without having to alt-enter

**Comment by Cupcak3** [comment]
Are you running Genshin through a shortcut with the `-popupwindow` option by chance? That is one reason that I can think of that would need you to use alt-enter to change between fullscreen and windowed modes.

The upscaling from 1280x720 will cause a problem for the scanner as it relies on the window size being the same as the in-game resolution.

**Comment by captainduna** [comment]
oh yes i just ran it through the shortcut with -popupwindow and used alt-enter and it seems to have worked! tysm!
