### ISSUE TITLE
InventoryKamera dont run

### ISSUE THREAD

**Issue by NezoreXn** [Andrewthe13th/Inventory_Kamera#123]
when i double click the file, the same dont launch and windows asks me with which program I want to open it

**Comment by mineminemine** [comment]
Did you extract the .zip file? The file you need to open is `InventoryKamera.exe`.

**Comment by Cupcak3** [comment]
This is an old issue and @NezoreXn has not responded so I am going to close it. Please reopen this issue if you have any questions
