### ISSUE TITLE
inventorykamera error

### ISSUE THREAD

**Issue by Kideathh** [Andrewthe13th/Inventory_Kamera#132]
i don't really get what is wrong 
   à InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() dans B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:ligne 207

**Comment by Hatyk** [comment]
Having the same problem

**Comment by Cupcak3** [comment]
@Kideathh do you have any other information you can give us about the error or have you resolved it?

**Comment by Cupcak3** [comment]
I am going to close this issue as no more useful information has been provided in quite some time. Please feel free to reopen this issue or to open a new issue should problems come up.
