### ISSUE TITLE
Scanner skipping rows and columns

### ISSUE THREAD

**Issue by AgentPARTY** [Andrewthe13th/Inventory_Kamera#136]
While scanning in 1280x720 windowed resolution, the scanner will skip the 2nd row in the weapons tab and the 1st and 2nd columns in the artifact tab.

**Comment by Ryrin45** [comment]
Same for me except it skips the 4th column in the artifact menu.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by Cupcak3** [comment]
I am going to close this issue as feedback hasn't been given in over a month. Recent releases have also improved on this issue. Feel free to reopen or create a new issue if you still experience this problem.
