### ISSUE TITLE
Images aren't lined up properly

### ISSUE THREAD

**Issue by gianni35011** [Andrewthe13th/Inventory_Kamera#138]
None of the screenshots are lined up properly. Any fixes for this?:

![4_0](https://user-images.githubusercontent.com/28686287/147432760-4184a5ab-2655-4114-bc6b-c686769c5af0.jpeg)

**Comment by jalil49** [comment]
check your screen resolution, the aspect ratio might not be supported

**Comment by gianni35011** [comment]
Thankyou yeah that appears to be the problem. Playing around with the CaptureRegion function and moving it 47 pixels to the left seems to have fixed all the issues.
