### ISSUE TITLE
[Request] Scan moras similar to the total number of artifacts

### ISSUE THREAD

**Issue by JJonnick** [Andrewthe13th/Inventory_Kamera#139]
I don't know if it has already been planned.

But would it be possible to scan the Moras when scanning the materials, as it is done when scanning the total number of artifacts?

**Comment by Andrewthe13th** [comment]
Yea thanks for the suggestion. I will be added eventually for materials. Just more focused on getting rid of all the issues we have right now.

**Comment by Cupcak3** [comment]
This feature has been added to the [v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease)
