### ISSUE TITLE
Scanner Crashes while doing Artifacts

### ISSUE THREAD

**Issue by RS257** [Andrewthe13th/Inventory_Kamera#140]
Im using 1.1 and following the instructions. I have been able to do the other 4 scans no problem.

I currently have 1289 artifacts in my inventory and the scanner seems to be going through and screenshotting all 1289 of them and quitting at the paimon screen. However in the app when it is still catching up, and when it reaches 865 the app crashes. I have tried this on all 3 delays and restarting the game on the recommended size and the issue still persists.

**Comment by SupaSaucySimba** [comment]
Having the same issue except it wont even get through all the artifacts. Did the same troubleshooting steps as well.

**Comment by erebfaer** [comment]
![image](https://user-images.githubusercontent.com/11277129/147709013-f6df033d-bc1f-4f5b-9323-e6421b721694.png)

Same issue, consistently crashes on this artifact

**Comment by OrangeBabette** [comment]
same problem :((

**Comment by giuliano0** [comment]
Hi all. Similar issue, you can see the artifact that crashed it below.

It went okay after I removed the artifact so I cannot say if it was consistent.

![image](https://user-images.githubusercontent.com/1154180/147863004-3eac9227-5b2d-4cfe-a672-a222af0425bc.png)

**Comment by SXN31** [comment]
![image](https://user-images.githubusercontent.com/43016545/147866256-e40ce930-7582-4aaa-9ec0-11462bed2349.png)
I got a crash after it stopped on this artifact.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
