### ISSUE TITLE
Couldn't find a way to export into Seelie format

### ISSUE THREAD

**Issue by Durianator** [Andrewthe13th/Inventory_Kamera#141]
Hello, hope you had a good day.
According to Read Me, this program can export data in either GOOD or Seelie format.

![image](https://user-images.githubusercontent.com/58900127/147541894-a4077b31-fb62-4774-9e0e-bd714189b39e.png)

However, I couldn't find a way to export into Seelie format.

![image](https://user-images.githubusercontent.com/58900127/147542654-6733608f-a2ad-4f3c-b0e3-19c1056f4ad6.png)

Not sure if I missed any instructions.

**Comment by SimplyArmin** [comment]
As far as I remember the Seeli format is obsolete since the purpose was for importing into Genshin Center. Since they support the GOOD format the dev removed it again.

**Comment by Durianator** [comment]
> As far as I remember the Seeli format is obsolete since the purpose was for importing into **Genshin Center** & **Seeli.me**. Since they support the GOOD format the dev removed it again.

I think the dev forgot to edit the README.md.

**Comment by Cupcak3** [comment]
As others have said, we are no longer exporting to Seelie format as [seelie.me](https://seelie.me) now supports importing materials in GOOD format. The README has been updated.
