### ISSUE TITLE
couldnt determine artifact rarity

### ISSUE THREAD

**Issue by misugashi** [Andrewthe13th/Inventory_Kamera#142]
the scanner goes through my artifacts 1 by 1, but only puts out the error message "couldnt determine artifact rarity"
ive also set it up like it says below

![Screenshot (67)_LI](https://user-images.githubusercontent.com/96683011/147595283-830e38cc-29fd-46cb-a1a7-03679e93f89e.jpg)

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
