### ISSUE TITLE
THE G.O DONT DETECT THE FILE

### ISSUE THREAD

**Issue by Keqin12** [Andrewthe13th/Inventory_Kamera#143]
when i select the file json on Genshin Optimizer the file stills loading infinitly and dont do nothing.How can i fix it?

**Comment by Cupcak3** [comment]
Please use [this website](https://jsonlint.com/) to validate the json file's text. If it is not valid please upload the json file to this issue so that we may further help with the issue.

**Comment by Cupcak3** [comment]
I am going to close this issue no new information has been given in a while. Please feel free to reopen this issue or to open a new issue should any problems come up.
