### ISSUE TITLE
Wrong values in artifacts

### ISSUE THREAD

**Issue by DiegoPerezGarcia** [Andrewthe13th/Inventory_Kamera#144]
I've been scanning with the last version and I started to have troubles with the values of the artifacts. For example this is a capture of 5 artifacts that have problems like DEF 66.0%. All the artifacts are getting values like that.
![image](https://user-images.githubusercontent.com/72458271/147664859-ac71eea4-e9b2-4b93-b540-0e4129859801.png)

**Comment by DiegoPerezGarcia** [comment]
json:
{"setKey":"HuskOfOpulentDreams","slotKey":"flower","rarity":5,"mainStatKey":"hp","level":20,"substats":[{"key":"critRate_","value":105.0},{"key":"def","value":23.0},{"key":"enerRech_","value":104.0},{"key":"critDMG_","value":179.0}],"location":"Albedo","lock":true,"SubStatsCount":4,"Id":0}
result:
![image](https://user-images.githubusercontent.com/72458271/147666418-02114785-f733-4f3a-b4a2-012babcb9239.png)
original:
![image](https://user-images.githubusercontent.com/72458271/147666436-98bcd927-65bd-479a-8e43-6f76793992cb.png)
The scanner is not getting the coma of the value :(

**Comment by Kakarlos** [comment]
I'm having the same problem here

**Comment by Jolopundrio** [comment]
At least In Windows 11, if you go to Control Panel, Clock, Language, and Region, if you choose Regional and Language Options and then change the language to English, everythings seems to work ok. I am quite sure that if you change "." for "," as separator, without changing the language, the effect is the same

**Comment by Dahmsk** [comment]
Hi guys, I stumbled upon this issue today and decided to fixed it. I Forked the project and created a Pull-Request #158  for this fix.

Nice App, keep it going!

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by DiegoPerezGarcia** [comment]
It works fine now!! Ty for the fast update ^^
