### ISSUE TITLE
Unable to validate information for artifact

### ISSUE THREAD

**Issue by fsirkot1** [Andrewthe13th/Inventory_Kamera#145]
Inventory Kamera works for weapons & characters but when says Unable to validate information for artifact when it scans artifacts

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
