### ISSUE TITLE
[BUG] Character scanner aborts on Geo Lumine

### ISSUE THREAD

**Issue by JamielleVelasquez** [Andrewthe13th/Inventory_Kamera#146]
![image](https://user-images.githubusercontent.com/65398417/147681530-ac83fa74-d0f7-4b2f-b5f4-b756bb0041d9.png)
Scanner stops short when lumine gets scanned
If lumine is the first character, scanner aborts
My lumine is geo lvl 90 with black sword, c6, 1-8-8 talents

**Comment by Andrewthe13th** [comment]
thanks for the post.

**Comment by Cupcak3** [comment]
Can you give us more information on what the error is in the error log?
