### ISSUE TITLE
feature suggestion) option to scan via rarity

### ISSUE THREAD

**Issue by xesgnik** [Andrewthe13th/Inventory_Kamera#150]
I usually only need info for 5-star artifacts (rarity:5), which accounts for probably 10-20% of all the artifacts, but program always scans to the 1-star artifacts. Is it possible to implement rarity filtering?

Thank you!

**Comment by Cupcak3** [comment]
This has been implemented in the [v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease).
