### ISSUE TITLE
Scanning stop when it was Kokomi

### ISSUE THREAD

**Issue by xFataL** [Andrewthe13th/Inventory_Kamera#152]
Scanning stopped when it was Kokomi's turn in the character.

**Comment by sumiranpradhan** [comment]
Yep same here. Tried putting koko in slots 8-4-1 and whenever it reaches kokomi > attributes the cursor stops for a minute or so, and then goes back to paimon menu and starts scanning other items ( that is, it skips all characters after Kokomi even if she's the very first character to be scanned. )

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
