### ISSUE TITLE
Scan Doesnt Start

### ISSUE THREAD

**Issue by SNKYNinja** [Andrewthe13th/Inventory_Kamera#153]
Attempted to divide by zero.
   at InventoryKamera.Navigation.GetAspectRatio() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 120
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 192

**Comment by Cupcak3** [comment]
This seems to be only possible in the event that the game window's width and/or height are 0. These values are critical in how Kamera functions but I'm trying to figure out what circumstances can lead to this.

Can you answer these few questions:

1. What is your monitor resolution?
2. What was your game's resolution?
3. Is your Genshin executable called `GenshinImpact.exe`?
4. Does the problem occur if Genshin is not minimized and is on top of every other window of your desktop?
5. Does the problem occur if Genshin's window is contained completely on one monitor's screen?

**Comment by Cupcak3** [comment]
I am going to close this issue as my questions have not been answered in a while. Please feel free to reopen this issue or to open a new issue should any problems come up.
