### ISSUE TITLE
Crash with System.ArgumentNullException while scanning artifacts

### ISSUE THREAD

**Issue by chinhodado** [Andrewthe13th/Inventory_Kamera#159]
``` 
An unhandled exception of type 'System.ArgumentNullException' occurred in mscorlib.dll
Value cannot be null. 
System.ArgumentNullException: 'Value cannot be null.
Parameter name: key'
```
![image](https://user-images.githubusercontent.com/1388219/148175928-9c2b6d6e-b675-45e7-aef5-965ff2cfe6e1.png)
![image](https://user-images.githubusercontent.com/1388219/148175955-f1fa4720-9fc3-4482-a8a9-3c0bcba79a07.png)

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
