### ISSUE TITLE
Crash when finish scaning artifacts

### ISSUE THREAD

**Issue by Christalyum** [Andrewthe13th/Inventory_Kamera#161]
It just crash... Scan artifacts and crash when finish

**Comment by Andrewthe13th** [comment]
ok, if you can figure out more details. That would be helpful

**Comment by Christalyum** [comment]
I will try, if u something dont understood Im bad with english. Anyway, there is thing, when I start scanning on resolution 1280x720 it scan artifact and when finish artifacts it just crash not show nothing just close self and nothing happend, but on 1680x1050 it work briliant and thank you for this software it helps a lot! <3 anyway I recommended you just remove 1280x720 and it will be fine 💯 :)

**Comment by Andrewthe13th** [comment]
Interesting. Thanks for the feedback.

**Comment by Cupcak3** [comment]
Hi there. Sorry for coming back to this issue after a while. Please let us know if this has been corrected in recent releases or pre-releases so that we may close this issue. Thanks!
