### ISSUE TITLE
New species of fish == new problems...

### ISSUE THREAD

**Issue by Vasilic-Maxim** [Andrewthe13th/Inventory_Kamera#165]
Hi there. With the release of update 2.4, a new problem with the scanner arose. Here is how to reproduce the issue:
- open Genshin Impact
- set its resolution to 1280 x 720
- go to the Paimon menu
- open Inventory Kamera 1.1
- select the "Materials" checkbox in the "Scan Items" list
- press the "Scan Genshin" button

After the IK reaches "Divra Rai":
- the page is scrolled
- the cursor is moved to the last element in the last row
- cursor moves backward

Video:
https://user-images.githubusercontent.com/10743063/148580593-3125eb42-1cb7-4ed2-a3f6-d9fa05f0e056.mp4

**Comment by Vasilic-Maxim** [comment]
The same thing happens with the new world boss materials. It seems that you have some kind of condition that if the item name is in a set of acceptable names then get its data, otherwise do another thing. Guys, this is not a fault-tolerant approach. If with each new patch we will get new materials we will face the same issue over and over again. A better approach might be to get any item data and if the name of an item is not registered, then make a record in the log. That way users will not have to wait until the new version of the application would be released.

**Comment by Cupcak3** [comment]
Hi there. We have moved the functionality of updating Kamera with new materials/weapons/artifacts/characters etc., to the user. You can update these lists automatically using the updater under options (assuming the recent version has been [dumped here](https://github.com/Dimbreath/GenshinData)) or you can update the items manually in their proper json found under `inventorylists`. If you decide to go the manual route, updating is quite straight forward but I can provide steps if necessary.

**Comment by Vasilic-Maxim** [comment]
@Cupcak3 thanks for your reply. Please add information about lists-update workflow in the repository description. If it were where I would not bother you. Thanks again for your help 🙏
