### ISSUE TITLE
scanning done, but no json file created

### ISSUE THREAD

**Issue by clanchestonly** [Andrewthe13th/Inventory_Kamera#166]
problem as above, no error is shown and my knowledge isnt that good, so i cant explain what happened
just that i did a scan today a few times, but no json file is created after the scanning is done

**Comment by Cupcak3** [comment]
Hi there. Sorry for getting to this problem so very late. Are you still experiencing this problem in any of the recent releases or pre-releases?

**Comment by KindPandaGIT** [comment]
> Hi there. Sorry for getting to this problem so very late. Are you still experiencing this problem in any of the recent releases or pre-releases?

I do

**Comment by KindPandaGIT** [comment]
It happens when I stop scanning manually, by pressing "Enter". I don't need to scan +0 artifacts. The scanner works fine if I scan the whole list.

**Comment by Cupcak3** [comment]
Stopping the scan by pressing enter does not export any JSON file. That is how it works currently but we may change that soon.
