### ISSUE TITLE
Error Scanning Artifacts

### ISSUE THREAD

**Issue by themen098s** [Andrewthe13th/Inventory_Kamera#172]
Once the program scans an artifact, is will throw an error saying "Unable to validate information for artifact #.."
![afbeelding](https://user-images.githubusercontent.com/41344606/149024991-22ea2651-1c4a-4fc7-86df-6cb5017c6908.png)

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by themen098s** [comment]
Using the v1.1.1n this issue is resolved. Thanks!
