### ISSUE TITLE
v1.2 skipping 6th column

### ISSUE THREAD

**Issue by Cunningcory** [Andrewthe13th/Inventory_Kamera#173]
I've tried various 16:9 and 16:10 resolutions.

Items are in rows of 7. Sometimes, but not all the time, the 6th item of every row is skipped. I first noticed it when scanning artifacts. I restarted and then it seemed to work fine until it got to materials and then skipped the 6th item for half of the materials scan before correcting and hitting all 7 again. I have it set to a 50ms delay. I'm on an ultrawide monitor but I have the resolution set correctly for the scan and restarted Genshin after setting the resolution.

**Comment by Andrewthe13th** [comment]
Yea I have noticed this as well sometimes. Thanks for testing and telling me your findings. I think I will need to fix an issue in the programming.

**Comment by Cupcak3** [comment]
Can you try scanning the same inventory tabs after moving to different places in the world?

 The algorithm that the scanner uses to find rows and columns of items can sometimes be sensitive to the colors of the heavily blurred background. If the colors of the background blur with the dominant color corresponding to the rarity of the item then that's when I found this sort of issue happened in testing.

**Comment by Cunningcory** [comment]
> Can you try scanning the same inventory tabs after moving to different places in the world?
> 
> The algorithm that the scanner uses to find rows and columns of items can sometimes be sensitive to the colors of the heavily blurred background. If the colors of the background blur with the dominant color corresponding to the rarity of the item then that's when I found this sort of issue happened in testing.

Nothing I could do would get it to scan all the artifacts properly. It consistently would skip one artifact of each row, despite changing backgrounds and times of day. I did notice changing the time of the day could get it to skip an entire section (daytime made the scanner skip weapons completely) and at one point made it worse where it was skipping two artifacts in each row. Toggling to just scan artifacts also didn't work. I could not find any combination that would scan artifacts properly. It always would skip at least one in every row.

**Comment by Cunningcory** [comment]
I switched back from a 16:10 resolution to a 16:9 resolution and was able to get it to not skip as much. At 0ms it seems I missed 8 artifacts and at 100ms delay I missed 5.

**Comment by Cupcak3** [comment]
Please check out the [v1.2.2 release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.2). It improves on finding inventory items as well as an update for the game's v2.5 inventory UI update.
