### ISSUE TITLE
Genshin's window width cannot be 0

### ISSUE THREAD

**Issue by HanamiBunny** [Andrewthe13th/Inventory_Kamera#175]
My Display Mode was set to *1920x1080 Fullscreen*.

`Genshin's window width cannot be 0`

`   at InventoryKamera.Navigation.GetAspectRatio() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 127`

`   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 169`

**Comment by Andrewthe13th** [comment]
this program only works in windowed. turn off fullscreen

**Comment by Cupcak3** [comment]
Step 6 bullet point 2 in the readme
> Under Graphics, set Display Mode to any windowed resolution that is 16:9 or 16:10

**Comment by mehertikkas** [comment]
I have the same issue but my display mode is set to 1280x720 windowed
