### ISSUE TITLE
[BUG] Scanner skipping weapons section

### ISSUE THREAD

**Issue by Resistus-Ohmegus** [Andrewthe13th/Inventory_Kamera#176]
Just downloaded and tried the latest version and it's been skipping the weapons section for me, I tried unchecking everything except weapons but it gets stuck at the last weapon and won't finish the scan, my little brother has been using it too way before me and(edit) he also has this issue, can I get some help

I'm using resolution of 1600x900 and have tried other resolutions with the same results

Everything Checked
Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   at InventoryKamera.WeaponScraper.ScanWeaponCount() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 467

   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 22

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80

Weapons Only 
Could not parse Traveler's username

Thread was being aborted.

   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)

   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)

   at InventoryKamera.Navigation.SystemRandomWait(Speed type) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 438

   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 79

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80

When I exoprt the file to genshin optimizer it only gives the characters the basic lvl 1 default weapon
![WeaponInventory](https://user-images.githubusercontent.com/55318986/150752608-3d2f49da-ee61-40eb-9472-87fcf08e746c.png)

(edit) using the version before it and was able to finally scan the weapons

**Comment by Cupcak3** [comment]
Not being able to order traveler name and input string not being in correct format errors likely mean that the regions we're scanning for these pieces of information are misaligned. Usually this will result in a blank region being scanned. 

Can you tell me if you have the application zoom set to either normal or 100%? I don't remember what the setting is off the top of my head. Just make sure it's at the default value. 

#Also please be sure you're not using any sort of fullscreen trick to make the windowed game into borderless windowed. This will still make the scanner believe the game is 1600x900 despite it being the size of your monitor.

The `thread was being aborted` error is harmless. It's a default error thrown when a thread is sleeping and forcefully interrupted (ie. when you press enter). It's not particularly clean but we'll work on a different method. 

Characters being given weapons is half working as intended. If weapons and characters are scanned, and a character is never given a weapon, we just give them a basic weapon. However we didn't write code to account for the event in which weapon scan section failed.

**Comment by Resistus-Ohmegus** [comment]
I have two monitors that have the same resolution but different scalings, 

![image](https://user-images.githubusercontent.com/55318986/150895835-9c87e09b-70b1-4f2d-8c35-8b5939c9a175.png)

![image](https://user-images.githubusercontent.com/55318986/150895857-90acc33d-baa1-4b6b-9b2a-3c7859260023.png)

monitor 2 is my main monitor 

![image](https://user-images.githubusercontent.com/55318986/150896244-b8d36ebe-f567-4476-9da7-c94fbc9f1ce6.png)

I don't know any way to trick my screen to make it full screen while being 1600x900


I also mentioned my lil brother having the same issue, this is his settings 

![image](https://user-images.githubusercontent.com/55318986/150897189-f0437134-4da8-4c47-a306-a0bc976985ab.png)

![image](https://user-images.githubusercontent.com/55318986/150897244-889d2415-c558-4103-992c-f5662c7aab19.png)

and this is the error that shows up on his side

Insufficient items found in weapon inventory
   at InventoryKamera.WeaponScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 154

   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 23

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80

 is not a valid set name

Unable to validate information for artifact ID#317

 is not a valid set name

Invalid artifact set name
Artifact ID: 317
Set: 
Rarity: 4
Level: 12
Slot: goblet
Main Stat: hydro_dmg_
Substat 1: enerRech_ + 10.4%
Substat 2: critDMG_ + 5.6%
Substat 3: atk_ + 4.7%
Substat 4: def + 28
Locked: False
Equipped character: Mona


Unable to parse mora count

**Comment by Cupcak3** [comment]
Thanks for the screenshots.

On your side:

- Please try aligning your monitors virtually in Windows. It's possible that the virtual empty space above monitor 1 and below monitor 2 might have some sort of affect on screen-space coordinates.
- Additionally are there any screenshots in the subfolders of the `logging` folder than you can provide? These might confirm the point above.

On your brother's side:

- His monitor resolution of 1440x900 (16:10 aspect ratio) **might** be the source of the issues. I'm not sure about Andrew, but I test various *Genshin* resolutions but with a constant monitor resolution of 1920x1080. If possible, please try to change his monitor resolution to 1920x1080. If it's not possible then screenshots from the bullet points below might confirm this to be the issue.
- The `Insufficient items found in weapon inventory` and `Unable to parse mora count` errors generate associated screenshots to the `artifacts` and `materials` folders, respectively, within the `logging` folder. Please provide those here as they'll give a better idea of what's going on there.
- The `Unable to validate information for...` error also generates screenshots for each weapon and artifact that fails to validate. They can be found in their respective folders as well in the `logging` folders. Please provide one screenshot (or a couple if there are multiple) here along with the description of what the error log says is invalid (for each screenshot if more than 1).

**Comment by Resistus-Ohmegus** [comment]
We both did a few things

we re-updated the MS Visual c++

I unplugged my second monitor and kept my windows display settings on default
it finally scanned the weapons but it still showed some error
Unable to validate information for weapon ID#45


Invalid weapon level

Invalid refinement level

Weapon ID: 45

Name: FesteringDesire

Rarity: 3

Level -1

Refinement: 10

Locked: False




Unable to parse mora count

![image](https://user-images.githubusercontent.com/55318986/150924654-0f51b525-1b91-43d7-af31-5eb0af9c1f1b.png)

![image](https://user-images.githubusercontent.com/55318986/150924513-f921475f-7f75-4bbe-9915-348c675b6985.png)

![image](https://user-images.githubusercontent.com/55318986/150924535-5eebf891-0afb-432b-91d0-858e1a8a9b69.png)

the materials and weapons subfolder had screenshots in them


on my brother's side, after he updated we put his resolution on 1920x1080, I think his screen doesn't fully support it though cause it can't get to the corners

![image](https://user-images.githubusercontent.com/55318986/150924872-6fd1fd0f-2a9d-429e-b916-5778a689fad4.png)

and this is the error on his

Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   at InventoryKamera.WeaponScraper.ScanWeaponCount() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 467

   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 22

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80

 is not a valid set name

Unable to validate information for artifact ID#317

 is not a valid set name

Invalid artifact set name
Artifact ID: 317
Set: 
Rarity: 4
Level: 12
Slot: goblet
Main Stat: hydro_dmg_
Substat 1: enerRech_ + 10.4%
Substat 2: critDMG_ + 5.6%
Substat 3: atk_ + 4.7%
Substat 4: def + 28
Locked: False
Equipped character: Mona

**Comment by Cupcak3** [comment]
For you:
- You can ignore the weapon error and screenshot. As you can see from the screenshot that it's an enhancement ore and we aren't collecting those yet so it shouldn't even be generating an image for that so thanks for bringing it to my attention.
- Obviously you can see the Mora count is cut off in the screenshot. By chance how many primogems do you have? It's possible that the number of primogems you have causes the UI to shift the location of mora left or right. I have 1783 primos so my UI looks something like the screenshot below with the mora UI element starting roughly between the first and second column of items. Let me know if yours starts around there or if it's further to the left/right.
- Thanks for the information on unplugging your monitor. Please try what I suggested in my previous comment as well. It will help to confirm things for me.
![image](https://user-images.githubusercontent.com/8845977/150929112-e53b7f8d-c78b-4a16-b4a1-78b28503607d.png)


For your brother:
- I am working on a build to try and improve the scanner being unable to find the weapon/artifact count from the top right corner. It is interesting that it is unable to find the number of weapons yet it can find the number of artifacts. How many of each does your brother have?
- Is it just that one screenshot that's being generated for artifacts? Are the other artifacts in his inventory being scanned and exported? It seems to be a rare occurrence given it happens at artifact 317 and not before. 
I encourage your brother to use the screenshot generated to manually create the artifact on whatever website you are using this scanner for, which I assume is Genshin Optimizer. Make sure to add it ***after*** uploading the JSON file so it does not get overwritten.

**Comment by Resistus-Ohmegus** [comment]
![image](https://user-images.githubusercontent.com/55318986/150933728-3043aea5-c9c5-4463-a119-3ca952501871.png)

![image](https://user-images.githubusercontent.com/55318986/150936110-1101ffea-b82f-4d1c-b471-bf93d9d06685.png)


here is a screenshot of my inventory, being it only having one primo 

i put back my second monitor and tried scanning with both of them levelled and not, results are the same as when I got the error with a the festering desire

Unable to validate information for weapon ID#45


Invalid weapon level

Invalid refinement level

Weapon ID: 45

Name: FesteringDesire

Rarity: 3

Level -1

Refinement: 10

Locked: False

Next I logged in his acc on my computer and tried a scan, and it just gave me a one line error

Could not determine Noelle's level

![image](https://user-images.githubusercontent.com/55318986/150937328-9579704c-8d79-4829-a3fd-d9fd686d0378.png)

![image](https://user-images.githubusercontent.com/55318986/150937375-0eae6e1d-6d55-419a-9ceb-2911644cf82b.png)

![image](https://user-images.githubusercontent.com/55318986/150937403-98dc473b-573d-4882-a05a-44711f921f3e.png)

this is his number of artifacts and weapons

**Comment by Resistus-Ohmegus** [comment]
It's happening again for some reason, I backtracked to some of the things I did from between it was working and it wans't,  the last time I did a scan was when I was using my lil brothers acc to get the one line error from the app, next I closed the game to do some homework, and after a while of replaying I decided to fiddle with my artifacts and weapons again, the same issue happened again(I'm not sure if it's the same error message from the first time)

Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)


   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)


   at InventoryKamera.WeaponScraper.ScanWeaponCount() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 467


   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 22


   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80

![image](https://user-images.githubusercontent.com/55318986/151034857-e8d9ff6b-7f3d-4549-827c-84ec83af455a.png)


after doing scans multiple times I tried some solutions we had before, first was checking my windows and game resolution, and unplugging my second monitor, still having the same issue

![image](https://user-images.githubusercontent.com/55318986/151035213-80d56a60-a48a-4783-a810-328bf0d8c4b5.png)
![image](https://user-images.githubusercontent.com/55318986/151035228-58224ff0-70eb-4ccc-8697-df81773c51f7.png)

I repaired MS visual but still didn't work, I uninstalled it and then re-installed it, didn't work.

![image](https://user-images.githubusercontent.com/55318986/151035303-cdddf62a-598f-4794-bb1c-4b6994ffae3a.png)
![image](https://user-images.githubusercontent.com/55318986/151035333-7c6f9606-8a2d-4795-a487-aa8699110319.png)

these are pictures from logging folder but these were from my attempts before and while troubleshooting on my own


But here is where it gets weirder
I tried going back to V1.1 and it gave me this

No items detected in inventory
   at InventoryKamera.WeaponScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 129
   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 19
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 73
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

![image](https://user-images.githubusercontent.com/55318986/151035621-36a6a46c-3892-4620-97c2-955bb08eca71.png)

there was no logging folder in this one so I dont have anythng to send from there
![image](https://user-images.githubusercontent.com/55318986/151035718-e9cf38de-8f5f-4dfe-a1b7-458f0aebb210.png)

**Comment by Cupcak3** [comment]
Screenshot logging was introduced in V1.2 so nothing would be generated by V1.1.

[This screenshot](https://user-images.githubusercontent.com/55318986/151035333-7c6f9606-8a2d-4795-a487-aa8699110319.png) tells me that the game didn't correctly navigate to the weapon inventory to begin its scan. This could be for a few reasons like non-default keybinds (which you can adjust either in Genshin or under `Options` in Kamera) or the game just took longer to execute inputs than expected. As a result I assume this is what generated the `No items detected in inventory` error. You can increase the scanner delay to hopefully give the game enough time to navigate. I am not sure if V-Sync or a 30fps cap affects the time it takes for menus to change.

As I've mentioned before you can ignore any screenshot generated that shows enhancement ore. You have made me aware of it and I will be taking a look at it.

**Comment by vhqr** [comment]
Any definitive solution? I'm having the same problem as OP him/herself at ScanWeaponCount. I didn't change the keybind, but it goes wrong before ever opening the weapon inventory menu.

**Comment by Cupcak3** [comment]
@vhqr please make sure you start the game from the ESC menu (with Paimon visible). If the menu closes and your character attacks then please triple check your keybinds in-game *and* in Kamera under `options`.

**Comment by Cupcak3** [comment]
Please check out later versions and let us know if the issue persists. If it does please reopen this issue.

**Comment by Resistus-Ohmegus** [comment]
Hi I come back to Genshin for a bit to see the issue and I'm happy to see its working fine now, even though I dont play as much anymore thanks for this.

On a side note my brother found this bug about gladiators artifacts being scanned as gamblers even though he doesnt have any gamblers

Luckily I used the feature of log all screenshots in my scan and saw that its not an issue with the Kamera and i think its on the site we used ,cause the log saw that its a gladiators cup but the site saw it as a gamblers cup

Here is a log that it saw a weapon in my inventory and the log of the cup that genshin optimizer thought as a gamblers cup
![Screenshot 2022-07-24 124152](https://user-images.githubusercontent.com/55318986/180632738-76d0d3ef-8cce-4e12-b7cf-78c84074f2b0.png)
![Screenshot 2022-07-24 123709](https://user-images.githubusercontent.com/55318986/180632739-8aa2bcce-f420-4d46-b9b0-5f8d902e7f7c.png)

**Comment by Resistus-Ohmegus** [comment]
Again Thank you for this amazing tool and the efforts you made to still make it better
