### ISSUE TITLE
[BUG] Scanner stops at Mystic enhancement ore

### ISSUE THREAD

**Issue by sonalita** [Andrewthe13th/Inventory_Kamera#177]
Just downloaded this but getting an error on the weapon scan, which then stops the whole scan from continuing. See screenshot below - I have tried all the different scan delay options.
I have tried with setting different rarity thresholds.
If I turn off weapon scanning it works (though I did see some artiifact scanning errors but the scan does complete - and rn I'm not bothered about  artifacts)

There are lots of invalid rarity messages, the last part of the  stack trace is:
`
Unable to validate information for weapon ID#69
Invalid weapon rarity
Invalid weapon level
Weapon ID: 69
Name: FesteringDesire
Rarity: 0
Level -1
Refinement: 1
Locked: False

Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at InventoryKamera.Navigation.SystemRandomWait(Speed type) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 438
   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 79
   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line `80``

![image](https://user-images.githubusercontent.com/5406897/151080483-5036f9f9-9302-4361-a955-7b144fef6d16.png)

**Comment by Cupcak3** [comment]
Another user has made us aware of the scanner not handling enhancement materials correctly, even though it shouldn't be trying to handle them at all. If you see any enhancement material pop up at all you can safely ignore it. You can also ignore the `Thread was being aborted` error as well.

From your screenshot I see that it wasn't able validate even the first weapon. Is that error correct? If so there should be screenshots generated under `logging/weapons` and I would ask you to upload a one or two of them and the error descriptions for the ones you upload.

**Comment by sonalita** [comment]
Not at the pc atm, but will do so tomorrow. 

The issue for me is that the errors on the weapon scan are stopping the scanner cold. It does not go on to scan artefacts or other materials so I can't use it to it's fullest extent (i.e. to import into https://seelie.inmagi.com) as I have to exclude weapons.

**Comment by Cupcak3** [comment]
Hmm there is code to catch fatal crashes in each section so I'm not quite sure what is causing it to completely stop in the weapon's section. By chance does the scanner still hard stop if you set the weapon rarity to 5? I will see if I can reproduce the hard stopping behavior you experience.

**Comment by sonalita** [comment]
Hi, so I cleared out the log folder, deleted the previous output file and reran with no delay, min weapon level 5 - and I get the same behaviour. It gets stuck on Mystic enhancement ore as you can see below. I am  running genshin at 2560x1440 windowed on my right hand monitor with the scanner on my left hand monitor.

The error log shows "invalid rarity" for every single weapon. A couple of screenshots from the log folder are also shown below.

sample error log:
Unable to validate information for weapon ID#0
Unable to validate information for weapon ID#1
Invalid weapon rarity
Weapon ID: 0
Name: SolarPearl
Rarity: 0
Level 70
Refinement: 1
Locked: False
Equipped character: Ningguang

Invalid weapon rarity
Weapon ID: 1
Name: DragonsBane
Rarity: 0
Level 70
Refinement: 1
Locked: False
Equipped character: Xiangling


![image](https://user-images.githubusercontent.com/5406897/151127365-39448aeb-1897-4fb4-b7b1-63dfefb0226a.png)

![weapon0](https://user-images.githubusercontent.com/5406897/151127587-2c0dd35f-f965-4735-95ce-e7dd83821a7e.png)
![weapon1](https://user-images.githubusercontent.com/5406897/151127618-490595ab-9f9b-4f77-a4ab-14d6a2b34448.png)

**Comment by Cupcak3** [comment]
Oh wow that's a high resolution and large screenshot. This tells me exactly what we do wrong-ish. A workaround for now would probably be to use a lower game resolution until we can get a fix out for that.

The details: 
We take a pixel somewhere near the top of each card to compare it to rarity colors. *Usually* this is good enough but I was a bit lazy on picking which pixel to use. Since your resolution is so high, that specific pixel actually falls within the darker lining within the top area of the card which makes it not pass the rarity check.

**Comment by sonalita** [comment]
Glad to help. As a software developer myself, I know how frustrating it can be to reproduce user reported bugs and sometimes even harder to fix them :) I will scan at a lower screen resolution for now,

Your support is amazing by the way! I wasn't expecting this to be looked at for a couple of days!

**Comment by sonalita** [comment]
Just had chance to try the scan at 1920 x 1080 windowed. Much better! Some artifact substat parsing errors and it could not parse mora. Examples below.

![mora](https://user-images.githubusercontent.com/5406897/151149665-acf9b505-ccfb-43e9-afcb-9a621fb3e277.png)
![artifact49](https://user-images.githubusercontent.com/5406897/151149706-d4d1bcd7-4d9d-4ad6-b9e7-bb61bd98637a.png)
![artifact65](https://user-images.githubusercontent.com/5406897/151149711-d0c84505-1930-47ee-a222-e299ffe35c1b.png)

**Comment by Cupcak3** [comment]
Glad to hear it's working better.

I'm aware of mora failing to scan and a fix for that should be coming soon-ish. As for the artifacts, it looks like the first one is missing the second and third substats. The `DEF` (flat and %) has given us the most issues in testing so that's probably what's going on here. For now I suggest to use the screenshots to manually add the artifacts into whatever website you are using the scanner for until we can improve accuracy.

**Comment by kwm1800** [comment]
I have same issue, and unfortunately lowering the resolution does not solve this problem for me.

I also tried to run the scanner while facing grey wall of the Mondstadt castle to avoid errors but I still get stuck on the Ore.

**Comment by Ceredril** [comment]
Hey there,

i also have the same issue, i always put down the resolution to full hd before scanning, but the ore completely kills the program. The other weapons before are being scanned fine though.
<img width="447" alt="inventorykamera" src="https://user-images.githubusercontent.com/63151691/152032520-74ffdf0e-c7a0-48fd-bb2a-a448b0053b99.PNG">

**Comment by Cupcak3** [comment]
Hi there. Please check out the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) and let us know if the ore crashing has been fixed.

**Comment by kwm1800** [comment]
> Hi there. Please check out the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) and let us know if the ore crashing has been fixed.

Thank you. I tested it and unfortunately it still happens.

It seems it is not just Ore making the program halts though, at least in 1.2.1 prerelease. If the Ore is located in very first spot on the last row (means Ore is only item on the last row), the scanner stuck at the last weapon on the row before the last.

**Comment by kwm1800** [comment]
I have updated to v1.2.2 and this problem still occurs. Pretty much makes scanning weapons impossible.

Perhaps treat Ore as "weapons" during scanning and fix it after scanning is done?

**Comment by kwm1800** [comment]
I did some more experiments and it is indeed something to do with handling Ore internally, not the issue of scanning process.


When I limited scanner to just scan 4 and 5 stars, the scanner worked fine. It always casued a problem when I include 3 stars.

I got an idea from this and added a 2 star weapon to my inventory; now the scanner worked flawlessly with the 2 star sword.

**Comment by Cupcak3** [comment]
If the issue persists on later versions please reopen this issue and let us know
