### ISSUE TITLE
scanner isn't working i keep getting the same error text

### ISSUE THREAD

**Issue by iBroodx** [Andrewthe13th/Inventory_Kamera#179]
C:\Users\keyon\OneDrive\Desktop\mods\Inventory_Kamera_V1.2\GenshinData is not a valid directory

**Comment by langelkeiser** [comment]
Hi,

Create the directory GenshinData yourself and it will work

**Comment by iBroodx** [comment]
i'm sorry but i dont really know what you mean by this. just make a new folder named 'GenshinData'?

**Comment by Cupcak3** [comment]
Yes just create a new folder with that name if you've deleted it. Otherwise you can select a different output folder.

**Comment by Cupcak3** [comment]
This error has been fixed and automated in the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) version.
