### ISSUE TITLE
Type initializer threw an exception

### ISSUE THREAD

**Issue by CrashingBootcamp** [Andrewthe13th/Inventory_Kamera#181]
The type initializer for 'InventoryKamera.Scraper' threw an exception.
   at InventoryKamera.Scraper.RestartEngines()
   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 66
   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 180

**Comment by Cupcak3** [comment]
Thanks for the report. We are aware of this issue and are working to try and fix it for good.

**Comment by CrashingBootcamp** [comment]
Thank you!

**Comment by Cupcak3** [comment]
Hi there. Please check out the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) version. It includes a possible fix specifically aimed to eliminate this bug. If it hasn't been fixed.. well let's hope the error generated is any more helpful 😅

**Comment by Cupcak3** [comment]
Please check out the note in the latest release patch notes. One user found that installing both the [x64 and x86 C++ 2015-2022 (or 2019) redistributable packages from Microsoft](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) fixed this error.

![image](https://user-images.githubusercontent.com/8845977/154861603-e6387622-c351-414e-bee3-24c3a6bcfdc6.png)

**Comment by CrashingBootcamp** [comment]
Hey, yes this worked for me, thanks very much. Super useful.

Sent wirelessly via neural implant
