### ISSUE TITLE
Artifact scanning stops early if there are more than 1500 artifacts

### ISSUE THREAD

**Issue by briankchan** [Andrewthe13th/Inventory_Kamera#183]
E.g., with 1505 artifacts, only the first 150 get scanned. (This is probably the same issue as #13; I'm not sure if that was supposed to have been fixed, or if it's something that won't be fixed.)

**Comment by Cupcak3** [comment]
Since 1500 is the max of the inventory we check against that, albeit lazily and mostly incorrectly. However we likely won't look into a fix for this specifically. I suggest decreasing your artifact count to below 1500 through enhancements for now.

**Comment by Cupcak3** [comment]
Hi there. [V1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) hopefully parses artifact quantities more accurately. Please let us know if this issue is fixed with that so that we may close it.

**Comment by briankchan** [comment]
Yup, all artifacts get scanned by the prerelease, even if there are >1500 total.
