### ISSUE TITLE
Invalid artifact rarity at high resolutions

### ISSUE THREAD

**Issue by Jeinara** [Andrewthe13th/Inventory_Kamera#184]
Unable to validate information for artifact ID#70
Invalid artifact rarity
Artifact ID: 70
Set: GladiatorsFinale
Rarity: 0
Level: 20
Slot: sands
Main Stat: eleMas
Substat 1: critRate_ + 6,6%
Substat 2: atk + 16
Substat 3: enerRech_ + 21,4%
Substat 4: hp + 209
Locked: True
Equipped character: KaedeharaKazuha

and this same for all my arts, win10, 16:9

![artifact0](https://user-images.githubusercontent.com/12751573/151422152-9c5966e6-12ba-4e96-9345-d5f6191d0199.png)
![artifact1](https://user-images.githubusercontent.com/12751573/151422142-43814b6d-5bcf-4aaf-81a7-48690d13e8b3.png)
![artifact2](https://user-images.githubusercontent.com/12751573/151422146-50e4797b-fb97-4a36-83ec-fc5400e1254c.png)
![artifact3](https://user-images.githubusercontent.com/12751573/151422148-113a9858-ffcb-435c-bdbc-9ea65bdbfc8f.png)

**Comment by Cupcak3** [comment]
Another user reported this as part of issue #177. Since your screenshots are the same dimensions I assume your game window is 2560x1440. They reported that lowering the resolution to 1920x1080 or lower gives better results.

**Comment by Jeinara** [comment]
Yep, that works. Sorry for dublicate.

**Comment by Cupcak3** [comment]
Hi there. The [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) hopefully fixes this bug that happens at high resolutions. Please let us know if it fixes the problem so that we may close this issue.
