### ISSUE TITLE
Nothing other than materials getting scanned

### ISSUE THREAD

**Issue by rsmyst** [Andrewthe13th/Inventory_Kamera#186]
I get insufficient artifact count error for artifacts and so on. What am I doing wrong? I'm not moving mouse and have set window to windowed

**Comment by Cupcak3** [comment]
This error generates a screenshot in the `logging/artifacts/` folder. Please upload that screenshot so that we can help more.

**Comment by rsmyst** [comment]
![ArtifactInventory](https://user-images.githubusercontent.com/30620767/151647452-269c5ffc-f675-4e9e-8a42-aee86ab613e2.png)
here you go!

**Comment by Cupcak3** [comment]
Are you positive your resolution was 1280x720? The screenshot is 1600x900.

**Comment by rsmyst** [comment]
> Are you positive your resolution was 1280x720? The screenshot is 1600x900.

Oh I was just trying out different settings. It didn't work with 720 windows nor 1600x900 windowed. I will try again tomorrow and update
