### ISSUE TITLE
Asking for chinese genshin yuanshen.exe support

### ISSUE THREAD

**Issue by ShiinaRio** [Andrewthe13th/Inventory_Kamera#187]
tysm!

**Comment by ShiinaRio** [comment]
I can change the game language to English just pls make support for that

**Comment by Cupcak3** [comment]
This is something that I have written in on my internal build. I hope to get it out after I fix one or two more bugs.

**Comment by Cupcak3** [comment]
Support for the Chinese client has been added in the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease).
