### ISSUE TITLE
Does inventory_kamera read memory?

### ISSUE THREAD

**Issue by ggez89** [Andrewthe13th/Inventory_Kamera#189]
I am concerned about the bannability of this program. Does it read memory, or inject into memory? How are mouse clicks performed?

Thanks

**Comment by Cupcak3** [comment]
Kamera does not try to access, whether to inject or read, Genshin's protected memory. 

It uses [.Net's Graphics library](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics?view=dotnet-plat-ext-6.0) to screenshot the game's window region, [a .Net Tesseract wrapper](https://github.com/charlesw/tesseract) for text recognition, and [WindowsInput](https://github.com/MediatedCommunications/WindowsInput) for keyboard and mouse simulation.

Although all of this is done "outside" of Genshin, your account is at the mercy of miHoYo. This can be said about all third party software. The most this application interacts with the game is navigating menus.

**Comment by ggez89** [comment]
Thanks, sounds safe to me. I used it. Wonderful program!
