### ISSUE TITLE
5 star rarity not working

### ISSUE THREAD

**Issue by ToastyTickle** [Andrewthe13th/Inventory_Kamera#191]
My 5 star artifacts and weapons both show up as a rarity of 0 but my 4 stars work fine.

**Comment by Cupcak3** [comment]
Hi there. Sorry for the delay in getting to this issue. Are there any more specific details you can provide? Screenshots generated in the `logging` folder will help us to understand the problem more as well.

**Comment by ToastyTickle** [comment]
it actually fixed itself when i tried it again and used another monitor i
had
