### ISSUE TITLE
I can't scan my account.

### ISSUE THREAD

**Issue by AzzinothKG** [Andrewthe13th/Inventory_Kamera#194]
I'm a new user and tried scanner program and i think something wrong with my setting. Please kindly help me solve the problem
in game resolution:  1280x720  60fps
desktop res: 3440x1440

weapon tab
![weapon0](https://user-images.githubusercontent.com/98711283/151715317-b088de22-a9a9-4621-8203-ed61177913e9.png)
artifact tab
![artifact0](https://user-images.githubusercontent.com/98711283/151715332-c78e8095-e8c6-4548-816b-a11d6cc7335e.png)
material tab
![mora](https://user-images.githubusercontent.com/98711283/151715342-65ad8740-68a1-4df6-a7f0-33e67b175908.png)
charactor tab
There is no screenshot. i found program scan 1st character and then  hang at change avartar.

**Comment by Cupcak3** [comment]
Your weapons and artifacts look like issue those in issue #192 and your desktop resolution tells me you at least have access to ultrawide resolutions. As mentioned in that thread, the UI shifts for ultrawide resolutions but stays shifted when changed to a regular resolution without a restart of the game.

**Comment by AzzinothKG** [comment]
> Your weapons and artifacts look like issue those in issue #192 and your desktop resolution tells me you at least have access to ultrawide resolutions. As mentioned in that thread, the UI shifts for ultrawide resolutions but stays shifted when changed to a regular resolution without a restart of the game.

Thank you for your help. I can scan properly.
