### ISSUE TITLE
Invalid monitor display error

### ISSUE THREAD

**Issue by Beidou3142** [Andrewthe13th/Inventory_Kamera#195]
I keep getting the same error that my resolution is unsupported no matter what size I pick. So what resolutions ARE allowed?

**Comment by Cupcak3** [comment]
All 16:9 and 16:10 resolutions are accepted. If all of those resolutions are saying they're not supported then we will need some more information about your setup.

**Comment by Beidou3142** [comment]
Never mind, the issue was resolved once I switched to a different monitor.
