### ISSUE TITLE
V1.2 misses 7th column on weapons scan in 1440p

### ISSUE THREAD

**Issue by Nazuyuki** [Andrewthe13th/Inventory_Kamera#203]
In 2560x1440, it appears that the 7th column get missed completely. Artifact scanning appears to work fine.
It eventually goes into an infinite loop at the end because it's unable to count enough weapons.

It worked fine in 1080p but figured it was worth mentioning as people with 4K displays may not pick a windowed resolution as low as 1080p. Both 4K and 1440p are 16:9 resolutions so it should be working.

**Comment by Cupcak3** [comment]
This is a known issue. I hope to get something out for 4k resolutions soon, or at the very least more helpful debugging outputs, but I do not have a 4k monitor myself to verify with.

**Comment by Ghost-of-Razgriz** [comment]
Hi, it's not just 4k Resolutions. My Display does not run at 4k and my game was running at 1980x1020. (It didn't want what I normally use as 1600x1024.) For me, it would miss the 6th row.

(Unrelated it skipped some mats and when it got to traveler it stopped tracking characters)

**Comment by Cupcak3** [comment]
Please check out the new [v1.2.2 release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.2). It improves on finding inventory items as well as an update for the game's new V2.5 inventory UI update.
