### ISSUE TITLE
Type initializer threw an exception

### ISSUE THREAD

**Issue by J3llis** [Andrewthe13th/Inventory_Kamera#204]
I keep getting this error instanly when i try to start the scan, and it just says scan aborted afterwards

"at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 180"

**Comment by Cupcak3** [comment]
There should be more to the error log above that line. Please copy the whole text box so we can help.

**Comment by J3llis** [comment]
oh i didnt see there was more to it heres the whole error log

The type initializer for 'InventoryKamera.Scraper' threw an exception.
   at InventoryKamera.Scraper.RestartEngines()
   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 66
   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 180

**Comment by Cupcak3** [comment]
Hi there. Please check out the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prereleasehttps://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease). It has a possible fix aimed specifically to fix this issue.

**Comment by J3llis** [comment]
Hi just wanted to update you, v1.2.1 prerealease fixed the error i was getting previously

I did get some "failed to parse errors" though on this pre release build

Failed to parse quantity for DvalinsPlume

Failed to parse quantity for ShadowOfTheWarrior

Failed to parse quantity for RiftbornRegalia

Failed to parse quantity for AgnidusAgateFragment

Failed to parse quantity for GuideToTransience

Failed to parse quantity for CrownOfInsight

Failed to parse quantity for DebrisOfDecarabiansCity


Failed to parse quantity for LustrousStoneFromGuyun

Failed to parse quantity for MistVeiledMercuryElixir

Failed to parse quantity for MaskOfTheKijin

**Comment by Cupcak3** [comment]
Thanks for the update. Those are unfortunately expected as the material quantity scanning isn't as accurate as we'd like. We're working on improving that. I'll go ahead and close this issue.
