### ISSUE TITLE
cant scan, getting an error

### ISSUE THREAD

**Issue by josephisticated** [Andrewthe13th/Inventory_Kamera#206]
C:\Users\josephisticated\Desktop\Inventory_Kamera_V1.2\GenshinData is not a valid directory

**Comment by josephisticated** [comment]
From what I see from other issues, I can fix this by creating a folder named "GenshinData", a fix on the original repository could have been nice though.

**Comment by Cupcak3** [comment]
V1.2.1-prerelease fixes this behavior.
