### ISSUE TITLE
[BUG] Insufficient items in Inventory

### ISSUE THREAD

**Issue by josephisticated** [Andrewthe13th/Inventory_Kamera#208]
![image](https://user-images.githubusercontent.com/53388005/152653488-fd56ae5d-22ee-4ad4-8a1e-aba530645c20.png)
I wanted to scan everything checked here as it can be seen, but the app stopped after materials and gave an error log:

-----------------------------------------------
Insufficient items found in artifact inventory

   at InventoryKamera.ArtifactScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\ArtifactScraper.cs:line 186

   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\ArtifactScraper.cs:line 23

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 96

**Comment by Cupcak3** [comment]
Please consider trying the new v1.2.1-prerelease. It has additional screenshot generation written to help us debug this problem more accurately should you continue to have the problem.

**Comment by josephisticated** [comment]
Seems v1.2.1-prerelease worked for me.
![image](https://user-images.githubusercontent.com/53388005/152656389-2feb9aa7-9ba2-4e98-a12d-529f5a118661.png)

----------------------------
 is not a valid set name


Unable to validate information for artifact ID#1313


 is not a valid set name


Invalid artifact set name

Artifact ID: 1313

Set: 

Rarity: 4

Level: 0

Slot: plume

Main Stat: atk

Substat 1: enerRech_ + 5.2%

Substat 2: critRate_ + 3.1%

Locked: False




Failed to parse quantity for BlackCrystalHorn


Failed to parse quantity for BlackBronzeHorn


Failed to parse quantity for DeadLeyLineLeaves


Failed to parse quantity for AgentsSacrificialKnife


Failed to parse quantity for GoldenRavenInsignia


Failed to parse quantity for HellfireButterfly


Failed to parse quantity for HoarfrostCore


Failed to parse quantity for DragonheirsFalseFin


Failed to parse quantity for VarunadaLazuriteGemstone


Failed to parse quantity for VarunadaLazuriteChunk


Failed to parse quantity for VajradaAmethystGemstone


Failed to parse quantity for VajradaAmethystChunk


Failed to parse quantity for PrithivaTopazGemstone


Failed to parse quantity for TeachingsOfProsperity


Failed to parse quantity for PhilosophiesOfDiligence


Failed to parse quantity for TeachingsOfGold


Failed to parse quantity for PhilosophiesOfTransience


Failed to parse quantity for PhilosophiesOfElegance


Failed to parse quantity for PhilosophiesOfLight


Failed to parse quantity for CrownOfInsight


Failed to parse quantity for ScatteredPieceOfDecarabiansDream


Failed to parse quantity for FragmentOfDecarabiansEpic


Failed to parse quantity for DebrisOfDecarabiansCity


Failed to parse quantity for BorealWolfsNostalgia


Failed to parse quantity for MaskOfTheTigersBite


Failed to parse quantity for NarukamisJoy


Failed to parse quantity for JeweledBranchOfADistantSea


Failed to parse quantity for DreamOfTheDandelionGladiator


Failed to parse quantity for RustyKoi


----------------------------
I couldn't see a problem but got an error log.

**Comment by Cupcak3** [comment]
I am glad to hear that the pre-release version fixed your first problem.

The artifact error should include a screenshot in the `logging\artifacts` folder. Can you please upload that image and say what your game resolution was set to?

The failures to parse quantities is expected as it's not very accurate right now. We are working on improving it.

**Comment by josephisticated** [comment]
![artifact1313](https://user-images.githubusercontent.com/53388005/152771693-24b02347-7c4b-4100-a908-8101b31328ee.png)

**Comment by Cupcak3** [comment]
Recent versions should have this fixed. Feel free to reopen if the issue persists.
