### ISSUE TITLE
Insufficient items in inventory

### ISSUE THREAD

**Issue by amberbestgirl** [Andrewthe13th/Inventory_Kamera#209]
Insufficient items found in artifact inventory

   at InventoryKamera.ArtifactScraper.GetPageOfItems()

   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)

   at InventoryKamera.InventoryKamera.GatherData()

![image](https://user-images.githubusercontent.com/81830199/152657293-ff1a0b02-ef50-4890-87d6-c405f8392818.png)

It keeps failing to scan my inventory once it gets to the point where it scans the number of artifacts in my inventory. My current resolution is 1280x720.

**Comment by Cupcak3** [comment]
Please upload the `ArtifactInventory.png` image found in `logging\artifacts`

**Comment by amberbestgirl** [comment]
![ArtifactInventory](https://user-images.githubusercontent.com/81830199/152659106-9f611180-cb36-4c1c-bd68-b45ef29308ad.png)
