### ISSUE TITLE
V1.2.1-prerelease Yuanshen.exe 1600x900 resolution Error when scanning

### ISSUE THREAD

**Issue by ShiinaRio** [Andrewthe13th/Inventory_Kamera#210]
Unable to parse mora count

Insufficient items found in CharacterDevelopmentItems inventory

   at InventoryKamera.MaterialScraper.GetPageOfItems(InventorySection section, Int32 page)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials)

   at InventoryKamera.InventoryKamera.GatherData()

Insufficient items found in Materials inventory

   at InventoryKamera.MaterialScraper.GetPageOfItems(InventorySection section, Int32 page)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials)

   at InventoryKamera.InventoryKamera.GatherData()

<img width="800" alt="CharacterDevelopmentItemsInventory0" src="https://user-images.githubusercontent.com/90119663/152675488-c4eb9438-7302-4aee-abb9-83c3abfc34bf.png">
<img width="800" alt="MaterialsInventory0" src="https://user-images.githubusercontent.com/90119663/152675492-d744480e-d582-49fd-9d00-51e17c1bc26a.png">
<img width="188" alt="mora" src="https://user-images.githubusercontent.com/90119663/152675497-36062625-3ba1-4da4-8f1f-d641592f3191.png">

**Comment by ShiinaRio** [comment]
I was changing resolution mid game so I restart the game and start the scan but It's acting very weird.
Scanning not in order and miss some items.
That's many pictures in the logging/materials
Failed to parse quantity for HerosWit


Failed to parse quantity for FossilizedBoneShard


Failed to parse quantity for SturdyBoneShard


Failed to parse quantity for ChaosOculus


Failed to parse quantity for ShadowOfTheWarrior


Failed to parse quantity for DragonLordsCrown


Failed to parse quantity for MoltenMoment


Failed to parse quantity for VayudaTurquoiseFragment


Failed to parse quantity for ShivadaJadeChunk


Failed to parse quantity for PrithivaTopazChunk


Failed to parse quantity for AgnidusAgateSliver


Failed to parse quantity for VarunadaLazuriteChunk


Failed to parse quantity for PhilosophiesOfDiligence


Failed to parse quantity for PhilosophiesOfGold


Failed to parse quantity for GuideToGold


Failed to parse quantity for NarukamisJoy


Failed to parse quantity for NorthlanderBowBillet


Failed to parse quantity for RustyKoi


Failed to parse quantity for BambooShoot


Failed to parse quantity for Almond


Failed to parse quantity for Fish

**Comment by Cupcak3** [comment]
Thank you for the screenshots and extra details. I will use them in testing to improve the accuracy of finding inventory items.

The failures to parse quantities is expected as that part of the scanner doesn't have high accuracy at the moment. We are working to improve that.

**Comment by Cupcak3** [comment]
Please check out the new [v1.2.2 release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.2). It improves finding inventory items as well as an update for the game's V2.5 inventory UI update.

Unfortunately the quantity parser is still not 100% accurate, but items being skipped should be fixed.
