### ISSUE TITLE
screen cropped at any given resolution

### ISSUE THREAD

**Issue by Blubbolo** [Andrewthe13th/Inventory_Kamera#211]
as the title, it doesnt matter what resolution i use on Genshin, every screen taken will be cropped like this
![weapon0](https://user-images.githubusercontent.com/99135175/152690318-ad66800b-e3e6-4653-a86f-8f67ee20e0a5.png)

**Comment by Cupcak3** [comment]
Please check out issue #40 if you have ultrawide capabilities.
