### ISSUE TITLE
[BUG] Incorrect display for number of artifacts scanned

### ISSUE THREAD

**Issue by briankchan** [Andrewthe13th/Inventory_Kamera#214]
After scanning artifacts, the display for scan progress in the bottom-left seems to get desynced.

E.g., after scanning 1504 artifacts:

- the counter displays "1493 / 1504"
- the JSON output has 1501 artifacts
- (there were 3 artifacts that errored out during scanning)

I've encountered this issue in both v1.2 and v1.2.1-prerelease.

**Comment by Cupcak3** [comment]
Did you have any artifacts remaining below the rarity threshold you had set? E.g Did you have any 3 star artifacts when your filter was set to 4 stars?

**Comment by briankchan** [comment]
No, the filter was set to scan all artifacts (1-5 stars).

**Comment by Cupcak3** [comment]
Fixed in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0)
