### ISSUE TITLE
My artifacts are not being scanned at all

### ISSUE THREAD

**Issue by therealsbeve** [Andrewthe13th/Inventory_Kamera#215]
Tried scanning my artifacts but it just skips them over after going to the artifact page and then just leaving the inventory page and going back to paimon menu.

Error message:
Insufficient items found in artifact inventory

   at InventoryKamera.ArtifactScraper.GetPageOfItems()

   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)

   at InventoryKamera.InventoryKamera.GatherData()

**Comment by therealsbeve** [comment]
> Happened to me too but I fixed it by moving the Genshin game folder to other drive. Make sure it's not on C drive.

What if I only have one drive? I'm on laptop.

**Comment by Cupcak3** [comment]
Please check out the [V1.2.2 release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.2). It has fixes that aim to eliminate the `Insufficient items found` error. Please let us know if it fixes your problem so that we may close this issue.

**Comment by therealsbeve** [comment]
> Please check out the [V1.2.2 release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.2). It has fixes that aim to eliminate the `Insufficient items found` error. Please let us know if it fixes your problem so that we may close this issue.

Yes this update was able to solve the problem. Thank you!
