### ISSUE TITLE
Update 2.5 Breaks Most Scanning

### ISSUE THREAD

**Issue by Cupcak3** [Andrewthe13th/Inventory_Kamera#219]
Hi Everyone. V2.5 adjusted some UI's a bit so Inventory Kamera will need fixes to adjust for these changes. Thankfully they don't seem too be crazy. We hope to get an update out ASAP.

You will likely see many many errors for basically everything. Any screenshots that Kamera generates will help ensure that our fixes work outside of testing but we have a general understanding of what needs to be done. You can upload those screenshots to this thread.

**Comment by Cupcak3** [comment]
Additional description:

Inventory tabs now display more items per "page" with this update. In previous versions there were (usually) about 4-5 rows and 7 columns used to display a full page of an inventory tab. Now there are 8 columns and about the same number of rows. As a result, the position of the information card on the right-hand side moved slightly. Inventory Kamera has relied on the position of the card to be more or less "fixed" (The card's height would be slightly longer in resolutions with a 16:10 aspect ratio). The shift may also require us to take a look at the positioning of important information (name, level, rarity, etc.) within the card once we capture it.

Here's a general comparison at 1280x720 resolution:

Old UI
![image](https://user-images.githubusercontent.com/8845977/154200164-d763c4ed-c97d-4f8b-a861-d039a4b0328e.png)

New UI
![image](https://user-images.githubusercontent.com/8845977/154200122-a4472607-d0f7-4afc-bdc9-f7cbfaa4380a.png)

**Comment by Mknyss** [comment]
Is this because 2.5 UI?

![image](https://user-images.githubusercontent.com/99862573/154416996-2bdb831d-95c3-4fae-94f3-9cb0ea13cd8d.png)

**Comment by Cupcak3** [comment]
@Mknyss probably. There's more error text in that box but it's cut off. The latest release should be working

**Comment by ACPixel** [comment]
Not sure if this is just me but in the recent 2.5 update the constellation screen UI *seems* to have changed a tiny bit, and the C6 click target isn't as wide as it used to be, and as such Kamera is missing the target and causing a failure. Tried on several different resolutions.

![click](https://up.pxl.ac/2022/pXmcs/Ej3AgzCA5F.jpg)

Offsetting the last click a bit to the left should work fine as a temp fix. Would love to make a PR but C# is not my language haha

**Comment by Cupcak3** [comment]
Interesting. I don't think the scanner stopped like that for my Mona. Do you mind sharing what resolution your game was in and if you were using V1.2.2 of Kamera?

**Comment by Cupcak3** [comment]
Do you happen to have an ultrawide monitor and/or had you changed from an ultrawide resolution to a standard resolution? I don't know about V2.5, but in previous versions of Genshin ultrawide adjusts the UI but that UI adjustment does not readjust when changing to a standard resolution without a restart.

**Comment by ACPixel** [comment]
That would be it! I'll keep that in mind thank you!
