### ISSUE TITLE
I keep getting "invalid artifact subs stats error" for multiple artifact

### ISSUE THREAD

**Issue by akhdanp1234** [Andrewthe13th/Inventory_Kamera#221]
I think this also happens in the 1.2.1 version which I first use. It successfully scanned most of my artifacts but there are around 20 or 30 error messages like this:

Unable to validate information for artifact ID#548

Invalid artifact sub stats

Artifact ID: 548

Set: ResolutionOfSojourner

Rarity: 3

Level: 0

Slot: circlet

Main Stat: def_

Substat 1: def + 10

Locked: False

This is the artifact:
![artifact548](https://user-images.githubusercontent.com/16409172/154596293-c5dfe2ed-28c9-4c01-8e90-0a9bc8d0a2fd.png)

**Comment by LiuAnshan** [comment]
Seeing similar things as well.  Seems to be my 3 star artifacts that have between +7 and +9 atk or def. I can post some examples and the log text if necessary.

**Comment by akhdanp1234** [comment]
> What resolution did you have your game in?

I forgot but I tried it again in 1600x900 and yeah it gives me the "invalid artifact subs stats" error. I just checked the log folder and there are 137 artifacts that have that error. All of them are 3-star artifacts.

**Comment by shallowbit** [comment]
I can also confirm this is happening to me with blue artifacts with flat atk or def stats between 7 and 9 with 1600x900. I have 91 "invalid substat" artifacts In the log folder. I have checked the card.png captures for all of them. 

I'd like to also note, for expedience sake, that the substat.png looks clear to me in each. Although, I don't know anything about it's tesseract requirements. 

When I have another moment I'll upload a log archive so someone can debug it further.

v1.2.6 client
v2.7.0 lookup

**Comment by Cupcak3** [comment]
Please check out any newer releases and let us know if this was resolved. If the issue still exists reopen this issue
