### ISSUE TITLE
no % for artefact

### ISSUE THREAD

**Issue by flover2102** [Andrewthe13th/Inventory_Kamera#229]
i have use scanner 1600x900 w/ 50 ms speed , 

scanner have 41 fail/621 

all def% , atk % and hp%  main change to def,hp and atk w/ out %

**Comment by flover2102** [comment]
work well when  screen is 1280x720

**Comment by Cupcak3** [comment]
Are you saying the main stat for artifacts were listed as their flat variants? This is not possible because we force DEF/ATK/HP to become the % variants when it comes to the main stat for an artifact.

**Comment by leandrolsf** [comment]
i have the same error here.
all "def_" artifacts are being written "def" instead.

take for instance this:

{"format":"GOOD","version":1,"kamera_version":"1.2.3","source":"Inventory_Kamera","artifacts":[{
    "setKey": "GladiatorsFinale",
    "slotKey": "sands",
    "rarity": 5,
    "mainStatKey": "def",
    "level": 20,
    "substats": [
      {
        "key": "critRate_",
        "value": 9.7
      },
      {
        "key": "enerRech_",
        "value": 6.5
      },
      {
        "key": "atk_",
        "value": 15.2
      },
      {
        "key": "hp_",
        "value": 4.1
      }
    ],
    "location": "",
    "lock": true,
    "SubStatsCount": 4,
    "Id": 91
  }
]}

**Comment by Cupcak3** [comment]
Please let us know if newer releases resolved this issue
