### ISSUE TITLE
Thinks refinement 3 weapons are refinement 13 for some reason

### ISSUE THREAD

**Issue by jamuwu** [Andrewthe13th/Inventory_Kamera#230]
The weapons that failed are all R3
```Unable to validate information for weapon ID#1


Invalid refinement level

Weapon ID: 1

Name: StaffOfHoma

Rarity: 5

Level 90

Refinement: 13

Locked: False

Equipped character: HuTao


Unable to validate information for weapon ID#7


Invalid refinement level

Weapon ID: 7

Name: PrimordialJadeWingedSpear

Rarity: 5

Level 80

Refinement: 13

Locked: False

Equipped character: Xiao


Unable to validate information for weapon ID#26


Invalid refinement level

Weapon ID: 26

Name: Whiteblind

Rarity: 4

Level 70

Refinement: 13

Locked: False

Equipped character: Noelle


Unable to validate information for weapon ID#30


Invalid refinement level

Weapon ID: 30

Name: SerpentSpine

Rarity: 4

Level 50+

Refinement: 13

Locked: False




Unable to validate information for weapon ID#43


Invalid refinement level

Weapon ID: 43

Name: FavoniusWarbow

Rarity: 4

Level 1

Refinement: 13

Locked: False

Equipped character: Amber


Unable to validate information for weapon ID#48


Invalid refinement level

Weapon ID: 48

Name: Akuoumaru

Rarity: 4

Level 1

Refinement: 13

Locked: False
```

**Comment by Cupcak3** [comment]
Please upload some of the generated screenshots from the logging folder. Also what resolution was the game at?

**Comment by jamuwu** [comment]
ah sorry, resolution was 1920 x 1080
<details>
<summary>screenshots</summary>

![weapon1](https://user-images.githubusercontent.com/14200370/155022145-34cdad57-08a6-4526-bebd-e9f9beae3fe6.png)
![weapon7](https://user-images.githubusercontent.com/14200370/155022156-69f677d1-baa4-4db9-87ae-7e45c0400f96.png)
![weapon26](https://user-images.githubusercontent.com/14200370/155022176-f337d7cf-cf78-446d-88a5-3badbb339a33.png)
</details>

**Comment by Cupcak3** [comment]
Alright, I'll see what can be done to improve the accuracy or default behavior. Does the same refinement problem exist at slightly lower resolutions?

**Comment by jamuwu** [comment]
I forgot to check, sorry. It only has an issue when at 1920 x 1080. Works as expected on every other [supported] resolution.

**Comment by jamuwu** [comment]
Never noticed there was a release after I made this issue, with that this is no longer happening for me
