### ISSUE TITLE
When importing artifacts to GO, there are some invalid artifacts

### ISSUE THREAD

**Issue by Cocolatte0403** [Andrewthe13th/Inventory_Kamera#231]
![image](https://user-images.githubusercontent.com/100179418/155056843-2ff5e484-4d8a-42f6-9541-2f75c60125ca.png)
I used Inventory Kamera to scan my artifacts for Genshin Optimiser but for some reason Genshin Optimiser said that there were invalid artifacts. I looked through the json file and for some reason Inventory Kamera scanned some artifacts under the "Tea" artifact set. Also, when I imported the json file to GO, some of my artifacts became 5* Gambler artifacts too.

**Comment by Cupcak3** [comment]
Looks like there was some weird data that shouldn't be where we're collecting our artifact set information from. It should be a simple filtering fix to make sure something like this doesn't happen in the future.

In the meantime, in the `artifacts.json` file under `inventorylists` try deleting the items below (basically delete everything that isn't a real artifact set) and let me know if the scan gets the artifact sets right. They're likely at the very bottom of the file, or very top if you used the auto updater to create a new file.
![image](https://user-images.githubusercontent.com/8845977/155104639-bb1ee239-e348-4ab5-bd1e-30bdb77f1e49.png)

**Comment by Cocolatte0403** [comment]
I did as you told and there are no more artifacts saved under weird names. However I think the scanner has been saving my Ocean Hued Clam artifacts under the scholar artifact set...

![image](https://user-images.githubusercontent.com/100179418/155129039-61ea1c1b-8d3a-4345-b3c2-2365578f4f65.png)

Also, I'm not sure if this is related but some of my artifacts have been removed from GO after I uploaded the latest json file that I scanned which presumably has the same artifacts as the previous json file I scanned today as I didn't do anything to my artifacts at all.

![image](https://user-images.githubusercontent.com/100179418/155129532-3a3b1c0f-68f7-4c18-8a85-fbd96152557b.png)

**Comment by Jolopundrio** [comment]
Same problem. 35 artifacts from GladiatorsFinale were scanned as Tea. If I delete the items in artifacs.json as suggested, there is no error but the artifacts affected vanished. I have also lost at least another artifact from BlizzardStrayer I detected it becasuse it is equipped for Ayaka and now Ayaka has only 4 artfifacts, not five. In this case is not renamed, it vanished. 
![imagen](https://user-images.githubusercontent.com/96955063/155287752-0738fa54-962d-429e-ab4b-19af277fd6cd.png)
