### ISSUE TITLE
Scanner scans Artifacts and Weapons below the Minimum Rarity set.

### ISSUE THREAD

**Issue by NottCurious** [Andrewthe13th/Inventory_Kamera#232]
The scanner scans Artifacts and Weapons that have a rarity below the Minimum that is set.

![image](https://user-images.githubusercontent.com/56356841/155105719-c57e4609-0f7c-43cd-89de-95bc72532432.png)

**Comment by Cupcak3** [comment]
What resolution was this happening at? I'll take a peek at it later today.

**Comment by NottCurious** [comment]
1920x1080

**Comment by Rilasis** [comment]
Same thing is happening to me. It's also giving errors for artifact rarity on artifacts that are fine:

Unable to validate information for artifact ID#1


Invalid artifact rarity

Artifact ID: 1

Set: EmblemOfSeveredFate

Rarity: 0

Level: 2

Slot: flower

Main Stat: hp

Substat 1: atk + 19

Substat 2: critDMG_ + 21.8%

Substat 3: critRate_ + 7.4%

Substat 4: def + 60

Locked: False

Equipped character: RaidenShogun

**Comment by NottCurious** [comment]
Fixed in latest release
