### ISSUE TITLE
Include artifact level as filter

### ISSUE THREAD

**Issue by 5arthak01** [Andrewthe13th/Inventory_Kamera#233]
[ENHANCEMENT]
Most people have a lot of potential 5-star artifacts at level 0 that are not useful for optimisers, and only a few are equipped on the characters. Hopefully, this should not be a challenge since the artifacts are given in descending levels, and we can include this as a subset for when the minimum artifact level is given 5. This would help us reduce the significant part of the time spent and the file space and be a huge convenience boost!

**Comment by ForAeons** [comment]
Please add this feature.

**Comment by Cupcak3** [comment]
This has been added in [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5)
