### ISSUE TITLE
[BUG] Unable to validate artifact information

### ISSUE THREAD

**Issue by ignaciocastro** [Andrewthe13th/Inventory_Kamera#236]
```
Unable to validate information for artifact ID#5
Invalid artifact set name
Artifact ID: 5
Set: 
Rarity: 4
Level: 9
Slot: plume
Main Stat: atk
Substat 1: hp + 239
Substat 2: def_ + 4.1%
Substat 3: def + 17
Substat 4: eleMas + 13
Locked: False
Equipped character: Zhongli

Failed to parse quantity for OintmentOfSight
Failed to parse quantity for ChaosGear
Failed to parse quantity for ConcealedUnguis
Failed to parse quantity for HurricaneSeed
Failed to parse quantity for HoarfrostCore
Failed to parse quantity for CleansingHeart
Failed to parse quantity for CrystallineBloom
Failed to parse quantity for AgnidusAgateFragment
Failed to parse quantity for VajradaAmethystChunk
Failed to parse quantity for VayudaTurquoiseFragment
Failed to parse quantity for PrithivaTopazFragment
Failed to parse quantity for GuideToLight
Failed to parse quantity for CrownOfInsight
Failed to parse quantity for AizenMedaka
Failed to parse quantity for BrownShirakodai
Failed to parse quantity for BitterPufferfish
Failed to parse quantity for Snapdragon
```
Using latest version of Inventory Kamera + Genshin in 1600x900 windowed
Screenshot of said artifact + some quantity errors

![artifact5](https://user-images.githubusercontent.com/7141944/155469227-355afe4b-9ebb-4978-bba9-ae94d7460aa3.png)
![Snapdragon_Quantity](https://user-images.githubusercontent.com/7141944/155469345-91c1845d-5ad7-43db-8245-4e77210ccaf9.png)
![AgnidusAgateFragment_Quantity](https://user-images.githubusercontent.com/7141944/155469346-5a21daab-b7a3-4c7c-9e17-c358861ab24f.png)
![BrownShirakodai_Quantity](https://user-images.githubusercontent.com/7141944/155469348-5b87d9a2-5e3b-4131-bc23-ad81e5115cfd.png)
![ChaosGear_Quantity](https://user-images.githubusercontent.com/7141944/155469351-3f09abd7-e364-4616-8f21-2593126234da.png)
![ConcealedUnguis_Quantity](https://user-images.githubusercontent.com/7141944/155469352-5af9b721-0941-4fc4-8105-11e5609366a2.png)

**Comment by Cupcak3** [comment]
Quantity parsing is unfortunately not that great yet so those errors are mostly reported for your convenience when you go to upload the file to Seelie.me or something.

As for the set name being blank, something was formatted differently from the database we pull our information from. This added bogus artifact sets to the `artifacts.json` list in the `inventorylists` folder. Please delete everything that isn't an artifact set from that file and let me know if the artifact set name is parsed correctly. They'll be easy to spot (Is "Tea" really an artifact set? lol)

**Comment by ignaciocastro** [comment]
Updated the artifacts.json file but still getting the same error.
```
Unable to validate information for artifact ID#5


Invalid artifact set name

Artifact ID: 5

Set: 

Rarity: 4

Level: 9

Slot: plume

Main Stat: atk

Substat 1: hp + 239

Substat 2: def_ + 4.1%

Substat 3: def + 17

Substat 4: eleMas + 13

Locked: False

Equipped character: Zhongli
```

**Comment by Cupcak3** [comment]
Recent versions should have this fixed. Feel free to reopen this issue if the problem persists.
