### ISSUE TITLE
Newest Release Ridiculously bugged

### ISSUE THREAD

**Issue by ghost** [Andrewthe13th/Inventory_Kamera#238]
Not only does it take well over a second PER ARTIFACT, it keeps throwing up errors. Keep in mind, this was terminated after the FOURTH artifact.
Did anyone think to test the latest release?

Unexpected error Parameter is not valid. for artifact ID#0

   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)

   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)

   at InventoryKamera.Scraper.ResizeImage(Image image, Int32 width, Int32 height)

   at InventoryKamera.Scraper.ScaleImage(Image image, Double factor)

   at InventoryKamera.ArtifactScraper.GetRarity(Bitmap bitmap, Double scale)

...
(deleted this middle section, but basically repeated the above error about 50 times)
...

   at InventoryKamera.ArtifactScraper.GetRarity(Bitmap bitmap, Double scale)

   at InventoryKamera.ArtifactScraper.QueueScan(Int32 id)

**Comment by Cupcak3** [comment]
I'm sorry that the new release is not working for you. In my testing I never encountered this error and I run full scans on all supported resolutions from 1280x720 to 1920x1080 before uploading a release. 

 The `Parameter is not valid.` error seems to be a vague and default error message being caught. However your log does tell me that something about the the rarity check is breaking. I will look into improving that area of code if I can't figure out exactly what's causing the problem.

As for the scanner taking longer to scan an artifact, scanning time increases as the size of images it has to scan increases. It's simply a given. Lowering resolution will speed up scan time for artifacts.

On a different note I would like to ask you to please be more cordial when reporting issues. We work on this project in our free time for ourselves and for the benefit of the community. We try to make it as stable and accurate as possible but problems are inevitable. Simple reports with the error and a discussion are much more constructive without snide comments.

**Comment by NightEmerald** [comment]
I am sorry for behaving rudely earlier, it takes a lot of time and effort to work on projects like these, and acting like this will not solve any issues.

On a separate note, in case it may help, here is video of the scanner (recording software only goes to 5 minutes) resolution was set to 1600x900 windowed.
https://youtu.be/2Nqhtclsz6g

Furthermore, attached is the entire error log of the scan, though the contents are primarily the same as those of the original post.
[ErrorLogKamera.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/8181568/ErrorLogKamera.txt)

Once again, I would like to apologize for my previous behavior, I should not have disrespected the sheer amount of work that the devs have put in.

**Comment by h2bro** [comment]
I was getting the same problem and errors. I believe Nvidia overlay + freestyle were causing the issue. I opened genshin, disabled overlay entirely, did another genshin restart and then opened InventoryKamera and ran a scan without the issues occurring.

**Comment by NottCurious** [comment]
Can confirm NVidia FreeStyle is somehow breaking the program. Switched my `Game Filters` to `Off` and everything works fine.

P.S: A restart for Genshin is not required. Just `Alt + F3` and change your profile to `Off`
