### ISSUE TITLE
Weapon data not show on GO

### ISSUE THREAD

**Issue by AzzinothKG** [Andrewthe13th/Inventory_Kamera#239]
I've scan all data in my account and upload to GO but I found weapon data missing. Plus some artifact detail missing
Is it bug from new version?

**Comment by Cupcak3** [comment]
Hi there, I know it's been a while since this issue was opened but (V1.2.5)[https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5] has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!
