### ISSUE TITLE
Not all artifacts are scanned

### ISSUE THREAD

**Issue by chronospectrum** [Andrewthe13th/Inventory_Kamera#24]
Version 0.8 works as expected.

Version 0.9 successfully scans all weapons and characters, but the artifact process seems to fail around row 11. At that point, row 13 scrolls from just below view at the bottom all the way up to the top visible row. The scanner then tries to scan rows 13-17 (basically all onscreen artifacts) before concluding the scanning process and moving on to characters (if enabled). This issue happens to me at all 3 delay levels.

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.

**Comment by chronospectrum** [comment]
Just for confirmation, release 1.1 and prerelease 1.1.1 both work as expected, so the issue was resolved somewhere.
