### ISSUE TITLE
[BUG] Artifact sets being incorrectly set

### ISSUE THREAD

**Issue by AugustusOctavian2** [Andrewthe13th/Inventory_Kamera#240]
Several artifacts scanned in as the wrong set, seemed to be especially gladiators finale pieces turning into gambler's dice set. I was using windowed 1280x720, when I changed to windowed 1600x900 that seemed to solve the problem. If the new recommended setting is 1600x900 and I missed it then my bad. Thanks for the great program!

**Comment by coworo** [comment]
Have the same issue, tried 1280x800 (now that i think of it its wrong ratio 😅) and 1920x1080. Both exhibited it. only thing that semi-reliably solves it is turning off anti-aliasing from genshin's graphics settings on 1920x1080. I now tried it with 1280x720 AA off and it still read it as gamblers.

**Comment by Cupcak3** [comment]
Image filtering and post-processing will probably mess with the scanner. Please disable any before running a scan.

**Comment by kazerniel** [comment]
Tried scanning with anti-aliasing off, in 1280x800 window (the largest 16:9 ratio my 1680x1050 screen can do).

<details>
  <summary>These pieces scanned as Gambler</summary>

![card](https://user-images.githubusercontent.com/5689996/182003579-476d08b2-8c7d-4aaf-8544-e8b667c2bd26.png)
![card](https://user-images.githubusercontent.com/5689996/182003602-231db28f-85ff-454f-bcb7-eecd44e82375.png)
![card](https://user-images.githubusercontent.com/5689996/182003614-4b28335a-2a52-43b2-8fe6-e077b973208a.png)
![card](https://user-images.githubusercontent.com/5689996/182003666-bd7f4352-b2f2-41fd-9fdb-f46b8ae07bc3.png)
![card](https://user-images.githubusercontent.com/5689996/182003818-304e3c05-7dd4-46ad-abab-e9f25a600ef0.png)

</details>

**Comment by Cupcak3** [comment]
Fixed in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0)
