### ISSUE TITLE
[Bug] Scanner endlessly cycling among characters

### ISSUE THREAD

**Issue by kazerniel** [Andrewthe13th/Inventory_Kamera#241]
First time that I got this bug, normally it stops after it scanned them all, but now it continued scanning characters it had already scanned.

Edit: It also scanned my Diluc as Diona. (There was a similar error a few weeks ago, where my Xingqiu got scanned as Xinyan.)

**Comment by Cupcak3** [comment]
I believe I've written fixes to avoid clicking through endlessly like this, please let me know if a newer release fixed this

**Comment by kazerniel** [comment]
> I believe I've written fixes to avoid clicking through endlessly like this, please let me know if a newer release fixed this

I haven't had this issue in months, so I guess a subsequent update did fix it 👍

**Comment by NoSoundAllEcho** [comment]
Bug appears to be back, I left it to scan while I made lunch and came back to it saying I had 200 characters lol

**Comment by NoSoundAllEcho** [comment]
It only seems to be happening on one of my accounts so it may be bc the Traveler is in my team? I'll try switching Lumine out
