### ISSUE TITLE
Update Lookup Tables doesn't work

### ISSUE THREAD

**Issue by nammerduong** [Andrewthe13th/Inventory_Kamera#252]
I keep getting an error every time I try to update the lookup tables.
![FgqV6Qz](https://user-images.githubusercontent.com/35582033/161381859-a20dbc60-7db7-4ea3-bc3a-c8a9a5ae4a1a.png)

**Comment by kwm1800** [comment]
I hasve same issue as well.

**Comment by Cupcak3** [comment]
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by nammerduong** [comment]
I just installed new version and pressed "update lookup tables". Doesn't seem fixed.
![vEPda5w](https://user-images.githubusercontent.com/35582033/168519690-e57bcd95-4365-4189-a724-c1941ab8bee2.png)

**Comment by nammerduong** [comment]
> Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

I just installed new version and pressed "update lookup tables". Doesn't seem fixed.
![vEPda5w](https://user-images.githubusercontent.com/35582033/168519921-62e8b770-4d49-4e88-bdbd-8d247c78d943.png)

**Comment by Cupcak3** [comment]
This issue should be resolved in V1.2.7. Please let us know if the issue persists
