### ISSUE TITLE
Scanner is missing the 2nd row of artefacts

### ISSUE THREAD

**Issue by Alician3141592** [Andrewthe13th/Inventory_Kamera#254]
Not sure how to explain it but the scanner is missing the 2nd row of artefacts when scanning. I attached a screenshot and also the json. I've tried 3 times and it's consistent everytime. Oddly this only happens with artefacts. I think this happened after the latest (Genshin) release.

Resolution is 2560 x 1440 (windows) but I run a genshin command to make it borderless but have done so before the release and it was fine.

![image](https://user-images.githubusercontent.com/103151806/162084135-6f971da1-6291-44fb-aaef-4922f67081f2.png)

**Comment by Alician3141592** [comment]
![ArtifactInventoryIncomplete](https://user-images.githubusercontent.com/103151806/162300100-4375d9f9-9077-4026-ab75-bb891a78a4c5.png)
![ArtifactInventory_8x4](https://user-images.githubusercontent.com/103151806/162300114-af76f8a7-a448-4817-8e36-4a1d762541dd.png)
oh the logging folder has something interesting

**Comment by Alician3141592** [comment]
btw if I force fullscreen scanner works so maybe it's something to do with the windowed mode.

**Comment by Cupcak3** [comment]
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!
