### ISSUE TITLE
Unable to validate information for artifact; Invalid artifact set name

### ISSUE THREAD

**Issue by lainverse** [Andrewthe13th/Inventory_Kamera#258]
Scanner failed to recognize set name for a couple of artifacts.
All from Wanderer's Troupe set.
Scanned in 1280x720 resolution windowed.

Details in attachment.
[artifacts.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8499812/artifacts.zip)

**Comment by IamCarbonMan** [comment]
Also having this issue. happens on various artifacts including VV, glad and maiden. Also 1280x720

**Comment by Cupcak3** [comment]
Duplicate of #240
