### ISSUE TITLE
Artifact scan

### ISSUE THREAD

**Issue by Shorsey** [Andrewthe13th/Inventory_Kamera#26]
I ran into the same issue reported by chronospectrum while scanning artifacts. In some cases it even stopped scanning after the first 3 or 4 artifacts.

It started working correctly after i reduced the amount of artifacts in my inventory from 811 to 786.

**Comment by Andrewthe13th** [comment]
Thanks for the feedback. Might need to revert something for my artifact scanner.

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
