### ISSUE TITLE
Unable to Parse Items

### ISSUE THREAD

**Issue by gkeylow** [Andrewthe13th/Inventory_Kamera#260]
Unable to parse mora count

Failed to parse quantity for HerosWit

Failed to parse quantity for AdventurersExperience

Failed to parse quantity for SlimeConcentrate

Failed to parse quantity for MistGrassWick

Failed to parse quantity for AgentsSacrificialKnife

Failed to parse quantity for ConcealedUnguis

Failed to parse quantity for DarkStatuette

Failed to parse quantity for MarionetteCore

Failed to parse quantity for LightningPrism

Failed to parse quantity for BloodjadeBranch

Failed to parse quantity for ShardOfAFoulLegacy

Failed to parse quantity for SpiritLocketOfBoreas

Failed to parse quantity for RingOfBoreas

Failed to parse quantity for TailOfBoreas

Failed to parse quantity for DvalinsSigh

Failed to parse quantity for DvalinsPlume

Failed to parse quantity for NorthlanderBowBillet

Failed to parse quantity for NorthlanderClaymoreBillet

Failed to parse quantity for FakeFlyBait

Failed to parse quantity for Medaka

Failed to parse quantity for Dawncatcher

Failed to parse quantity for Crystalfish

Failed to parse quantity for LungedStickleback

Failed to parse quantity for Betta

Failed to parse quantity for Snowstrider

Failed to parse quantity for PurpleShirakodai

Failed to parse quantity for AbidingAngelfish

Failed to parse quantity for RaimeiAngelfish

Failed to parse quantity for Pufferfish

Failed to parse quantity for BitterPufferfish

Failed to parse quantity for DivdaRay

Failed to parse quantity for FormaloRay

**Comment by Cupcak3** [comment]
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!
