### ISSUE TITLE
Can't launch the scan

### ISSUE THREAD

**Issue by MayAzuulaa** [Andrewthe13th/Inventory_Kamera#263]
Hello everyone,

I've already done scans in the past, successfully.
But now, when I click on the button, I have the erreor log :  à InventoryKamera.InventoryKamera.GatherData()

  à InventoryKamera.MainForm.<>c__DisplayClass1
![Capture d’écran 2022-04-23 125741](https://user-images.githubusercontent.com/104257240/164891709-f78745a0-7ed1-4cf7-94c7-81538e609b2e.png)
4_0.<StartButton_Clicked>b__0()

And the message in red "scan aborted"
How can I fix that ?
Thank you

**Comment by Cupcak3** [comment]
Hi there, that is only the end of the error code, there is more to that error in the window if you scroll. Alternatively you can post Kamera's logs to so that we can see what happened exactly.

**Comment by Cupcak3** [comment]
No information has been provided so I am closing this issue
