### ISSUE TITLE
Weapons and Artifacts Aren't Scanned

### ISSUE THREAD

**Issue by d5122001** [Andrewthe13th/Inventory_Kamera#265]
The scanner wasn't able to scan the weapons and artifacts inventory. It just goes to the weapons and artifacts categories and gives up. I have the latest scanner update.

**Comment by Cupcak3** [comment]
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!
