### ISSUE TITLE
Empty JSON File

### ISSUE THREAD

**Issue by Fxnarji** [Andrewthe13th/Inventory_Kamera#266]
Scanner seemingly successfully scans all artifacts, but only spits out an almost empty Jason file:

({"format":"GOOD","version":1,"kamera_version":"1.2.4","source":"Inventory_Kamera"})

**Comment by Cupcak3** [comment]
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by Fxnarji** [comment]
> Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

I tested it out again but couldnt get to the point where it finished scanning Artifacts, so it doesnt export anythint whatsoever :/

(I made a new Bug report on it, hope it helps ^^)
