### ISSUE TITLE
[BUG] Unable to validate information for artifacts

### ISSUE THREAD

**Issue by huang-jy** [Andrewthe13th/Inventory_Kamera#267]
There appears to be some problems parsing various stats. 

I am running version 1.2.4, with the game in a windows 1600x900 (16:9 Aspect)

Artifact parsing fails with "Unable to validate information", this happens with random artifacts, as if there's something it doesn't recognise. A few examples below (taken from the `logging` folder created by the app):

```
Unable to validate information for artifact ID#27


Invalid artifact sub stats

Artifact ID: 27

Slot: goblet

Set: ResolutionOfSojourner

Rarity: 3

Level: 1

Main Stat: electro_dmg_

Substat 2: enerRech_ + 3.1%

Locked: False

Equipped character: YunJin
```

![card](https://user-images.githubusercontent.com/2756283/167292941-38477ae5-ee5a-4992-9e86-d5693c52a169.png)

```
Unable to validate information for artifact ID#29


Invalid artifact sub stats

Artifact ID: 29

Slot: circlet

Set: PrayersForWisdom

Rarity: 3

Level: 0

Main Stat: atk_

Locked: False

Equipped character: KujouSara
```

![card](https://user-images.githubusercontent.com/2756283/167292957-329781df-73cb-4591-86d1-e8f0f3f416fa.png)

It seems like it is not recognising one or more of the substats correctly. For example, it only picked up "Substat 2" on the first one, but totally missed both substats on the second one.

---

For Materials, the app seems to fail to parse some of the quantities, but they seem clear enough. Some examples below (again, taken from the `logging` folder in the app):

`Failed to parse quantity for MistGrass`

![MistGrass_Quantity](https://user-images.githubusercontent.com/2756283/167293197-fcdf9618-3aa0-4349-aac8-4758cd6a1f34.png)

`Failed to parse quantity for AgentsSacrificialKnife`

![AgentsSacrificialKnife_Quantity](https://user-images.githubusercontent.com/2756283/167293203-da12540f-0480-47c9-b0e9-b10e816b194c.png)

`Failed to parse quantity for EverflameSeed`

![EverflameSeed_Quantity](https://user-images.githubusercontent.com/2756283/167293208-a04bf3da-4325-4d16-8bae-d9c0d94adc8f.png)

`Failed to parse quantity for BrilliantDiamondChunk`

![BrilliantDiamondChunk_Quantity](https://user-images.githubusercontent.com/2756283/167293216-930f7b3e-6034-4f59-81ed-aa300bf266c0.png)

**Comment by Phakes** [comment]
Also have the same error for some materials quantities. Running 1.2.4 with 1600x900 windowed.

Don't have any 3* or 4* artifacts so didn't scan it, but 5* seem to have no issue logged, only that it does not seem to finished them all.

![image](https://user-images.githubusercontent.com/31535183/167296272-75918a00-3e02-4fbc-acf2-107440bb7903.png)

Full log here

https://pastebin.com/0MqY6TFN

Examples.

`Failed to parse quantity for BasaltPillar`

![image](https://user-images.githubusercontent.com/31535183/167296367-ee3f522b-510e-4b64-a84c-511ac6a00394.png)

`Failed to parse quantity for GuideToDiligence`

![image](https://user-images.githubusercontent.com/31535183/167296717-fe9a0625-c086-4560-9a28-bc70bdbfcc58.png)

`Failed to parse quantity for NarukamisValor`

![image](https://user-images.githubusercontent.com/31535183/167296733-7b2deba0-89ab-4720-8d9c-2255b7f73578.png)

`Failed to parse quantity for BitterPufferfish`

![image](https://user-images.githubusercontent.com/31535183/167296660-9b1ae8a0-c77e-416b-baf2-162df61a84fb.png)

`Failed to parse quantity for NorthlanderPolearmBillet`

![image](https://user-images.githubusercontent.com/31535183/167296763-de36ca22-8a45-49e9-b3bb-9d8257b5e899.png)

**Comment by Cupcak3** [comment]
Hi there, [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by huang-jy** [comment]
Unfortunately, it did not fix the issue. Worse, the application exits abnormally during scanning of the artifacts with the following in the `logging` folder:

```
2022-05-16 20:41:01.447|INFO|UserInterface|Parsed 452 artifacts to scan
2022-05-16 20:41:05.946|ERROR|UserInterface|Unable to validate information for artifact ID#19
2022-05-16 20:41:05.946|ERROR|UserInterface|Invalid artifact sub stats
Artifact ID: 19
Slot: flower
Set: TravelingDoctor
Rarity: 3
Level: 12
Main Stat: hp
Substat 1: critDMG_ + 3.3%
Substat 3: hp_ + 3.5%
Substat 4: critRate_ + 3.5%
Locked: True
```

Since it seems to have crashed out, there's nothing logged. Switching on "Log all screenshots" does add all the screenshots, but in the above run, there's no `artifact19` folder.

Also, I noticed the box sizes for the artifact captures seem a bit off -- are they supposed to cover the entire artifact box?

![ArtifactInventory_8x5](https://user-images.githubusercontent.com/2756283/168670628-a657d255-7466-4aa1-9134-0f768ed0138a.png)

**Comment by huang-jy** [comment]
v1.2.6 still has the issue.

**Comment by Tetranor89** [comment]
v1.2.7 still has the issue.

**Comment by Cupcak3** [comment]
This thread has a duplicate description of #96 
The issue about artifact information not being validated exists for low rarity has an equally low priority of being addressed.

**Comment by Cupcak3** [comment]
Recent versions have improved material quantity scanning. If you are still having invalid artifact errors please create a new issue.
