### ISSUE TITLE
Scanner never makes it past 1st weapon or artifact

### ISSUE THREAD

**Issue by kyanscienceman** [Andrewthe13th/Inventory_Kamera#269]
Character scanning works just fine. When trying to scan weapons or artifacts, scanner gets up to the part where it clicks on the first weapon/artifact, then immediately finishes. Resulting JSON file is empty except for the header. Replicated with 2 different resolutions, and with different minimum weapon/artifact rarities. 

Most likely a duplicate of issue #265.

1. Resolution: Tried for both 1600x900 and 1280x720
2. Inventory Kamera version: v1.2.4
3. Genshin Impact version: 2.6
4. Logs
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8666594/InventoryKamera.log)

**Comment by Cupcak3** [comment]
Hi there, [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by kyanscienceman** [comment]
Hi, thanks a bunch for putting out the 1.2.5 update. Unfortunately the bug hasn't been resolved, but the behavior has changed slightly. 
- The scanner still never gets past the first weapon
- The scanner now clicks on 2 artifacts before closing out of the artifacts screen
- There is now an error message in the logs:
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8704418/InventoryKamera.log)
- The resulting JSON file is still empty besides the header

**Comment by MacMJ3** [comment]
I am also receiving the same error.

1. Resolutions tried: 1920×1080 and 1280×720
2. Inventory Kamera v1.2.5
3. Genshin Impact v2.6
4. Logs
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8709429/InventoryKamera.log)

**Comment by TLD99** [comment]
Same issue (albeit not the same, similar vein), I've tried 1.2.5 with different resolutions but couldn't get to scan the artifacts I've got. Log attached
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8713530/InventoryKamera.log)

**Comment by Cupcak3** [comment]
Thanks for the logs everyone. I've found the issue and hopefully can get a fix out soon.

**Comment by kyanscienceman** [comment]
Hey @Cupcak3 thanks for putting out version 1.2.6, I just downloaded it today and tried it out - no longer having this issue! Appreciate your hard work on the bugfixing.
