### ISSUE TITLE
Feature Request: Add option to ignore equipped state

### ISSUE THREAD

**Issue by huang-jy** [Andrewthe13th/Inventory_Kamera#270]
I would like a feature where an item is not marked as equipped.

Simple reason being is when I import the GOOD file into something Genshin Optimizer I want to be able to build a team's equipment from scratch, with nothing equipped yet.

Right now, I'm using Notepad++ to regex the json and replace `"location": "{character}"` to `"location": ""` -- now this works, but it's pretty much a hack.

**Comment by Cupcak3** [comment]
Hi there, this has been added in [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5).
