### ISSUE TITLE
Mention that you need to have Inventory keybind set to "B"

### ISSUE THREAD

**Issue by hyoretsu** [Andrewthe13th/Inventory_Kamera#272]
Title's self-explanatory, didn't work for me at first. That or open inventory by clicking on the icon, which I guess should be harder.

**Comment by Cupcak3** [comment]
Hi there, this step is outlined in [the readme](https://github.com/Andrewthe13th/Inventory_Kamera#readme) for the project.

**Comment by hyoretsu** [comment]
This README's way more specified than the instructions in the program though, not everyone will read the GitHub one.
