### ISSUE TITLE
[FEATURE] Add saving for Inventory Key hotkey

### ISSUE THREAD

**Issue by b4lesh** [Andrewthe13th/Inventory_Kamera#278]
I don't now is it bug or no. I want to be able to save Inventory Key hotkey. Because my inventory opens on **I** key, but after closing the app I always should change hotkey from **B** to **I**. It will be more comfortable for users, thanks (´｡• ᵕ •｡`)

**Comment by Cupcak3** [comment]
Thanks for bringing this to my attention. I just forgot the two lines of code to save these two settings in particular because I handle them differently. Hopefully I can get a fix for this out soon.

**Comment by b4lesh** [comment]
Thank you for updating
