### ISSUE TITLE
Stops when it hits a level-read error

### ISSUE THREAD

**Issue by Majik0327** [Andrewthe13th/Inventory_Kamera#280]
I ran it on my characters and it picked up everything correctly until it was "Unable to determine level for Noelle" -- after that, it stopped scanning, and didn't scan the rest of my characters.

Perhaps as an alternative, if it can't determine someone's level, set it to some value or skip them (since it says it in the logs, it wouldn't be a big deal to enter that one character manually) and then continue scanning the rest of the characters. The way it is now, I have to manually enter all of my characters that come after Noelle.

**Comment by Cupcak3** [comment]
I can look into a fix for this. Thanks for the suggestion.

**Comment by Cupcak3** [comment]
Fixed in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0). Scanner instead sets character level to 1 if it can't figure out the level.

**Comment by Julienraptor01** [comment]
> Fixed in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0). Scanner instead sets character level to 1 if it can't figure out the level.

There is a possibility of a fix, when character level can't be determined with screenshot then it should set the minimum required level based of the highest normalized talent (aka by not forgeting that tartaglia and constellations change talent level)
