### ISSUE TITLE
Skipping Artifacts + Weapons

### ISSUE THREAD

**Issue by EddieMaiale** [Andrewthe13th/Inventory_Kamera#281]
I'm not sure if I am doing something wrong, but I have 8 columns per row of items, however, the program appears to be skipping the first column entirely, and skipping items every so often on each of the artifacts. 

I've tried using different resolutions, but I am using a standard 1440p monitor at 16:9 aspect ratio. Each option still skips the first column, but my biggest problem is that it's randomly skipping artifacts. If there is something else I can test, please let me know.

**Comment by Cupcak3** [comment]
Hmm. Please upload a screenshot generated by Kamera from the `\logging\artifacts` and `\logging\weapons` folders. They should be called "WeaponInventory_7x4.png" or something similar, same for the artifacts. If those screenshots don't exist, enable screenshot logging option and let the scan click through an artifact/weapon or two so it doesn't save too many images.

**Comment by EddieMaiale** [comment]
> Hmm. Please upload a screenshot generated by Kamera from the `\logging\artifacts` and `\logging\weapons` folders. They should be called "WeaponInventory_7x4.png" or something similar, same for the artifacts. If those screenshots don't exist, enable screenshot logging option and let the scan click through an artifact/weapon or two so it doesn't save too many images.

So when I went through again today, for some reason it decided to capture the first column. I still noticed some skips here and there, but it appears to have been okay. 

When I looked through the logging folders I did not see anything, however I also don't see an option to enable screenshot logging.

**Comment by EddieMaiale** [comment]
> 

Well, that would be why I couldn't see it. I have version 1.2.4. Not sure how I got that version, but I'll correct that mistake now. Who knows, it might resolve my issue completely.

**Comment by EddieMaiale** [comment]
Skipping is relatively good compared to 1.2.4, however, my scan crashes after getting to the 4 star artifacts. I will create a new issue for that and close this one. Thank you for your help!
