### ISSUE TITLE
Phamtom Ganyu [BUG] 

### ISSUE THREAD

**Issue by AsHalt** [Andrewthe13th/Inventory_Kamera#285]
> Instruction: Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?
Please describe what seems to be an issue.

extra entry of ganyu when User didn't have one during any _wishes_ 

## How to reproduce this issue
Please describe how can WE reproduce the issue.
1. ... I do this ...
2. ... and this ...
3. ... and that ...
4. ... so I experienced this ...
Just run the tool in an account without ganyu

We appreciates describing your issue with pictures and screen recording. If you have any, please attatch it here (by drag and dropping)

## What seems to cause this issue?
Please create a resonable guess on what might cause this issue.
Coding, or AI error

## Expected behavior
Please describe what you expect from Inventory Kamera or output files:
No additional character (ganyu) not in inventory

## Info about your device
- Device Operating System : W10 Home 21H2 19044.1706 Windows Feature Experience Pack 120.2212.4170.0
- Genshin Impact Version : 2.6
- Inventory Kamera Version : 1.2.5
- Screen resolution(s) affected : estimated all, (tested) 1680x1050 , 1280x720

## Additional Notes / Remarks
Add any other context about the problem and log files/report here.<br>
If you managed to find any related or similar issue, please paste a link here.
[genshinData_GOOD_2022_05_19_23_52.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/8732092/genshinData_GOOD_2022_05_19_23_52.txt)
[genshinData_GOOD_2022_05_20_00_10.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/8732093/genshinData_GOOD_2022_05_20_00_10.txt)

## Checklist before sending issue
Here's everything you should try before sending this issue. Make sure that you have completed it accordingly.

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
> Instruction: If your issue does not relate to scanning issue, feel free to delete any unrelated checklist.
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that will explain what caused the issue.

**Comment by Cupcak3** [comment]
Weird, not sure why it managed to scan characters multiple times. I'll add something to prevent this sort of issue at all.

**Comment by AsHalt** [comment]
It's not a duplicate, more of an "extra" character.

Unless that's what's happening on backend. (Code idiot)

**Comment by Cupcak3** [comment]
Newer versions should resolve this kind of problem. Please let me know if you encounter it again.
