### ISSUE TITLE
[BUG] The scanner stops scanning and turns itself off when scanning the artifact.

### ISSUE THREAD

**Issue by Astra3usZ** [Andrewthe13th/Inventory_Kamera#286]
> Instruction: Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?
Please describe what seems to be an issue.
- The scanner stops scanning and turns itself off when scanning the artifact.

## How to reproduce this issue
Please describe how can WE reproduce the issue.
1. Open the scanner normally.
2. Have the scanner scan for artifacts. (adding other options still get the same result)
3. Let the scanner scan it.
4. The scanner reports in the error log will say "Locked: false" before shutdown itself.

We appreciates describing your issue with pictures and screen recording. If you have any, please attatch it here (by drag and dropping)

## What seems to cause this issue?
Please create a resonable guess on what might cause this issue.
- According to the logging, it scans up to artifact 133 before it stops. So I guess the problem might be there (see attachment).
- ![card](https://user-images.githubusercontent.com/103481808/169353910-4efebb35-e8b5-400c-aa91-8b27585f53fa.png)

## Expected behavior
Please describe what you expect from Inventory Kamera or output files:
- Provides a regular scan report.

## Info about your device
- Device Operating System: Windows 10
- Genshin Impact Version: 2.6
- Inventory Kamera Version: 1.2.5
- Screen resolution(s) affected : 1280x720

## Additional Notes / Remarks
Add any other context about the problem and log files/report here.<br>
If you managed to find any related or similar issue, please paste a link here.
- The resolution of 1680x1050 and 1600x900 works fine without causing any errors.
- Maybe the problem is with the resolution?

## Checklist before sending issue
Here's everything you should try before sending this issue. Make sure that you have completed it accordingly.

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
> Instruction: If your issue does not relate to scanning issue, feel free to delete any unrelated checklist.
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that will explain what caused the issue.

**Comment by kazerniel** [comment]
I had this happen to me too, twice in a row.

I set Kamera to scan weapons, artifacts and characters.

<details>
<summary>End of 1st scan log + image</summary>

```
2022-05-19 21:34:48.007|INFO|InventoryKamera|Scanning artifacts...
2022-05-19 21:34:55.900|INFO|UserInterface|Parsed 1018 artifacts to scan
2022-05-19 21:35:10.408|ERROR|UserInterface|Unable to validate information for artifact ID#59
2022-05-19 21:35:10.408|ERROR|UserInterface|Invalid artifact sub stats
Artifact ID: 59
Slot: circlet
Set: HuskOfOpulentDreams
Rarity: 4
Level: 0
Main Stat: def_
Substat 1: atk + 16
Locked: False
```

![image](https://user-images.githubusercontent.com/5689996/169402165-e7553581-7ce3-486b-be28-1f36bd26843d.png)
</details>


<details>
<summary>End of 2nd scan log + image</summary>

```
2022-05-19 21:36:55.956|INFO|InventoryKamera|Scanning artifacts...
2022-05-19 21:37:03.767|INFO|UserInterface|Parsed 1018 artifacts to scan
2022-05-19 21:38:23.715|ERROR|UserInterface|Unable to validate information for artifact ID#332
2022-05-19 21:38:23.715|ERROR|UserInterface|Invalid artifact sub stats
Artifact ID: 332
Slot: flower
Set: TravelingDoctor
Rarity: 3
Level: 0
Main Stat: hp
Locked: False
```
![image](https://user-images.githubusercontent.com/5689996/169402823-79e24fae-cc21-456d-9e26-598c8be18bfa.png)

</details>

(Took manual screenshots bc couldn't find the ones the app took.)

## Info about your device

* Device Operating System: Windows 10

* Genshin Impact Version: 2.6

* Inventory Kamera Version: 1.2.5

* Screen resolution(s) affected : 1280x800

## Checklist before sending issue

* [x]  I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
* [x]  I have correctly set my character and inventory keys in Inventory Kamera
* [x]  I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

## Additional checklist for Scanning issues
* [x]  I tried setting the delay to maximum and still experiencing issues.

**Comment by Cupcak3** [comment]
The images provided are not the same images generated by the application. Please try enabling the 'Log All Screenshots' button, zipping, and uploading the last artifact folder the application generates found in `logging\artifacts`

**Comment by Astra3usZ** [comment]
Since 1.2.6 the artifact scanner works fine for me so I decided to turn this issue off.
