### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by newnyansan** [Andrewthe13th/Inventory_Kamera#289]
> Instruction: Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?
Please describe what seems to be an issue.
1)I am trying to use InventoryKamera to scan everything , weapons artifacts materials etc and at the moment it encounters pieces of Echoes  of an Offering set it immediately crashes 
2) i am using the scanned file for the characters and weapons to import on genshin optimiser but for some reason genshin optimiser thinks that the scanned ayato is ayaka , so i have ayato in the heroes i own but on the site it shows me ayaka

## How to reproduce this issue
Please describe how can WE reproduce the issue.
1. ... I do this ...
2. ... and this ...
3. ... and that ...
4. ... so I experienced this ...

We appreciates describing your issue with pictures and screen recording. If you have any, please attatch it here (by drag and dropping)

## What seems to cause this issue?
Please create a resonable guess on what might cause this issue.

## Expected behavior
Please describe what you expect from Inventory Kamera or output files:

## Info about your device
- Device Operating System : windows 10
- Genshin Impact Version : latest
- Inventory Kamera Version : 2.5 and 2.3
- Screen resolution(s) affected : 1280x(either 720 or the 800)

## Additional Notes / Remarks
Add any other context about the problem and log files/report here.<br>
If you managed to find any related or similar issue, please paste a link here.

## Checklist before sending issue
Here's everything you should try before sending this issue. Make sure that you have completed it accordingly.

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [ ] I have checked Issue page and there is **none** that is related to mine.
- [ ] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [ ] I have filled in "Info about your device" section.
- [ ] I have correctly set my character and inventory keys in Inventory Kamera
- [ ] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
> Instruction: If your issue does not relate to scanning issue, feel free to delete any unrelated checklist.
- [ ] I tried setting the delay to maximum and still experiencing issues.
- [ ] I have attached media and log files that will explain what caused the issue.

**Comment by Cupcak3** [comment]
Please upload your logs so that we can help with the crashing.

As for ayato being misread as ayaka, please make sure Ayato can be found in the `characters.json` file found under `inventorylists`. If he is not there then your lists are out of date. The V1.2.5 upload should have up-to-date information in it already.

**Comment by newnyansan** [comment]
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8759848/InventoryKamera.log)
[InventoryKamera.20220516054851.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8759849/InventoryKamera.20220516054851.log)
[InventoryKamera.20220521092822.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8759850/InventoryKamera.20220521092822.log)
[InventoryKamera.20220521093105.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8759851/InventoryKamera.20220521093105.log)
[InventoryKamera.20220521093353.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8759852/InventoryKamera.20220521093353.log)
I hope those are the ones you needed .

**Comment by Cupcak3** [comment]
New releases should have the fixes for this issue. Please let us know if it persists
