### ISSUE TITLE
[BUG] Scanning stops early and doesn't exit artifact scanning

### ISSUE THREAD

**Issue by EddieMaiale** [Andrewthe13th/Inventory_Kamera#291]
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?
I tried running the scan about 5-6 times with different scanner delay settings but if I try to set the program to scan 4 star artifacts, the program will crash after getting through approximately 20-30 4 star artifacts. I verified this by selecting only 5 star artifacts and it went through successfully, no errors. 

## How to reproduce this issue
Select 4 star and up on the artifacts section, then try scanning. I have attached a video of this here: 

https://user-images.githubusercontent.com/26036944/170142366-a8e45420-b1cd-49bd-abad-576da1bed088.mp4

## What seems to cause this issue?
I suppose it could be too many artifacts. Off the top of my head, that's about all I can think of. 

## Expected behavior
I just expect it to get past the artifacts section and export the artifacts. When I was using 1.2.4 I didn't run into this issue, it just skipped too many artifacts. I still think it's skipping artifacts/gear in this one, but not nearly as much. Perhaps you could tell if it's skipping? My eyes could be playing tricks on me.

## Info about your device
- Device Operating System : Win 10 Pro
- Genshin Impact Version : 2.6
- Inventory Kamera Version : 1.2.5
- Screen resolution(s) affected : 2560 x 1440

## Additional Notes / Remarks
Video attached

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that Inventory Kamera generates.

**Comment by Cupcak3** [comment]
There's a few things that could be happening and your comments touch on a few areas;
1. It does seem like it's stopping short, however from your video alone I cannot tell if the application is hard crashing or if just the scan crashes. If the application is hard crashing then you would have gotten a popup saying as much. If the scan is crashing then it at least means we caught something right. In either case there's a log file generated under `logging` which I will need to be able to debug further. If there are artifacts under `logging\artifacts` zipping those up and providing them would be helpful. Zipping up the entire logging folder also works.
2. You mentioned it skipping items, however I don't see that happening here. I do see it scrolling to a new page of artifacts to click through without finishing the last line of items on the previous page. This isn't ideal but that last line of artifacts are at least the first line of items after a page scroll which means they're not being entirely skipped. V1.2.6 has a bit of an update to this so while it may be slightly slower, it *should* at least be more accurate at scrolling.

**Comment by Cupcak3** [comment]
V1.2.7 I think fixes the last row not getting scanned and lookup table update failures. There was background logic that wasn't keeping track of the number of artifacts left correctly which could have lead to this. Let me know if that issue was resolved with the update

**Comment by Cupcak3** [comment]
There has been no further feedback on this in a while so I am closing the issue. Feel free to reopen if the issue persists
