### ISSUE TITLE
Confused on running the application [QUESTION] 

### ISSUE THREAD

**Issue by jet419** [Andrewthe13th/Inventory_Kamera#292]
How are you supposed to run the application with the Paimon menu open when Genshin minimizes itself whenever you click anywhere outside of the game? I can't run borderless windowed mode either because my display settings are not supported in that mode. Only fullscreen resolution supported. Please help!

**Comment by Cupcak3** [comment]
If the game minimizes itself then that means the application isn't running in some sort of windowed or borderless fullscreen mode. If you cannot run in a windowed resolution then you can run the game's application directly with the following:

1. Locate GenshinImpact.exe wherever you installed the game. It'll be something like `<path>/Genshin Impact/Genshin Impact Game/GenshinImpact.exe`
2. Right click the application file and create a shortcut
3. Right click the shortcut and select properties
4. Add `-popupwindow` to the target. Mine looks like this: `"E:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact.exe" -popupwindow`
5. Now you can run the game directly and in a borderless windowed mode. With the game focused, you can press alt+enter to toggle between true fullscreen and the borderless window.

You can tell which mode it is in if the game disappears when you click out of the game. If it disappears then it is in true fullscreen. If it doesn't disappear then you're in borderless window. If you want to use this Inventory Kamera you'll want to be in borderless window.
