### ISSUE TITLE
[BUG] Weapon scanning stops after scrolling to second page at 1680x1050

### ISSUE THREAD

**Issue by doxxx** [Andrewthe13th/Inventory_Kamera#295]
## What happed? What is seems to be a bug?
Weapon scanning scans the first page, scrolls to second page and then stops without scanning any more weapons even though they meet the rarity and level criteria.

## How to reproduce this issue
1. Ensure that you have enough weapons to cover two pages at a resolution with an aspect ratio of 1.6, e.g. 1920x1200 or 1680x1050, etc.
2. Select Weapons in IK and set minimum weapon rarity and level such that weapons on page 2 would be scanned. 
3. Start scanning.

## What seems to cause this issue?
There's an error message in the log:

```
Insufficient items found in weapon inventory
   at InventoryKamera.WeaponScraper.ProcessScreenshot(Bitmap screenshot)
   at InventoryKamera.WeaponScraper.GetPageOfItems(Int32 page)
   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count)
   at InventoryKamera.InventoryKamera.GatherData()
```

## Expected behavior
All weapons are scanned based on filters.

## Info about your device
- Device Operating System : Windows 10
- Genshin Impact Version : 2.6
- Inventory Kamera Version : 1.2.6
- Screen resolution(s) affected : 1920 x 1200 or 1680x1050
- Native screen resolution: 2560x1440 (1.77 ratio)

## Additional Notes / Remarks
If I switch the resolution to 1920x1080, the problem no longer occurs.
Delay was set to "Slower".

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that Inventory Kamera generates.

**Comment by Cupcak3** [comment]
This kind of error will generate screenshots under `logging\weapons` and `logging\artifacts` respectively. Please upload those.

**Comment by doxxx** [comment]
For a weapon scan which fails, it only produced one screenshot in the `logging\weapons` folder. I've attached that and the corresponding log files.

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8828813/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8828811/InventoryKamera.log)
![WeaponInventory](https://user-images.githubusercontent.com/677940/171767554-d21fbf0b-780e-4342-bd77-118ac0780c35.png)

**Comment by backerman** [comment]
Same deal on my machine (XPS 17 9700, 3840x2400 display, Genshin Impact 2.7 running in windowed mode at 2560x1600) with master 42d69c457f7dd07e4bcd6a111b7bb46e54e9e351.

**Comment by Cupcak3** [comment]
V1.2.7 should have some fixes aimed towards insufficient items in inventory. Let me know if that version fixes the issue

**Comment by Cupcak3** [comment]
I am closing this issue for no response. Feel free to reopen this issue.
