### ISSUE TITLE
[BUG] Unable to obtain inventorylists for new version

### ISSUE THREAD

**Issue by Maelstrom-Portal** [Andrewthe13th/Inventory_Kamera#298]
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?

Unable to obtain inventorylists for new version due to:
1. "Game Version Update" shows "Could not check for updates" after a long pause.
2. "Update Lookup Tables" throws Newtonsoft.Json.JsonReaderException after a long pause.

## How to reproduce this issue

1. On "Game Version Update" popup, click "Yes".
2. Click "Update Lookup Tables"
## What seems to cause this issue?

Newtonsoft.Json.JsonReaderException

## Expected behavior

Obtain inventorylists successfully for new version of Inventory Kamera

## Info about your device
- Device Operating System : Windows 10 Professional 64 bits
- Genshin Impact Version : N/A
- Inventory Kamera Version : V1.2.6
- Screen resolution(s) affected : N/A

## Additional Notes / Remarks

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8802101/InventoryKamera.debug.log)
Similar issue?: https://github.com/Andrewthe13th/Inventory_Kamera/issues/120

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [ ] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [ ] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that Inventory Kamera generates.

**Comment by emerua** [comment]
I have encountered the same issue.
I'm Japanese and I'm not good at English, so I'm sorry if the sentences are wrong.

Probably because the UTF8 encoding was not specified when reading the textMap json.
I've checked it in my local environment and it seems that the following fixes work, but I'm not confident.
I hope this info helps contributors.

add `client.Encoding = System.Text.Encoding.UTF8;` to LoadJsonFromURLAsync

```cs
		private string LoadJsonFromURLAsync(string url)
		{
			string json = "";
			using (WebClient client = new WebClient())
			{
				client.Encoding = System.Text.Encoding.UTF8;
				json = client.DownloadString(url);
			}
			return json;
		}
```

**Comment by Cupcak3** [comment]
@emerua Thanks for looking at this. It does seem at least related and doesn't break anything for me so I'll add it in.

**Comment by JirgCode** [comment]
Which file do you add it in, i couldnt find a file called "textmap.json', i only found Newtonsoft.Json.xml and Newtonsoft.Json.dll.

Newtonsoft.json.xml didnt have that line in it and i cant open new Newtonsoft,.Json.dll without it showing a bunch of random symbols

**Comment by JirgCode** [comment]
Changing my computers unicode language from japanese->english fixed the error for me

**Comment by Maelstrom-Portal** [comment]
> Changing my computers unicode language from japanese->english fixed the error for me

For windows users, follow this guide: https://www.java.com/en/download/help/locale.html

However, instead of selecting the desired language in step 5, check the box of "Beta: Use Unicode UTF-8 for worldwide language support" and you are good to go.
