### ISSUE TITLE
[BUG] Gladiator's set seems to be mistaken as the Gambler's set

### ISSUE THREAD

**Issue by seriaati** [Andrewthe13th/Inventory_Kamera#300]

**Comment by MysticHqra** [comment]
seconded, this has been happening since v1.2.3

**Comment by Cupcak3** [comment]
This has been reported to me. Please enable the screenshot logging option and let the scanner scan at least a few gladiator artifacts. After you see a couple show up on the application's window you may interrupt the scan by pressing Enter.

After, I will need you to locate those artifacts under `logging\artifacts`. There should be numerous folders labeled `artifact` followed by a number. Please try and find the folders that correspond to gladiator artifacts, zip them all together, and submit them here.

**Comment by seriaati** [comment]
[New folder.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8840181/New.folder.zip)
