### ISSUE TITLE
Error while scanning

### ISSUE THREAD

**Issue by upy003** [Andrewthe13th/Inventory_Kamera#305]
This error occurred while scanning:

Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.

Parametername: index

   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)

   bei InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)

   bei InventoryKamera.InventoryKamera.GatherData()

**Comment by Cupcak3** [comment]
Hi there, sorry for the very late reply. However your description is not descriptive enough to help us figure out what's going on. Please reopen this issue after submitting the application's crash logs.
