### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AuroraStarlin** [Andrewthe13th/Inventory_Kamera#307]
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?
 My scan keeps getting aborted bcs of a mistake i dont know how to solve
 "InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)"

## How to reproduce this issue
 No Idea

## What seems to cause this issue?
 No idea

## Expected behavior
 To san normally...

## Info about your device
- Device Operating System : Windows 10
- Genshin Impact Version : 2.7
- Inventory Kamera Version : 1.2.6V
- Screen resolution(s) affected : 1280x720

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [x] I tried setting the delay to maximum and still experiencing issues.
- [ ] I have attached media and log files that Inventory Kamera generates.

**Comment by Cupcak3** [comment]
Hi there, sorry for the late reply. However your report is not descriptive enough to help us begin to figure out what's going on. Please reopen this issue after submitting the application's crash logs.
