### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by freshrock222** [Andrewthe13th/Inventory_Kamera#308]
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

## Info about your device
- Device Operating System :
- Genshin Impact Version :
- Inventory Kamera Version :
- Screen resolution(s) affected :

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [ ] I have checked Issue page and there is **none** that is related to mine.
- [ ] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [ ] I have filled in "Info about your device" section.
- [ ] I have correctly set my character and inventory keys in Inventory Kamera
- [ ] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [ ] I tried setting the delay to maximum and still experiencing issues.
- [ ] I have attached media and log files that Inventory Kamera generates.
![image_2022-06-10_232314872](https://user-images.githubusercontent.com/71994740/173170692-7d033561-33f3-4e26-98fb-f03fe2f4cbe2.png)

**Comment by Cupcak3** [comment]
Sorry for the late reply. However your report is not very descriptive and you have not done any of the checklist items (the last one will be most helpful). Please reopen this issue after you have filled out the report with more information and/or submit the crash logs.
