### ISSUE TITLE
issue in scanning artifacts

### ISSUE THREAD

**Issue by Pix77** [Andrewthe13th/Inventory_Kamera#31]
I kept getting "Error: aanemodmgbonus is not a valid Main Stat Name"
I have 563 artifacts during the scans, but in 508th the program stops and closes
Tried it in 3 different Scanner Delays. Still has errors.
Not sure if there's something else I need to do before scanning for it to work properly

The Weapon and Character scans worked.

**Comment by Cupcak3** [comment]
This is a very old issue and has been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
