### ISSUE TITLE
[BUG] Scanning characters as C6 when they are not

### ISSUE THREAD

**Issue by heathermacgregor** [Andrewthe13th/Inventory_Kamera#311]
> **NOTE**
> Please describe on each question as much as you can.

## What existing feature are you requesting from?

Scanner incorrectly marks all my characters as C6.

## What can we get from this feature?

![image_2022-06-14_122329588](https://user-images.githubusercontent.com/50675985/173671789-fc7696c8-dd87-42b9-87cd-59aa26a3e29a.png)

**Comment by sagelga** [comment]
What you are asking is probably a bug, not an enhancement to any feature.
Please close this Issue by pressing "Close Issue" and create a new one by choosing "Report a bug".

**Comment by Cupcak3** [comment]
From your screenshot I cannot tell if your Yelan is C6 or not. It's likely that the scanner is not delayed long enough for your particular computer. Increasing the delay for the scanner might fix this for you.

**Comment by Cupcak3** [comment]
I am closing this in favor of #227
