### ISSUE TITLE
[BUG] Data file does not exists for X

### ISSUE THREAD

**Issue by LoganOnii** [Andrewthe13th/Inventory_Kamera#315]
System.IO.FileNotFoundException: Data file does not exist for Characters.

   at InventoryKamera.DatabaseManager.GetList(ListType list)

   at InventoryKamera.DatabaseManager.LoadCharacters()

   at InventoryKamera.Scraper..cctor()

keep getting this error and im unsure of how to fix this, cant get past the first few seconds of start scanning

**Comment by Dobratr** [comment]
System.IO.FileNotFoundException: Data file does not exist for Characters.
   konum: InventoryKamera.DatabaseManager.GetList(ListType list)
   konum: InventoryKamera.DatabaseManager.LoadCharacters()
   konum: InventoryKamera.Scraper..cctor()

I have the same issue.
The scan doesn't start at all.

**Comment by awacs** [comment]
Have the exact same issue.

**Comment by KiraGio** [comment]
Having the same problem.

**Comment by LOKSTED** [comment]
It looks the issue was discovered and fixed in [vivienicepig:patch-1 ](https://github.com/vivienicepig/Inventory_Kamera/tree/patch-1) 

They also mentioned that "using System.Text;" should be added to the top

So if someone knows how to compile, please do.

The mentioned pull request: https://github.com/Andrewthe13th/Inventory_Kamera/pull/309#issue-1268207699

**Comment by HayashiLeroi** [comment]
> It looks the issue was discovered and fixed in [vivienicepig:patch-1 ](https://github.com/vivienicepig/Inventory_Kamera/tree/patch-1)
> 
> They also mentioned that "using System.Text;" should be added to the top of InventoryKamera/data/DatabaseManager.cs
> 
> So if someone knows how to compile, please do.
> 
> The mentioned pull request: [#309 (comment)](https://github.com/Andrewthe13th/Inventory_Kamera/pull/309#issue-1268207699)

Sorry I don't understand this. So how do we fix the bug?

**Comment by Cupcak3** [comment]
V1.2.7 should fix the auto updater not working. Let us know if the issue persists

**Comment by Cupcak3** [comment]
I am closing this issue now. Feel free to reopen if the issue still persists.
