### ISSUE TITLE
Scanner crashes whenever I try to scan

### ISSUE THREAD

**Issue by Sunrisetantalize** [Andrewthe13th/Inventory_Kamera#32]
I do all the steps then I leave the game and its at the start game screen. I scan but nothing happens then the app crashes, idk what im doing wrong. If soemone could help me figure this out it would be much appreciated :).

**Comment by giosann** [comment]
I had this happen to me and it was because even thoug i chagend the resolution to 720p i was coming from borderless fullscreen. If you are start the game from the actual launcher, it will take away the borderless.

**Comment by mmn6d6d6e** [comment]
I got the same issue.

1. Click scan
2. Window switched to the game
3. It opens Paimon Menu
4. Cursor move to the account name
5. App crashed

**Comment by Cupcak3** [comment]
It seems like the issue has been resolved so I am closing it.
