### ISSUE TITLE
[BUG] Scanner always failed to parse quantity

### ISSUE THREAD

**Issue by b4lesh** [Andrewthe13th/Inventory_Kamera#322]
In new version the scanner is not counting the Char Development Items correctly

Resolution: 1600x900 (window mode)
Kamera version: 1.2.7
All tables and game version are updated

https://user-images.githubusercontent.com/43409599/178224310-2bc1cee6-c484-4fc0-9029-288a1ec21577.mp4

**Comment by AstraeusZ** [comment]
I have the same problem here. The scanner gives "failed and false" results.

Examples of false results:
1. I have a 216 Hero's Wit, but the scanner results in 4414.
2. From the case in the video of b4lesh. He has a 108 Hero's Wit, but the scanner results in 8.

Resolution: 1600x900 (window mode)
Kamera version: 1.2.7
All tables and game versions are updated

**Comment by distronic4** [comment]
This issue persists across all compatible resolutions and scan speeds, it also occurs individually whether scanning for "char development items" or "materials" independently

**Comment by MisterOcto** [comment]
Someone found a solution ?

**Comment by Cupcak3** [comment]
This is a duplicate of #96. The numbers are in too much of an inconvenient location and size for scanning to be 100%
