### ISSUE TITLE
[BUG] Scanning button enabled with no scan options selected.

### ISSUE THREAD

**Issue by OperationLucky** [Andrewthe13th/Inventory_Kamera#326]
scanner doesnt scan equipped weapons and artifacts

tried restarting the app but doesn't help

**Comment by b4lesh** [comment]
Hello. Can you sand us screenshot app, and write your Windows version

**Comment by OperationLucky** [comment]
Windows 11 Home 21H2
<img width="480" alt="image" src="https://user-images.githubusercontent.com/109564747/179715668-fbc5539f-fb64-4ba4-9419-ece9363286e5.png">

**Comment by b4lesh** [comment]
Do you have error in the error log at the bottom of the app?
You can try to deactivate the checkbox "Equip Weapon", try to scan and after that activate checkbox and try to scan again.

**Comment by OperationLucky** [comment]
sry for a late replt buy ok ill try that asap

**Comment by Cupcak3** [comment]
Hi there you must select one or more scan items from the left side of the application to begin a scan. But thanks for highlighting this for me lol
