### ISSUE TITLE
[BUG] "Genshin window could not be focused. Please make sure the game is visible." 

### ISSUE THREAD

**Issue by xetrovial** [Andrewthe13th/Inventory_Kamera#329]

**Comment by TheFarix** [comment]
Make sure that Genshin Impact is in Window Mode and not Full Screen. Alt-Enter will let you switch between the two modes.

**Comment by Cupcak3** [comment]
Farix is correct. If your game is in true fullscreen and disappears when clicking or alt-tabbing out then the scan will fail to start. I haven't looked much into how to bring focus back to a true fullscreen process yet. This is a low priority issue to debug as windowed resolutions can be brought back into focus for scanning. Code contributions to this issue are welcome.

**Comment by AidanP771** [comment]
I am also having this issue. However, my game is in windowed mode and is completely visible.

**Comment by Cupcak3** [comment]
[V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0) now has fullscreen support.
