### ISSUE TITLE
[BUG] Scanner does not begin artifact scan

### ISSUE THREAD

**Issue by Amateretsu** [Andrewthe13th/Inventory_Kamera#331]
> **NOTE**
> Please describe on each question as much as you can.

## What seems to be an issue / question?
 When selecting to scan artifacts rarity minimum 5 the scanner opens up my artifact inventory and then selected the first artifact, doesn't scan it, and closes my inventory.

https://user-images.githubusercontent.com/108034721/180615762-fd937704-066f-45ad-9a64-a1117abb9ff8.mp4

## What have you done / tried?
Slowing down scan speed, attempting weapon and character scans (same result) and changing minimum values for scanning. If I decide to scan say Character, Weapon, and Artifacts then it does 1 of each.

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [ X] I have checked Issue page and there is **none** similar/unrelated to mine.

**Comment by Amateretsu** [comment]
Note: The video is only the top left of my screen. (The game is fully visible on my monitor, nothing is cut off like in the video)

**Comment by Cupcak3** [comment]
Can you give more description on your system? In your video I see an X button to close the game menu when Kamera's 'Navigation' display shows the artifact count. That's probably messing up the artifact count parsing and just giving up. I've never seen the X there and I don't know if that's new or has been part of the game and is configuration specific.

**Comment by Cupcak3** [comment]
Though it does seem to be parsing the number... Not sure why it's not starting. Please attach one or both of the logs generated.

**Comment by Amateretsu** [comment]
Hopefully these are the right logs :)

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/9174657/InventoryKamera.log)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/9174658/InventoryKamera.debug.log)

**Comment by Amateretsu** [comment]
Also my system OS: Microsoft Windows 11 Pro (Ver. 10.0.22000 Build 22000)

Let me know if you need anything else

**Comment by Cupcak3** [comment]
Blegh the logs don't help but not because of anything you did. I'll have to add more to the logs to figure this one out.. Maaaaybe it's to do with the fact that nearly all of your first page of artifacts are equipped and the character icons are throwing things off... Can you please run a scan with the 'Log All Screenshots' box checked and do an artifact scan, then zip up the `logging` folder and submit that? I'm curious whats being seen.

**Comment by Amateretsu** [comment]
[logging.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/9174686/logging.zip)

**Comment by Cupcak3** [comment]
Do you by chance have an ultrawide monitor? Your UI is not what I expect, it's compressed a bit.

**Comment by Amateretsu** [comment]
I do, I'll attempt on my normal monitor

**Comment by Amateretsu** [comment]
I did set my resolution to 1600:900 Windows if that helps

**Comment by Cupcak3** [comment]
If you restart your game does this part of the Paimon menu go flush with the edge of the window?
![image](https://user-images.githubusercontent.com/8845977/180623611-65f84830-c889-4f23-868d-44a3196cbbc3.png)

**Comment by Amateretsu** [comment]
Yep, I was able to get that menu flush. That seems to have fixed it! Thank you so much!

**Comment by Cupcak3** [comment]
Glad that fixed it. Anything you can tell me about your monitor or what you think might have cause the compressed UI? Usually it's an ultrawide thing and the only fix is to set a resolution to not ultrawide and then restart the game.

**Comment by Amateretsu** [comment]
I would assume it is due to the Ultrawide aspect as well. I run the launcher through steam with a "-popupwindow -screen-height 1440 -screen-width 3440" parameter in the launch properties.
