### ISSUE TITLE
[BUG] Cannot handle non-English traveler names

### ISSUE THREAD

**Issue by 3ckat1** [Andrewthe13th/Inventory_Kamera#337]
### Current Behavior

Scanned for weapons, characters, and artifacts. My male traveler (named 抹茶) is scanned as Klee (I don't have her), checked by looking at JSON exports.

This issue happened on all 2 occasions when using the scanner. Traveler name is the same for both scans.

### Expected Behavior

Scanner to correctly exports data

### Reproduce a Behavior

1. Start on 1920x1080 borderless
2. Wait
3. Finish scanning and check JSON files

### Device OS

Windows 10

### Genshin Impact Version

2.8 (pre-release)

### Inventory Kamera Version

1.2.7

### Screen resolution, screen mode, and UI scale

1920x1080, windowed

### Evidence

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/9180037/InventoryKamera.log)

### Preflight Checklist

- [X] I have checked the issue page, and there were none that similar to the one I'm reporting.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [x] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I did not enable any image filtering software or plugins (ie. HDR, Image Sharpening, etc.) while scanning.
- [X] I use default keybindings or have configured keybindings to the scanner.

**Comment by Cupcak3** [comment]
Hmm this one might be tricky because your traveler name does not use the English alphabet.. So it's unlikely that I can fix this right away without edging into language-support territory. I don't have a very good workaround for your problem at the moment. But thanks for the report.

**Comment by 3ckat1** [comment]
No worries! I can manually edit the JSON files. Thanks for the response :D
