### ISSUE TITLE
Scanning not working on artifacts or weapons

### ISSUE THREAD

**Issue by kazuhasssimp** [Andrewthe13th/Inventory_Kamera#341]
### Current Behavior

Everytime i scan my genshin account (following all instructions!), the scanner only gets the characters. When done with characters it moves on to attempting to scan weapons and artifacts but the scan is finished after the messages "Unable to locate artifact count." and "Unable to locate weapon count." appear. I don't know what i'm doing wrong, any help is welcome!!!

### Expected Behavior

Scanner to correctly exports data

### Reproduce a Behavior

'

### Device OS

Windows 10

### Genshin Impact Version

2.8

### Inventory Kamera Version

1.2.7

### Screen resolution, screen mode, and UI scale

1280x720

### Preflight Checklist

- [X] I have checked the issue page, and there were none that similar to the one I'm reporting.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I did not enable any image filtering software or plugins (ie. HDR, Image Sharpening, etc.) while scanning.
- [X] I use default keybindings or have configured keybindings to the scanner.

**Comment by Cupcak3** [comment]
Please zip up the logging folder and submit it here.

**Comment by Jordo24** [comment]
the scanner worked properly days ago for me and i have the same settings as this person, but my issue is slightly different, the scanner is completely skipping over my 4 star weapons even though the scanners logic is set to scan at least 3 star gear

**Comment by Cupcak3** [comment]
I am going to close this issue because the requested logs have not been provided. Feel free to reopen this issue.
