### ISSUE TITLE
Error: aanemodmgbonus is not a valid Main Stat Name

### ISSUE THREAD

**Issue by jeiseun1017** [Andrewthe13th/Inventory_Kamera#35]
When you own the _**Viridescent Venerer**_ you get the error **"Error: aanemodmgbonus is not a valid Main Stat Name"** message and then after it scans your whole artifacts the application crash. 
![image](https://user-images.githubusercontent.com/53262509/138731263-ed9692c2-8250-4125-984f-edf128506e62.png)

**Comment by Cupcak3** [comment]
This is a very old issue and has been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
