### ISSUE TITLE
Gladiator set artifacts are wrongly scanned as Gambler

### ISSUE THREAD

**Issue by ninjamask** [Andrewthe13th/Inventory_Kamera#351]
### Current Behavior

Scanner scans a lot of my Gladiator set artifacts and wrongly marks them as Gambler set in the json.

### Expected Behavior

Other (please specify in additional notes)

### Reproducing a Behavior

scanning

### Device OS

Windows 10

### Genshin Impact Version

2.8

### Inventory Kamera Version

1.2.8

### Screen resolution, screen mode, and UI scale

1280x720

### Evidence

[wrong artifacts.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/9255234/wrong.artifacts.zip)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [x] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Hi there this sort of bug already has been reported #240
