### ISSUE TITLE
scanner scans all characters as c6

### ISSUE THREAD

**Issue by Loraxsx** [Andrewthe13th/Inventory_Kamera#357]
### Current Behavior

scans the locked constellations as unlocked

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

scan characters ig?

### Device OS

Windows 11

### Genshin Impact Version

2.8

### Inventory Kamera Version

1.2.8

### Screen resolution, screen mode, and UI scale

1280x720

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [ ] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
I am closing this issue as it is a duplicate
