### ISSUE TITLE
artifact scanning is messing up

### ISSUE THREAD

**Issue by SeaPeixes** [Andrewthe13th/Inventory_Kamera#358]
### Current Behavior

the scanner just breaks all of a sudden and misses a whole page of artifacts

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

I wouldn't know how to reproduce the issue. It came out of no where for me

### Device OS

Windows 10

### Genshin Impact Version

2.8.0

### Inventory Kamera Version

1.2.8

### Screen resolution, screen mode, and UI scale

1600x900

### Evidence

Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)

   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)

   at InventoryKamera.InventoryKamera.GatherData()

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Goutak** [comment]
I had the same problem but once I deactivated the Geforce Experience settings, the scan worked again.

**Comment by Cupcak3** [comment]
Artifact scanning has been improved in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0). Additionally, please try Goutak's suggestion of turning of image sharpening with your GPU software.
