### ISSUE TITLE
Weapons missing

### ISSUE THREAD

**Issue by Maill** [Andrewthe13th/Inventory_Kamera#36]
Latest version (0.9), Vortex Vanquisher and Freedom-Sworn are not correctly parsed and throws errors.

Error log from the tool : 
```
Error: Found instead of Weapon Level.
Error: mysticenhancementore is not a valid Weapon Name
```

Error log from Genshin Optimizer : 
```
[
  {
    "key": "VortextVanquisher",
    "level": 50,
    "ascension": 3,
    "refinement": 1,
    "location": ""
  },
  {
    "key": "Freedom-Sworn",
    "level": 1,
    "ascension": 0,
    "refinement": 1,
    "location": "KaedeharaKazuha"
  }
]
```

**Comment by Andrewthe13th** [comment]
ok

**Comment by Cupcak3** [comment]
This is a very old issue and has been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
