### ISSUE TITLE
scan crashed

### ISSUE THREAD

**Issue by qwertroot12345** [Andrewthe13th/Inventory_Kamera#360]
### Current Behavior

scan crashed,and remind systemlog:

错误应用程序名称: InventoryKamera.exe，版本: 1.2.8.0，时间戳: 0x93d9239f
错误模块名称: KERNELBASE.dll，版本: 10.0.18362.815，时间戳: 0x67005c2a
异常代码: 0xe0434352
错误偏移量: 0x00114402
错误进程 ID: 0x2aa0
错误应用程序启动时间: 0x01d8afbecf16178c
错误应用程序路径: D:\Inventory_KameraV1.2.8\InventoryKamera.exe
错误模块路径: C:\windows\System32\KERNELBASE.dll
报告 ID: 30f74621-4f9e-4971-9e8c-fb5118ab97aa
错误程序包全名: 
错误程序包相对应用程序 ID: 

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

at any time when start scan

### Device OS

Windows 10

### Genshin Impact Version

 Genshin Impact version2.8 

### Inventory Kamera Version

1.2.8

### Screen resolution, screen mode, and UI scale

1920*1080,windowed,125%

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Please submit the crash log for this or give more information on the crash and what you do that leads to this.

**Comment by Cupcak3** [comment]
No information has been provided for quite some time so I am closing this issue,
