### ISSUE TITLE
Parse Failed

### ISSUE THREAD

**Issue by Engylizium** [Andrewthe13th/Inventory_Kamera#363]
### Current Behavior
```

Unable to validate information for artifact ID#152
Invalid artifact set name **(This is Lavawalker)**
Artifact ID: 152
Slot: flower
Set: 
Rarity: 5
Level: 20
Main Stat: hp
Substat 1: critDMG_ + 12.4%
Substat 2: critRate_ + 10.9%
Substat 3: atk_ + 4.1%
Substat 4: enerRech_ + 9.7%
Locked: False

Could not determine Zhongli's level. Setting to 1. **(It's 81)**
Could not determine Noelle's level. Setting to 1. **(It's 90)**

Failed to parse quantity for OminousMask 
Failed to parse quantity for FossilizedBoneShard 
Failed to parse quantity for DvalinsPlume 
Failed to parse quantity for DragonLordsCrown 
Failed to parse quantity for BloodjadeBranch
Failed to parse quantity for GildedScale
Failed to parse quantity for VarunadaLazuriteFragment
Failed to parse quantity for VajradaAmethystChunk
Failed to parse quantity for VayudaTurquoiseChunk
Failed to parse quantity for VayudaTurquoiseFragment
Failed to parse quantity for GuideToFreedom
Failed to parse quantity for GuideToDiligence
Failed to parse quantity for MistVeiledPrimoElixir
Failed to parse quantity for LustrousStoneFromGuyun
Failed to parse quantity for ShacklesOfTheDandelionGladiator
Failed to parse quantity for Crystalfish
Failed to parse quantity for GoldenKoi
Failed to parse quantity for PurpleShirakodai
Failed to parse quantity for AbidingAngelfish
Failed to parse quantity for RaimeiAngelfish
Failed to parse quantity for Pufferfish
Failed to parse quantity for DivdaRay
Failed to parse quantity for FormaloRay
Failed to parse quantity for Jam
Failed to parse quantity for Cecilia
```

Edit: Also found those incorrect values below:
`"HellfireButterfly":44447,"MudraOfTheMaleficGeneral":44887,"TearsOfTheCalamitousGod":44887,"TheMeaningOfAeons":48447,"BasaltPillar":44,"EverflameSeed":4,"CleansingHeart":424,"CrystallineBloom":424
`
Edit2: I did rescan with Slower setting:
```
Invalid level Xinqiu
_and the same_ Unable to validate information for artifact ID#152

Failed to parse quantity for ForbiddenCurseScroll
Failed to parse quantity for CrystalPrism
Failed to parse quantity for DvalinsPlume
Failed to parse quantity for DragonLordsCrown
Failed to parse quantity for BloodjadeBranch
Failed to parse quantity for GildedScale
Failed to parse quantity for VarunadaLazuriteFragment
Failed to parse quantity for VajradaAmethystChunk
Failed to parse quantity for VayudaTurquoiseChunk
Failed to parse quantity for VayudaTurquoiseFragment
Failed to parse quantity for GuideToFreedom
Failed to parse quantity for GuideToDiligence
Failed to parse quantity for MaskOfTheTigersBite
Failed to parse quantity for MaskOfTheOneHorned
Failed to parse quantity for MistVeiledPrimoElixir
Failed to parse quantity for LustrousStoneFromGuyun
Failed to parse quantity for ShacklesOfTheDandelionGladiator
Failed to parse quantity for Crystalfish
Failed to parse quantity for VenomspineFish
Failed to parse quantity for GoldenKoi
Failed to parse quantity for PurpleShirakodai
Failed to parse quantity for AbidingAngelfish
Failed to parse quantity for RaimeiAngelfish
Failed to parse quantity for Pufferfish
Failed to parse quantity for DivdaRay
Failed to parse quantity for FormaloRay

```
But why? Only you can figure this out

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Everything in settings set by default except resolution is 2560x1600 windowed. Settings are high since I have nice specs, no lags.
In scanner I turned off "equip weapons" and "equip artifacts" because I don't know what those are doing and I'm afraid to lose my setups

### Device OS

Windows 10

### Genshin Impact Version

2.8

### Inventory Kamera Version

1.2.8

### Screen resolution, screen mode, and UI scale

2560x1600

### Additional notes and remarks

Sorry for messy bug report, dunno how to report those mistakes made by scanner

### Evidence

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/9383714/InventoryKamera.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Artifact set scanning and material scanning have been improved in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0)
