### ISSUE TITLE
Dendro Goblets scan incorrectly

### ISSUE THREAD

**Issue by RarePossum** [Andrewthe13th/Inventory_Kamera#369]
### Current Behavior

Currently, when a dendro goblet is scanned, the program picks it up as a Hydro Goblet rather than a dendro goblet. 

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Scan a dendro goblet

### Device OS

Windows 10

### Genshin Impact Version

3.0

### Inventory Kamera Version

1.28

### Screen resolution, screen mode, and UI scale

1920x1080

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Fixed in [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0)
