### ISSUE TITLE
Immediate Abort of Scanning Process

### ISSUE THREAD

**Issue by unlikely-charlie** [Andrewthe13th/Inventory_Kamera#373]
### Current Behavior

I've done everything as I'm supposed to, as far as I'm aware, but I'll detail the process.

I unzipped the Kamera app after downloading, and opened the .exe program.

I've opened Genshin and switched my window to 1600x900 (Windowed) and then went back to the Paimon Menu.

My controls are set to Keyboard, and I don't have Inventory (B) or Characters (C) bound to anything but B and C

I try to scan, and the app immediately aborts the scan, throwing this error:

```
System.DllNotFoundException:` Failed to find library "tesseract41.dll" for platform x86.


   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)


   at InteropRuntimeImplementer.TessApiSignaturesInstance.TessApiSignaturesImplementation..ctor(LibraryLoader loader)
```

These files _are_ in the folder, but don't seem to be found.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

I don't know, as I opened the program and immediately experienced the error upon trying to scan.

### Device OS

Windows 11

### Genshin Impact Version

3.0

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

1600x900

### Additional notes and remarks

I did find a few threads with similar issues but they had no solutions because the OPs didn't include enough information.

### Evidence

System.DllNotFoundException: Failed to find library "tesseract41.dll" for platform x86.

   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)

   at InteropRuntimeImplementer.TessApiSignaturesInstance.TessApiSignaturesImplementation..ctor(LibraryLoader loader)

![Screenshot (47)](https://user-images.githubusercontent.com/112905946/188513807-6858d8e7-fddb-4bcb-91b2-51763d23aba8.png)

edit: formatting

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
> System.DllNotFoundException: Failed to find library "tesseract41.dll" for platform x86.

Please make sure you unzipped the release completely and the x86 and x64 folders exist with two files in them
![image](https://user-images.githubusercontent.com/8845977/188514924-9942b7f2-3c64-42ed-b001-9df50a7e613a.png)

**Comment by unlikely-charlie** [comment]
![image](https://user-images.githubusercontent.com/112905946/188515451-29a48e11-d6f7-40a9-819b-7d9258b95038.png)
![image](https://user-images.githubusercontent.com/112905946/188515469-50774ebb-4f8e-440c-b113-47062e22e3eb.png)
![image](https://user-images.githubusercontent.com/112905946/188515493-20ae35a5-4f87-405f-be8d-e1430439324e.png)

Unless I'm mistaken I believe I have already?

**Comment by unlikely-charlie** [comment]
I run Genshin on an external hard drive, could it have to do with that?

**Comment by Cupcak3** [comment]
That's not likely. Do you have the [latest packages](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) from Microsoft?

**Comment by unlikely-charlie** [comment]
I'll double check! I believe I have the 64 but not the 86 version. Where do these go on my computer once I get them downloaded?

**Comment by Cupcak3** [comment]
The default installer should be fine.

**Comment by unlikely-charlie** [comment]
That got it working, thank you!
