### ISSUE TITLE
[BUG] scanner opens shop page and doesn't progress

### ISSUE THREAD

**Issue by TheSast** [Andrewthe13th/Inventory_Kamera#378]
### Current Behavior

The software opens my paimon menu, then my shop, closes both menus and re-opens the latter.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

I have no idea how to reproduce the behavior, I have included a video recording (which also has the error log shown)

### Device OS

Windows 10

### Genshin Impact Version

3.0.0

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

1920x1080, windowed

### Additional notes and remarks

This doesn't seem to be affected by changing namecards.

### Evidence

https://youtu.be/CwGfJOUKIQk

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by TitaniumLexa** [comment]
You need to keep Paimon menu open before start scanning.

**Comment by TheSast** [comment]
> You need to keep Paimon menu open before start scanning.
You are right, in the clip I sent you that was what was creating the problem, I have tried it now multiple times and can confirm that that has improved the odds of the issue not happening, it still happens sometimes, if I do manage to get one on video I'll send it here as a reply.
