### ISSUE TITLE
Scanner doesn't recognize window resolution

### ISSUE THREAD

**Issue by lonecookie** [Andrewthe13th/Inventory_Kamera#38]
Every time I try to scan the error "Game Window not set to 1280x720 Windowed" show up, even if the game is in that resolution. Tried restarting several times the game.

**Comment by jsosulska** [comment]
Can confirm this happens on my GF's razor 15 laptop when attached to a secondary monitor. Works fine on a windows 10 laptop screen at native resolution, and on a desktop.

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease. Please let us know if those versions have been fixed so that we may close this issue.
