### ISSUE TITLE
Items with a quantity of 6 have errors.

### ISSUE THREAD

**Issue by ztmaev** [Andrewthe13th/Inventory_Kamera#380]
### Current Behavior

When the program scans a material with a quantity of 6 the program fails to identify the number and it puts the quantity as 0 in the output.

### Expected Behavior

Other (please specify in additional notes)

### Reproducing a Behavior

The scanner should be able to identify the number 6 and output correctly.

### Device OS

Windows 11

### Genshin Impact Version

3.1

### Inventory Kamera Version

1.3.0

### Screen resolution, screen mode, and UI scale

1280x720 (windowed)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This falls under one of the general pinned issues so I will be closing this as a duplicate.
