### ISSUE TITLE
Scanner Closes / Keep Crashing

### ISSUE THREAD

**Issue by Fradgaxd** [Andrewthe13th/Inventory_Kamera#39]
Pretty sure I followed the guide step by step, but I will just walk thro my steps atleast

- Downloaded the 0.9 version
- Unziped it
- Startet the program and then launched genshin
- put the game in 1280x720 Windowed and Controler type Keyboard 
- left the window in the paimon menu / esc menu 
- click scann

wosh and it crashes and will constantly close it self.  any ideas?

**Comment by Fradgaxd** [comment]
Tryed what you said dromzeh still crashing. No one is really helping here either so I guess its a no go for me atm. cba manually adding my artifacts and wepons got 291 artifacts atm that are not trash so its a meh :P

**Comment by dromzeh** [comment]
> 
> 
> Tryed what you said dromzeh still crashing. No one is really helping here either so I guess its a no go for me atm. cba manually adding my artifacts and wepons got 291 artifacts atm that are not trash so its a meh :P

i have no wonder why it still isn't working for you then, are you able to send a video or something like that showing it crash?  it might help me or any others who stumble across this help find a fix to your issue

**Comment by sagelga** [comment]
Is #53 helps? @Fradgaxd

**Comment by Washaka** [comment]
Hi, I downloaded and followed the instructions correctly. Inventory Kamera automatically closes while scanning Gladiator's artifact set Feathers. I tried upgrading that feather, then the other. Now it crashes at the sands lol. Please help me.

It crashes after the same duration of the scan at the artifacts always. Even if I scanned the weapons before it would crash at the exact same point.

**Comment by Cupcak3** [comment]
These issues have been hopefully fixed by a recent release or prerelease. Please let us know if they have been so that we may close this issue.
