### ISSUE TITLE
Only scans 3 characters

### ISSUE THREAD

**Issue by lizardamiibo** [Andrewthe13th/Inventory_Kamera#391]
### Current Behavior

I'll post a picture of my preferences and scanner output below, where you can see I have it set to only scan my characters; however, it initially happened while I was doing a full account scan. Note that it does not report any errors. After one of these bugged scans, it failed to determine the level of the Traveler, but only once. Additionally, it seems to only actually scan 2 characters (skips the first one, Cyno), which can be seen in the screenshot and in the JSONs (posted below).

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

I tried to record a video but OBS and the scanner don't seem to work at the same time.
![image](https://user-images.githubusercontent.com/115457827/194828651-c62d87fe-f1a2-43de-8e7f-3a5be0a5b50f.png)

### Device OS

Windows 10

### Genshin Impact Version

3.1

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

1920x1080 fullscreen

### Additional notes and remarks
`{"format":"GOOD","version":1,"kamera_version":"1.3","source":"Inventory_Kamera","characters":[{"key":"Traveler","level":90,"constellation":0,"ascension":6,"talent":{"auto":2,"skill":7,"burst":8}},{"key":"KukiShinobu","level":70,"constellation":4,"ascension":4,"talent":{"auto":1,"skill":6,"burst":1}}]}`

Every JSON reads the same. Also evidenced in the JSONs is an incorrect read on the Traveler's constellation, which should be 5; it did this all 5 times I scanned.

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This issue is very old and has likely been resolved.
