### ISSUE TITLE
[BUG] Scanner Stops Scan Prematurely When Min Level and Rarity Are Set

### ISSUE THREAD

**Issue by juuyokka** [Andrewthe13th/Inventory_Kamera#392]
### Current Behavior

If you set the minimum artifact level and rarity, it's possible that the scanner stops prematurely. As implemented now, the scanner will stop as soon as it encounters an artifact whose level OR rarity is below the minimum set by the user.

![image](https://user-images.githubusercontent.com/15185244/195966903-7ccfe30e-53ae-4af2-b028-b878b842f699.png)

In this case, if the minimum rarity is set to 5, the scanner will stop when it reaches an artifact with rarity 4.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

1. Set the minimum artifact rarity to 5 and the minimum level to 4.
2. Ensure that you have 4 star artifact whose level is above 4.
3. Use the scanner to scan artifacts.

### Device OS

Windows 10

### Genshin Impact Version

3.1

### Inventory Kamera Version

1.3.0

### Screen resolution, screen mode, and UI scale

1920x1080 windowed

### Additional notes and remarks

The scanner should stop when it encounters an artifact whose level AND rarity is below the minimum set by the user. Any artifacts whose level OR rarity is below should be skipped but should not cause the scan to end. I haven't tested this with weapons but I'd imagine that if the issue is present for artifacts it should be also present for weapons as well.

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by juuyokka** [comment]
It looks like the code causing this behavior is here.
https://github.com/Andrewthe13th/Inventory_Kamera/blob/0655b471388b6149b3e343c28a53c79bcb1e7259/InventoryKamera/scraping/ArtifactScraper.cs#L487-L488

Here is the analogous code for weapon scanning. 
https://github.com/Andrewthe13th/Inventory_Kamera/blob/0655b471388b6149b3e343c28a53c79bcb1e7259/InventoryKamera/scraping/WeaponScraper.cs#L420-L421

**Comment by Cupcak3** [comment]
This should be fixed in [V1.3.1](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.1)

**Comment by Nikolas-VIII** [comment]
Also, with the new behavior, the filtered out artifacts do still end up in the json file. So the filters do effectively not work anymore.

**Comment by Thaddaios94** [comment]
This is the error log I'm getting when scanning artifacts:

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)
   at InventoryKamera.InventoryKamera.GatherData()

**Comment by juuyokka** [comment]
> From what I can gather from this bug report, this bug was only possible because @juuyokka used the non-default sort of Level instead of the default sort of Rarity. @NNowakowski 

https://github.com/Andrewthe13th/Inventory_Kamera/blob/0655b471388b6149b3e343c28a53c79bcb1e7259/InventoryKamera/scraping/ArtifactScraper.cs#L39-L43

Level sorting is set automatically by Inventory Kamera when the minimum artifact level is set.

**Comment by Cupcak3** [comment]
This issue should be fixed in v1.3.2
