### ISSUE TITLE
v1.3.2 zip triggered Windows Defender: Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by doxxx** [Andrewthe13th/Inventory_Kamera#396]
### Current Behavior

When I downloaded the v1.3.2 zip from the releases page and opened it, Windows Defender popped up a warning that said it detected `Trojan:Script/Wacatac.B!ml` in the zip, which is apparently considered to be a "Severe" threat.

### Expected Behavior

Other (please specify in additional notes)

### Reproducing a Behavior

Download the 1.3.2 zip on Windows 10 and open it.

### Device OS

Windows 10

### Genshin Impact Version

n/a

### Inventory Kamera Version

1.3.2

### Screen resolution, screen mode, and UI scale

n/a

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [ ] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [x] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Hmm I can't reproduce this on Windows 11 so all I can really say is it's a false positive. The code is all there on the repo, and nothing in changes between 1.3.1 and 1.3.2 source code should cause this.

**Comment by doxxx** [comment]
I redownloaded the same zip and unpacked it, but Defender didn't trigger this time. 🤷
