### ISSUE TITLE
Doesn't scan the first two lines of artifacts

### ISSUE THREAD

**Issue by Fren62** [Andrewthe13th/Inventory_Kamera#397]
### Current Behavior

The program should scan every line of artifacts

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

1920x1080 Fullscreen
check "artifacts" in scan items

### Device OS

Windows 11

### Genshin Impact Version

3.2

### Inventory Kamera Version

1.3.1 and 1.3.2 (bug found in both versions)

### Screen resolution, screen mode, and UI scale

1920x1080 Fullscreen

### Additional notes and remarks

the mouse doesn't click in the right position so it skips some lines of artifacts. I found out it also skips some other lines in addition to the first two.

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Thaddaios94** [comment]
I'm having a similar issue. The scanner is skipping lines later on in the scan. It's not skipping the first ones for me.

**Comment by Cupcak3** [comment]
An issue already exists documenting this behavior so I am closing this issue as a duplicate
