### ISSUE TITLE
The Kamera does not recognize Wanderer with a custom name

### ISSUE THREAD

**Issue by hazydream** [Andrewthe13th/Inventory_Kamera#405]
### Current Behavior

I think everything works as intended; it's just that now Wanderer can have a custom name given by the player.

### Expected Behavior

Other (please specify in additional notes)

### Reproducing a Behavior

-

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.3

### Screen resolution, screen mode, and UI scale

1920x1080

### Additional notes and remarks

You can name Wanderer in the 3.3 archon quest, and it will change the displayed name of Wanderer. (This also affects the character page and inventory.) You can only name him for a limited time.

I worked around it by adding this to the `characters.json`.
```
"bongohead": {
    "GOOD": "Wanderer",
    "ConstellationOrder": [
      "burst",
      "skill"
    ],
  	"WeaponType": 4
},
```

### Evidence

![image](https://user-images.githubusercontent.com/61898056/206355792-1d1c5c76-117e-4c93-8c55-cc6a90673569.png)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
V1.3.4 should add an option for adding a custom name for your wanderer but I haven't tested it with my own game yet. Do you mind trying it out and testing your custom name as "Bongo Head", "bongohead", and "Bongo-Head"? Right now it doesn't try to normalize the input in any way so it could be off for unique names like yours.

**Comment by hazydream** [comment]
I tried version 1.3.4, but it did not work. I tried each of the names you mentioned twice, and each time I received the same error. I'll include it below.

I removed the other four artifacts from the log I attached below to save space, but they all have the same log message as the sample I provided.

```
Unable to validate information for weapon ID#2
Inavlid equipped character
Weapon ID: 2
Name: LostPrayerToTheSacredWinds
Rarity: 5
Level 90
Refinement: 1
Locked: True
Equipped character: Wanderer

Unable to validate information for artifact ID#49
Invalid equipped character
Artifact ID: 49
Slot: flower
Set: ShimenawasReminiscence
Rarity: 5
Level: 20
Main Stat: hp
Substat 1: critDMG_ + 12.4%
Substat 2: critRate_ + 13.6%
Substat 3: def + 16
Substat 4: atk_ + 4.1%
Locked: True
Equipped character: Wanderer
```

**Comment by Diana1620** [comment]
I have the same issue, pretty much the same error codes too

Originally when trying V1.3.3 it would scan Wanderer (he's in the first character spot for me) and his artifacts/weapon but the scanner thought he was Mona. So it would think it already scanned Mona and when it actually reached her in my character menu it would stop. Uploading the data to the optimizer showed that it equipped his artifacts to Mona too. 

I just downloaded V1.3.4 and I'm now having the same issue as the other player where it has an issue after scanning him or anything he has equipped, it stops right after scanning him.

![KameraWanderer](https://user-images.githubusercontent.com/120339899/207946216-2548ff68-e289-4ea3-9404-7e172b85aa89.png)

**Comment by Festo36** [comment]
Hello! 
I've got the same issue. 

![image](https://user-images.githubusercontent.com/34703218/208214347-c13d5da0-f537-41af-8d56-48797a0bc7fc.png)

If I delete the custom name, it simply won't any information about the character, even with a different name.
