### ISSUE TITLE
Doesn't recognize Artifacts with ATK sub-stat under 10

### ISSUE THREAD

**Issue by Queenhardt** [Andrewthe13th/Inventory_Kamera#407]
### Current Behavior

I only had that happening with the ATK sub-stat (not %) under 10 points, and that only occurred on 3-star artifacts (and probably also below that). The error is, that it doesn't recognize that specific sub-stat, every other sub-stat it recognizes. 
I just "fixed" it by not scanning artifacts below 4-star.
![ScreenShot_20221212054525](https://user-images.githubusercontent.com/82922999/207040504-acdf79cb-5d9d-4f15-a0a0-73607b2018d9.png)
![ScreenShot_20221212054805](https://user-images.githubusercontent.com/82922999/207040515-deeca864-87f9-45a4-88f0-ed2da95f0a2a.png)

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Just try it with an artifact with an under-10-points ATK sub-stat, I think that's it.

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.3

### Screen resolution, screen mode, and UI scale

2048x1152 Fullscreen

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Newer versions of Inventory Kamera have released since this issue was created. Please reopen this issue if the problem still persists in those versions.

**Comment by dudensen1** [comment]
Hello, the issue persists as of v1.3.12. I have 3star berserker artifacts with atk+8 and atk+7 and they are not being properly scanned so I assume this must be the issue.
