### ISSUE TITLE
it doesnt scan characters after itto

### ISSUE THREAD

**Issue by Gremhyr** [Andrewthe13th/Inventory_Kamera#408]
### Current Behavior

it doesnt scan characters after itto

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

it doesnt scan characters after itto. if i put itto first in the party it doesnt scan. if he doesnt in the party it only scan 5 characters and stop after itto.

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.3

### Screen resolution, screen mode, and UI scale

1280x720 1600x900

### Evidence

![Ekran görüntüsü 2022-12-12 211905](https://user-images.githubusercontent.com/103217855/207123417-aaea0de6-8f13-4142-9342-94852ba94186.png)
Verilen anahtar sözlükte yoktu.

   konum: System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   konum: InventoryKamera.CharacterScraper.ScanCharacter(String firstCharacter)

   konum: InventoryKamera.CharacterScraper.ScanCharacters(List`1& Characters)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by CodeSylo** [comment]
If you have any on-screen display such as Rivatuner with MSI Afterburner or discord overlay that blocks the characters name, it will not work. I was having this issue and rivatuner/discord overlay was the issue for me.

**Comment by Cupcak3** [comment]
Newer versions of Inventory Kamera have released since this issue was created. Please reopen this issue if the problem still exists in those versions.
