### ISSUE TITLE
Unable to validate information for artifact

### ISSUE THREAD

**Issue by IbarakiKasen** [Andrewthe13th/Inventory_Kamera#410]
### Current Behavior

One of my artifact is not in the result JSON. And this is the error log:
```
Unable to validate information for artifact ID#317

Invalid artifact sub stats
Artifact ID: 317
Slot: goblet
Set: EchoesOfAnOffering
Rarity: 5
Level: 0
Main Stat: hydro_dmg_
Substat 1: eleMas + 16
Substat 2: def_ + 7.3%
Substat 3: atk + 14
Locked: False
```

### Expected Behavior

The scanner exports the data

### Reproducing a Behavior

Use InventoryKamera.exe to scan only artifacts. This specific artifact is not included in the result JSON:

![Image](https://user-images.githubusercontent.com/24918484/207360579-903664be-a556-4d7d-8131-db5a139124d9.png)

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.4

### Screen resolution, screen mode, and UI scale

1280x720 windowed

### Evidence

GitHub has a 25MB limit on upload file, so I removed some irrelevant artifact* folders and ArtifactInventory*_8x5.png from the artifacts folder.

[logging.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/10218776/logging.zip)
[genshinData_GOOD_2022_12_13_09_01.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/10218784/genshinData_GOOD_2022_12_13_09_01.zip)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This issue is documented in another issue so I am closing it as a duplicate
