### ISSUE TITLE
Wrong resolution recognized as unsupported

### ISSUE THREAD

**Issue by mind-overflow** [Andrewthe13th/Inventory_Kamera#412]
### Current Behavior

I'm running GI on a dual-monitor setup. The main monitor has a resolution of 2880x1920 scaled at 200% (HiDPI). The second monitor is a standard 1366x768 VGA. The game is running on the second, low-res monitor. Inventory Kamera errors out saying `Unsupported resolution 2732x1536`.

### Expected Behavior

The scanner supports my device configuration

### Reproducing a Behavior

This is a screenshot showing that it errors out despite the resolution being a standard 1366x768.

![immagine](https://user-images.githubusercontent.com/67104846/208439674-6a6064b3-1930-4931-b252-2ff22d472e90.png)

### Device OS

Windows 11

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.4

### Screen resolution, screen mode, and UI scale

1366x768 at 100%, borderless

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Weird that it seems to be applying the 200% scaling. Window resolution is determined entirely through windows libraries so I'm not sure what I can do on Kamera's end to validate the resolution is correct.

In either case, 1366x768 is not a supported resolution regardless per [step 3-2 of the instructions.](https://github.com/Andrewthe13th/Inventory_Kamera#setting-up-genshin-impact)

**Comment by mind-overflow** [comment]
Oh, I see... Well, 1366x768 is *extremely* close to 16 : 9 (it's 16 : 8.99 ) so I thought it was still supported, since the button layout can't be that different from a pure 16:9 (Inventory Kamera clicks in the middle of buttons and things, and I'm pretty sure there isn't even a full single pixel difference from a 16:9 monitor layout in terms of button positioning)... So yeah, I'll keep that in mind and try again by running it in a lower-res windowed mode.  
  
Anyways, this is still weird because my main setup consists of a 4K monitor with 150% scaling, and two separate monitors with lower resolutions (1600x900 and 1920x1080) both at 100% scaling, and Inventory Kamera didn't give me any issue with the scaling on my main display.  
  
But if this is purely related to Windows APIs, and there's no way to fix it nicely (without making hacked-on modifications) then I guess you can just close the issue and we just hope that Microsoft fixes their APIs...
  
Thanks for taking the time to reply!
