### ISSUE TITLE
Scan produces errors on 3-start artifacts, unable to scan

### ISSUE THREAD

**Issue by ThiquidPenguiN** [Andrewthe13th/Inventory_Kamera#413]
### Current Behavior

Unable to scan some 3 star artifacts, appears as errors.

I have my resolution set to 1920x1080 and I have tried the slow scan option. I know my settings are correct as I was able to scan without issues earlier in the week. I have tried isolating to just scanning artifacts, changing the scan speed, using a different monitor, changing duplicate vs extended monitors (I have 2 monitors 1x 2k and 1x 1080p). I end up getting the same error logs and similar results every time.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

https://youtu.be/WtzT_QyQM_0

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.4 and 1.3.5

### Screen resolution, screen mode, and UI scale

1920x1080

### Additional notes and remarks

video of the scan

https://youtu.be/WtzT_QyQM_0

### Evidence

Unable to validate information for artifact ID#144

[20221219-errors.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/10273509/20221219-errors.txt)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

EDIT: condensed the wall of logs and fixed Genshin version to 3.3. Updated Kamera version to include 1.3.5 in my tests.

**Comment by ThiquidPenguiN** [comment]
Latest, I have rebooted my windows 10 machine and ran the new version 1.3.5 in a similar fashion to what I recorded in the post. I am still getting the same results. I have attached updated logs.
[20221220-errors.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/10273515/20221220-errors.txt)

**Comment by EffortlessFury** [comment]
I'll note that this has long been an issue for me, though I've just dealt with it, as honestly if you're looking to optimize, 3*s aren't a priority.

**Comment by ThiquidPenguiN** [comment]
Thanks Effortless, I have been playing for 4 months now and realizing that 4 stars are the way to go after playing awhile.

I agree with your reply, and will just focus on 4 stars since it works well with 4 stars and above.
