### ISSUE TITLE
Artifact substats export doesn't follow GOOD spec

### ISSUE THREAD

**Issue by Seeker14491** [Andrewthe13th/Inventory_Kamera#415]
### Current Behavior

Currently, artifact substats are always exported as a 4-item array, even if the artifact has less than 4 substats. The missing substats get a `null` key and a value of `0.0`. For example, this export snippet shows an artifact with 2 substats:

```
{
  "setKey": "DeepwoodMemories",
  "slotKey": "flower",
  "rarity": 4,
  "mainStatKey": "hp",
  "level": 0,
  "substats": [
    { "key": "eleMas", "value": 17.0 },
    { "key": "def", "value": 19.0 },
    { "key": null, "value": 0.0 },
    { "key": null, "value": 0.0 }
  ],
  "location": "",
  "lock": false,
  "id": 994
}
```

According to [the GOOD spec](https://frzyc.github.io/genshin-optimizer/#/doc), this is not valid. The substat key cannot be `null`, which implies these null entries should not be included.

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Scan any artifact(s) with less than 4 substats.

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.5

### Screen resolution, screen mode, and UI scale

1920x1080 windowed

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This has been corrected. Outputs no longer contain "null" for empty substats (fixed in commit 5436bb5).
