### ISSUE TITLE
Failure with items with "'s"

### ISSUE THREAD

**Issue by kikoptr** [Andrewthe13th/Inventory_Kamera#418]
### Current Behavior

In the object name list, when the name contains "'s" it is translated as "39S". According to the GOOD format it should be translated as "s". For example:
```
"Dvalin39SPlume": 55,
"Dvalin39SClaw": 41,
"Dvalin39SSigh": 53,
```

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

The correct names in this example is:
```
"DvalinsPlume": 55,
"DvalinsClaw": 41,
"DvalinsSigh": 53,
```

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.5

### Screen resolution, screen mode, and UI scale

1600x900

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Thanks for pointing this out. The updater should be fixed in the next version

**Comment by kikoptr** [comment]
Thanks to you for the work you are doing!

**Comment by IrfanNafiz** [comment]
Same issue, glad I found this before I posted an issue. Wrote a small code to replace all '39S' strings with 's' in the json file and it fixed everything.

**Comment by IrfanNafiz** [comment]
This issue only occurs for Character Development Materials. Artifacts with "'s" such as "Gladiator's Finale" are parsed correctly.

**Comment by Cupcak3** [comment]
Newer versions of Inventory Kamera should resolve this issue.
