### ISSUE TITLE
Facing an exception of "Failed to find library "leptonica-1.82.0.dll" for platform x64".

### ISSUE THREAD

**Issue by Bhanu7869** [Andrewthe13th/Inventory_Kamera#420]
### Current Behavior

Getting "Exception has been thrown by the target of an invocation" exception and "Failed to find library "leptonica-1.82.0.dll" for platform x64" as inner exception whenever we are calling a method of  new TesseractEngine(); using Tesseract dll.

### Expected Behavior

Other (please specify in additional notes)

### Reproducing a Behavior

Create a web application and add Tesseract dll to the references. Try to call  new TesseractEngine() method. 

### Device OS

Windows 10

### Genshin Impact Version

5.2

### Inventory Kamera Version

5.2.0

### Screen resolution, screen mode, and UI scale

1920x1080

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Please be sure to follow the install instructions [here](https://github.com/Andrewthe13th/Inventory_Kamera#installing-inventory-kamera). Usually a restart is required to fix.
