### ISSUE TITLE
Scan aborted - <StartButton_Clicked>b__13_0()

### ISSUE THREAD

**Issue by Olisteve** [Andrewthe13th/Inventory_Kamera#423]
### Current Behavior

When I press "Scan Genshin", it switches to Genshin Impact window (which is in the Paimon menu) and then reverts back to Inventory Kamera with the following error:   
at InventoryKamera.InventoryKamera.GatherData()
at InventoryKamera.MainForm.<StartButton_Clicked>b__13_0()
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/10444615/InventoryKamera.log)

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Just click on "Scan Genshin" while making you sure you have the correct resolution, up-to-date Microsoft Visual C++.... version, keybind to default, and game versions up-to-date.

https://user-images.githubusercontent.com/33529271/213145531-284732d6-26df-482c-a712-0d5eff60a0c5.mp4

### Device OS

Windows 11

### Genshin Impact Version

3.4

### Inventory Kamera Version

1.3.6

### Screen resolution, screen mode, and UI scale

1280x720

### Additional notes and remarks

I have tried all resolutions. Restarted both applications. Tried just scanning Artifacts and different variations. I have used also the correct Traveler's and Wnaderer's name.

### Evidence

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/10444701/InventoryKamera.log)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/10444704/InventoryKamera.debug.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by phucho0237** [comment]
same bug :(

**Comment by Orifarius** [comment]
Had the same issue, fixed by changing my nickname, guess Traveler and Wanderer nickname cannot be the same

**Comment by EinUnknownCoder** [comment]
And the nickname of the traveler must not have a name from another playable character (e.g. Tartaglia).

**Comment by Olisteve** [comment]
> And the nickname of the traveler must not have a name from another playable character (e.g. Tartaglia).

thank you @EinUnknownCoder , this solved the issue for me. My Traveler's Name was the same as an in-game character. When I changed it, it work without any issue.
