### ISSUE TITLE
Max levelled artifact scanned as lvl 2 instead of lvl 20

### ISSUE THREAD

**Issue by flemingoes** [Andrewthe13th/Inventory_Kamera#427]
### Current Behavior

I've tried scanning my artifacts several times and it always brought the same result. Tried scanning and different speeds and reinstalled the software but nothing changed.

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

.

### Device OS

Windows 10

### Genshin Impact Version

3.4

### Inventory Kamera Version

1.3.7

### Screen resolution, screen mode, and UI scale

1920x1080 Fullscreen

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [ ] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Please reopen this issue if the problem exists on recent versions
