### ISSUE TITLE
Infinite character scanning

### ISSUE THREAD

**Issue by Tron-Creeper2** [Andrewthe13th/Inventory_Kamera#429]
### Current Behavior

When scanning characters, after reaching the last character in the list, the scanner will loop back around to the first one and start scanning everything again. I let it run for a while but decided to stop it once it reached 319 characters scanned.
- Reproduced on fast (so far).

2nd time I was testing it, the same just stopped at 208.

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

Start a scan with the character scan option selected (in my case, had all "scan items" checked)
[Video proof](https://youtu.be/NdIWDc2gy8M)
![Screenshot_55](https://user-images.githubusercontent.com/94975374/216826957-e6c94f07-fe24-4897-b5ff-4e302087aeb7.png)

### Device OS

Windows 11

### Genshin Impact Version

3.4

### Inventory Kamera Version

1.3.7

### Screen resolution, screen mode, and UI scale

2560x1440 (fullscreen) and 1920x1080 (windowed)

### Additional notes and remarks

- #422 by [GH-Ben](https://github.com/GH-Ben)
- While in fullscreen, the game crashed twice or trice when I were out of the window (opened the game multiple times; each time it crashed that is,..)

### Evidence

[GoogleDrive - bug report + genshinData_GOOD.json](https://drive.google.com/drive/folders/1QvcU6yIDduZbeuTt04pUPWaVUk7TlhMC?usp=sharing)
[YouTube - Video proof](https://youtu.be/NdIWDc2gy8M)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by TitaniumLexa** [comment]
As i figured out that's because of Traveler in first slot. 
Temporary solution is move to another slot or use party without Traveler. 
Also created pull request with fix.
