### ISSUE TITLE
Error: prayerstospringtime is not a valid Set Name

### ISSUE THREAD

**Issue by gabip-ctrl** [Andrewthe13th/Inventory_Kamera#43]
Whenever I try to scan my characters, the scanner will always stop at Tartaglia, regardless if there are any other characters to scan. If he is in my party, it will skip him altogether.

Previously, I had an error similar to "error: prayerstosea is not a valid Set Name" or something, I've been trying to get the error to appear again but it doesn't say anything anymore. I thought it had something to do with his artifacts, so I unequipped all of them, but it still won't work.

Update, before posting this issue I tried once again to see if I could get the error name right, but this time it worked... I have done literally nothing different, except this time, the traveler is the one who didn't get scanned. The error I got is the following:

_**"Error: Error: prayerstospringtime is not a valid Set Name"**_
![imagem_2021-11-02_200815](https://user-images.githubusercontent.com/62409379/139964092-efc4d95c-cf35-4e2b-854f-2cc3e1103dba.png)

**Comment by Cupcak3** [comment]
I'm not sure what artifact could be parsed as `prayerstosea`. As for the `prayerstospringtime` error that's actually a typo in the artifacts list. All the other crown circlets are "Prayers _for_ X" but the Springtime circlet is "_to_". It's a simple fix.
