### ISSUE TITLE
Scanner Detects ALL Characters as Constellation 6 (C6)

### ISSUE THREAD

**Issue by Zerogeist** [Andrewthe13th/Inventory_Kamera#432]
### Current Behavior

When Scanning Characters, Inventory Kamera incorrectly identifies the constellation level as "Constellation: 6" regardless of the character's constellation level.

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Native Display is 3840x1080. Modified Genshin Settings to Display Mode: "1920x1080 Windowed"
Restarted Client to avoid published Widescreen Issues

Video was too large to upload to github.  Uploaded to YT here: https://youtu.be/VqV6IhgzWBo
Video includes incorrect scan of first two characters, on medium speed (but issue occurs on all characters at all speeds.)

### Device OS

Windows 11

### Genshin Impact Version

3.4

### Inventory Kamera Version

1.3.7

### Screen resolution, screen mode, and UI scale

1920x1080 Windowed

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Another issue exists describing this issue so I am closing this one as a duplicate
