### ISSUE TITLE
Quantity parsing; Invalid artifact sub stats; Unable to validate info for artifact ID#324, ID#316

### ISSUE THREAD

**Issue by Tron-Creeper2** [Andrewthe13th/Inventory_Kamera#434]
### Current Behavior

Got some errors
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/10845008/InventoryKamera.debug.log)
Also skipped a line, if I didn't miss-saw

### Expected Behavior

The scanner to not skip rows or items

### Reproducing a Behavior

The debug file might help ?
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/10845015/InventoryKamera.debug.log)

### Device OS

Windows 11

### Genshin Impact Version

3.4

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

1920x1080 (windowed)

### Additional notes and remarks

related: #410

### Evidence

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/10845017/InventoryKamera.debug.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
These have all been documented in various other issues so I am closing this issue
