### ISSUE TITLE
Could not determine character's element

### ISSUE THREAD

**Issue by tyvanmoppes** [Andrewthe13th/Inventory_Kamera#435]
### Current Behavior

Weapons and Artifacts scan OK. When the scanner gets to my characters, it opens up my first char (Hu Tao), goes to constellations, clicks each one and then exits out. It then normal attacks x 3, then stalls out and I get the error "Could not determine character's element."

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

screenshot
![Screenshot 2023-02-28 122536](https://user-images.githubusercontent.com/126603870/221930384-03e5e803-c6e1-4da0-9e16-8b77121ecb61.jpg)

### Device OS

Windows 11

### Genshin Impact Version

3.4

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

2560 x 1440p window

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [ ] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Please see the pinned comment regarding ultrawide monitors
