### ISSUE TITLE
Scan Aborted

### ISSUE THREAD

**Issue by Sintimacy** [Andrewthe13th/Inventory_Kamera#440]
### Current Behavior

Doesnt scan just instantly gives scan aborted. Res is set to 16:9 

### Expected Behavior

Other (please specify in additional notes)

### Reproducing a Behavior

Instantly get these errors.
![image](https://user-images.githubusercontent.com/127418082/224057239-da32e4e9-4ce7-4a06-a760-8a59eb210872.png)

### Device OS

Windows 11

### Genshin Impact Version

3.5

### Inventory Kamera Version

V1.3.8

### Screen resolution, screen mode, and UI scale

1600x900 windowed

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by sneakygreen** [comment]
I am experiencing a similar issue.

**Comment by briangohjw** [comment]
Experiencing this as well

**Comment by TheHunter7357** [comment]
i am experiencing this as well currently

**Comment by Ilzizi** [comment]
I got the same error... before this new update it ran normally...

**Comment by Cupcak3** [comment]
No additional information has been provided for this issue. I suspect it is similar to the "Failed to Initialize Tesseract Engine" error. An issue exists for this so I am closing this as a duplicate
