### ISSUE TITLE
Scanns weapons instead of artifacts, and puts those instead, and bugs the whole result.

### ISSUE THREAD

**Issue by McMaster2008** [Andrewthe13th/Inventory_Kamera#442]
### Current Behavior

For some reason, it doesnt go to the artifatcs tab, and constantly scanns the weapons tab of my inventory, i'm not even touching my mouse or keyboard, it just doesnt execute that single part correctly, and screenshots and registers my weapons as artifacts.

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

I dont know, maybe fix the coordinates of the click on the artifacts tab, or make it verify if it's a weapon or artifact on the tab it is while scanning the first item.

### Device OS

Windows 10

### Genshin Impact Version

3.5

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

1920*1080

### Evidence

![Uploading ArtifactInventory.png…]()
![Uploading ArtifactWindow_1920x1080.png…]()
![ArtifactCount](https://user-images.githubusercontent.com/68027397/227769463-403379d3-2564-43dd-af10-1163ea613658.png)
![Uploading ArtifactInventory0_8x5 - weight 0.png…]()

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
> Fix the coordinates for selecting inventory tab

Navigating to the correct inventory is quite reliable.

However the evidence you've provided isn't very helpful. (Your links re-direct right back to this issue). There has been a more recent release since this issue was posted. Please reopen this issue if the problem still exists in that version.
