### ISSUE TITLE
Issue with Scanning

### ISSUE THREAD

**Issue by k5ign** [Andrewthe13th/Inventory_Kamera#443]
### Current Behavior

When scanning artifacts, it skips over entire rows of artifacts.  I have tried different speeds and configurations and nothing changes.  Skips over the 2nd row on the 2nd page and then rescans the top row on the 3rd page.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Try to scan

### Device OS

Windows 10

### Genshin Impact Version

3.5

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

1920x1080

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by 501stRookie** [comment]
I am getting a similar issue, where after it scrolls down it skips the first row of artifacts after scrolling.

**Comment by Archangel87** [comment]
Same issue, tried with the scanning delay at maximum and still has the issue.

**Comment by DerpgonCz** [comment]
Should probably rename the issue to "Artifact scanning occasionally skips over rows"

**Comment by supernova-ws** [comment]
Same issue.
Inventory Kamera v1.3.8
Windows 10 Pro 22H2
Genshin Impact v3.6
Resolution 1920x1080

PROBABLY It's not only skips rows -  PROBABLY it's ocassionally scans same row twice (as I can see from scan process)

Looks like there is some problems with pagination

Otherwise it works very good! Thanks for a great product!

**Comment by Cupcak3** [comment]
Does lowering the resolution let the rows scan more predictably?

**Comment by Kalaborative** [comment]
Changing the resolution didn't work for me :( For me, it scans everything but the first row.

**Comment by Cupcak3** [comment]
I am closing this issue as it is a bit old. Please reopen the issue if this still happens on recent versions
