### ISSUE TITLE
Scanner stuck in character card and exiting after without action when scanning only characters

### ISSUE THREAD

**Issue by ecpgieicg** [Andrewthe13th/Inventory_Kamera#445]
### Current Behavior

When selected to scan characters only, the scanner went to open character card (Esc -> Avatar) and got stuck there for a few minutes and then exiting without performing any further visible actions. 

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Unsure. For me, selecting to scan all and selecting to scan only weapons worked for me. Select to scan characters only led to the failure. But the exact parameters for prompting the behavior is uncertain.

### Device OS

Windows 10

### Genshin Impact Version

3.5

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

2560x1440

### Additional notes and remarks

Error log below. But might be from a few different attempts in aggregate.

-----------

Could not determine character's name

Could not determine character's element

Could not determine character's name

Could not determine character's element

Could not determine character's name

Could not determine character's element

Could not determine character's name

Could not determine character's element

### Evidence

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11184572/InventoryKamera.log)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11184573/InventoryKamera.debug.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Your resolution says you have a widescreen monitor. Please see one of the pinned issue regarding this. Please reopen this issue if it does not fix your problem
