### ISSUE TITLE
artifacts scan issue

### ISSUE THREAD

**Issue by taveller** [Andrewthe13th/Inventory_Kamera#448]
### Current Behavior

it can't scan

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

![image](https://user-images.githubusercontent.com/132076588/235170251-f56a15a1-4208-4084-ae0e-7e16141814de.png)

### Device OS

Windows 11

### Genshin Impact Version

3.6

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

1280x720

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
It appears the inventory did not open. This might be due to your keybinds. 

However, not enough information has been provided to debug this issue more. If you have additional information, feel free to reopen this issue.
