### ISSUE TITLE
Error when scanning artifacts : Unable to validate information for artifact ID#336, Invalid artifact gear slot, Invalid artifact set name

### ISSUE THREAD

**Issue by Roxokam** [Andrewthe13th/Inventory_Kamera#451]
### Current Behavior

Hello,

When I scan my artifacts with Inventory Kamera, I am getting those errors: Unable to validate information for artifact ID#336, Invalid artifact gear slot, Invalid artifact set name.

And I get a 1ko JSON file in the export folder.

Thank you for your help  

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

I opened Genshin Impact menu (Esc) after putting the game in 1600 900 resolution.
Then press on Scan Genshin 
The image below represents the result that I got when I waited for the app to finish scanning 
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/23038200/802fecb8-4fa2-4be1-8f32-b620fff83f4f)

### Device OS

Windows 10

### Genshin Impact Version

3.7

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

1600x900, window, I did not modified the UI scale (I do not know how to do it) 

### Evidence

This is a part of the logs

Unable to validate information for artifact ID#333

Invalid artifact gear slot

Invalid artifact set name

Artifact ID: 333

Slot: fleurdelavie

Set: 

Rarity: 5

Level: 12

Main Stat: hp_

Substat 1: hp_ + 5,3%

Substat 2: def + 19

Locked: True

Unable to validate information for artifact ID#334

Invalid artifact gear slot

Invalid artifact set name

Artifact ID: 334

Slot: fleurdelavie

Set: 

Rarity: 5

Level: 12

Main Stat: hp_

Substat 1: atk + 16

Substat 2: atk_ + 15,2%

Locked: True

Unable to validate information for artifact ID#335

Invalid artifact set name

Artifact ID: 335

Slot: plume

Set: 

Rarity: 5

Level: 12

Main Stat: atk

Substat 1: def_ + 10,9%

Locked: True

Unable to validate information for artifact ID#336

Invalid artifact gear slot

Invalid artifact set name

Artifact ID: 336

Slot: diadémedelogos

Set: 

Rarity: 5

Level: 12

Main Stat: 

Substat 2: def_ + 13,1%

Substat 3: atk_ + 8,7%

Substat 4: hp + 478

Locked: True

Unable to validate information for artifact ID#337

Invalid artifact gear slot

Invalid artifact set name

Artifact ID: 337

Slot: fleurdelavie

Set: 

Rarity: 5

Level: 12

Main Stat: hp_

Substat 1: atk + 14

Substat 2: atk_ + 12,8%

Locked: True

Unable to validate information for artifact ID#338

Invalid artifact gear slot

Invalid artifact set name

Artifact ID: 338

Slot: sablesdutemps

Set: 

Rarity: 5

Level: 12

Main Stat: 

Substat 2: atk_ + 4,7%

Substat 4: hp + 717

Locked: True

Unable to validate information for artifact ID#339

Invalid artifact gear slot

Invalid artifact set name

Artifact ID: 339

Slot: diadémedelogos

Set: 

Rarity: 5

Level: 12

Main Stat: 

Substat 2: atk + 29

Substat 3: def + 37

Substat 4: def_ + 7,3%

Locked: True

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
The game must be in English
