### ISSUE TITLE
Unable to update game data

### ISSUE THREAD

**Issue by Daniil-pizza** [Andrewthe13th/Inventory_Kamera#454]
### Current Behavior

On open scan asks to update lookup tables, after trying to update gives error massage. Trying to update lookup tables through options menu result the same

### Expected Behavior

The scanner to supports game new or edited content

### Reproducing a Behavior

Just try to update lookup tables in any way
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/122693904/c955935f-090b-4a9f-b901-6e91814a5413)

### Device OS

Windows 11

### Genshin Impact Version

3.7

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

full screen

### Additional notes and remarks

tried use scanner 1.3.7, makes same error

### Evidence

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11688799/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11688800/InventoryKamera.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by e5pe** [comment]
It's happenning the same for me but I think you are looking at the wrong log file, it's in /logging/archives. The las lines in my log are these:
```
2023-06-09 17:10:37.228|INFO|InventoryKamera|Kamera initialized
2023-06-09 17:10:37.228|INFO|MainForm|Resolution: 1920x1080
2023-06-09 17:10:37.396|INFO|InventoryKamera|Logging directory reset
2023-06-09 17:10:38.183|ERROR|UserInterface|System.FormatException: Data file for Characters is invalid. Please try running the auto updater and try again.
   en InventoryKamera.DatabaseManager.GetList(ListType list)
   en InventoryKamera.Scraper.ReloadData()
   en InventoryKamera.Scraper..cctor()
2023-06-09 17:10:38.183|INFO|MainForm|Hotkey removed
````

Using:
Genshin Impact Version
3.7

Inventory Kamera Version
1.3.8

**Comment by Daniil-pizza** [comment]
[InventoryKamera.20230608162433.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11709536/InventoryKamera.20230608162433.debug.log)
[InventoryKamera.20230608162433.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11709537/InventoryKamera.20230608162433.log)
Well logs from there

**Comment by Riskinz** [comment]
Having the same issues myself, tried to change the location files where it was looking but something isnt right.
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11711435/InventoryKamera.log)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11711436/InventoryKamera.debug.log)

**Comment by Barikly** [comment]
Same issue happened to me. 
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11711539/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11711540/InventoryKamera.log)

**Comment by diggtrap** [comment]
Getting the same error
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11711552/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11711553/InventoryKamera.log)

**Comment by rafsawicki** [comment]
This is likely the same issue that I was having, so it should be fixed in a new version [since a fix was merged](https://github.com/Andrewthe13th/Inventory_Kamera/pull/453)

**Comment by Daniil-pizza** [comment]
So now I just need to wait for fix in 1.3.9?

**Comment by juandvasquezp** [comment]
> 

Program has been using the fandom wiki for a while instead of that repository, what happened is that someone made a change in the characters wiki.

**Comment by huang-jy** [comment]
As a minor workaround if you want the app to work, is to re-extract the zip from the releases (Which will overwrite the messed up data files) and start the app, but then choose NOT to update. The app will run and work (albeit with older database)

**Comment by Daniil-pizza** [comment]
Yup update to 1.3.9 works just fine (option to not update lookup tables on 1.3.8 made and error on ry to scan)
