### ISSUE TITLE
|ERROR|UserInterface|Unable to validate information for artifact ID#518

### ISSUE THREAD

**Issue by Xayayia** [Andrewthe13th/Inventory_Kamera#455]
### Current Behavior

Scanner says the substats are invalid yet they're in game so they are 100% valid

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

run the scanner, either scan only artifacts or artifacts and characters and weapons, result is the same, equip artifacts checked, minimum rarity 5*, minimum level 0, scanner delay fast/slower/slow

### Device OS

Windows 10

### Genshin Impact Version

3.7

### Inventory Kamera Version

1.3.9

### Screen resolution, screen mode, and UI scale

1280x720 windowed

### Evidence

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11753703/InventoryKamera.log)
![Screenshot_2](https://github.com/Andrewthe13th/Inventory_Kamera/assets/130109314/c033e139-8176-4147-99c7-ccebeb7c3a0c)
log and screenshot of one of the errored artifacts

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
An issue already exists for this issue so I am closing it as a duplicate
