### ISSUE TITLE
Error Artifact ID#2 on Scanning

### ISSUE THREAD

**Issue by HabKaPlaan** [Andrewthe13th/Inventory_Kamera#457]
### Current Behavior

I get an error on scanning genshin impact with Inventory Kamera.

![grafik](https://github.com/Andrewthe13th/Inventory_Kamera/assets/137694843/37a3f0ac-513b-4cf2-a956-257c048040f1)

Another bug is there too, Nahida is tagged as Geo.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

![grafik](https://github.com/Andrewthe13th/Inventory_Kamera/assets/137694843/807606bb-f4ea-4568-b0e2-0a4586c2a553)

This Item causes the Problem

### Device OS

Windows 10

### Genshin Impact Version

3.6

### Inventory Kamera Version

1.3.9

### Screen resolution, screen mode, and UI scale

1600*900

### Evidence

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11859578/InventoryKamera.debug.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
See #40
