### ISSUE TITLE
Scanning artifacts causes bug like behaviour + stops half way

### ISSUE THREAD

**Issue by sensnowy** [Andrewthe13th/Inventory_Kamera#458]
### Current Behavior

Scanning stops half way through artifacts. 
Skips afterwards to characters. 
End up without characters having 95% of their equipped artifacts

### Expected Behavior

The scanner to not skip rows or items

### Reproducing a Behavior

https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/d2551579-5026-48b5-9b70-9002682500f0

[InventoryKamera.20230627133037.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882350/InventoryKamera.20230627133037.debug.log)
[InventoryKamera.20230627133037.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882352/InventoryKamera.20230627133037.log)
[InventoryKamera.20230627143940.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882354/InventoryKamera.20230627143940.debug.log)
[InventoryKamera.20230627143940.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882357/InventoryKamera.20230627143940.log)

### Device OS

Windows 10

### Genshin Impact Version

3.7

### Inventory Kamera Version

1.3.9

### Screen resolution, screen mode, and UI scale

1920*1080/720p resolution advised in bug fixes

### Evidence

[InventoryKamera.20230627133037.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882427/InventoryKamera.20230627133037.debug.log)
[InventoryKamera.20230627133037.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882428/InventoryKamera.20230627133037.log)
[InventoryKamera.20230627143940.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882429/InventoryKamera.20230627143940.debug.log)
[InventoryKamera.20230627143940.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882430/InventoryKamera.20230627143940.log)
![ArtifactInventory](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/53c64e43-2496-4e58-aeb9-3e0ee6746868)
![ArtifactInventory4_7x4 - weight 0,5](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/c9898e1a-ea7a-4ab1-89a8-c4d65238051a)
![ArtifactInventory4_8x4 - weight 0,1](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/29e3c7cb-ef79-437d-afac-11d8af94c368)
![ArtifactInventory4_8x4 - weight 0,2](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/44b90530-7e99-4c9e-a412-33cc019266b8)
![ArtifactInventory4_8x4 - weight 0,3](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/6dc79fb2-7d5e-4ffc-a074-5f36677f50a9)
![ArtifactInventory4_8x4 - weight 0,4](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/96b7f005-8f65-4275-ba52-6c02cfb4cd1d)
![ArtifactInventory4_8x4 - weight 0,05](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/6f058f85-2414-4651-8b1b-2e090fc4f08a)
![ArtifactInventory4_8x4 - weight 0,15](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/1d1e26db-b6f1-429d-ae8d-05ddcfb8b71f)
![ArtifactInventory4_8x4 - weight 0,25](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/f1e913d8-55ad-43ff-91ad-d6cf0ea43358)
![ArtifactInventory4_8x4 - weight 0,35](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/e388d4f5-f434-4835-b435-55f060f18328)
![ArtifactInventory4_8x4 - weight 0,45](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/e805c617-ca06-4c14-8981-d372da11c297)
![ArtifactInventory4_8x4 - weight 0](https://github.com/Andrewthe13th/Inventory_Kamera/assets/42115708/cf3bfd4d-76be-40cc-bb86-227dfec96ee2)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882436/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/11882437/InventoryKamera.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
I suspect this is due to the filter label at the bottom of the page. Since Genshin's artifact UI has changed in a recent updated (and Kamera has updated for this) I am closing this issue.
