### ISSUE TITLE
Scanning artifacts function alternate between missing rows and repeating rows for certain resolutions

### ISSUE THREAD

**Issue by ecpgieicg** [Andrewthe13th/Inventory_Kamera#460]
### Current Behavior

In resolution 2560x1440 (full screen on my PC) and 1920x1440, I find the tool frequently misses rows and repeat rows when scanning artifacts. This happens when the artifact UI scrolls with the 1st row of the artifact grid being imperfectly aligned with the box that displays artifacts. When the misalignment is big enough, Inventory Kamera appears to select which row to continue based on how much the 1st row is cut off.

This method is however unreliable and result in the scan alternating between missing a row, being correct on a row, and repeating a row. (Never strictly alternative between these 3. Only loosely alternating.) 

I think the tool needs to be able to identify the highlighted artifact as that labels the previously selected and scanned artifact. Since the scrolling UI does not change the previous highlight, that will always identify the correct row to scan next.

### Expected Behavior

The scanner to not miss row or items

### Reproducing a Behavior

Use 2560x1440 and 1920x1440 in Genshin graphics setting.

Start scanning artifacts.

Pay particular attention to the alignment of artifact grid with the display box.

For any resolution where misalignment occurs, there should be missing rows and repeated rows.

### Device OS

Windows 10

### Genshin Impact Version

3.7

### Inventory Kamera Version

1.3.8

### Screen resolution, screen mode, and UI scale

2560x1440, 1920x1440

### Evidence

[Here is the result](https://pastebin.com/WaBWKa6v) from one of the scans I visually noticed missing/repeated rows.

I don't have a tool myself to parse the json file and don't really have an easy way to detect duplicates. 

It is easy to verify missing artifacts, however. 

This is [part of my current inventory](https://i.imgur.com/cG6UjtI.png) in the same state. Note the number of level 1 head pieces from the Emblem set is 11.  Meanwhile, in the scanned result, there are only 3 level 1 head pieces from Emblem set.

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
An issue already exists describing this issue. I am closing this as a duplicate.
