### ISSUE TITLE
Scanner thinks unequipped artifacts are equipped

### ISSUE THREAD

**Issue by kree-nickm** [Andrewthe13th/Inventory_Kamera#463]
### Current Behavior

Scanner thinks the "Source" label of an artifact is an "Equipped By" label and tries to set the "location" property of the artifact to whatever character it misreads the "Source" label to be.

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Scan any 5-star artifact that has the "Source" label visible near the bottom of the artifact info box. When using 1680x1050 Windowed display mode, the problem consistently occurs with the following artifacts (that I know of):

- Heart of Depth flower/plume/sands with 3 substats, or circlet with 3-4 substats.
- Emblem of Severed Fate plume/goblet with 3 substats, or circlet with 3-4 substats.
- Noblesse Oblige flower/plume/goblet/circlet with 3 substats.
- Maiden Beloved flower/plume/goblet.
- Bloodstained Chivalry flower/plume with 3 substats.

![artifact scan](https://github.com/Andrewthe13th/Inventory_Kamera/assets/38154033/d68b6317-1f23-4326-85a3-6d0be0ed9142)

In the above example, Inventory Kamera will think that the "Domain of Blessing: Stone Chamber" text is actually saying "Equipped By: Amber", and thus Amber will have multiple artifacts exported as being equipped to the same slot.

### Device OS

Windows 10

### Genshin Impact Version

3.8

### Inventory Kamera Version

1.3.9

### Screen resolution, screen mode, and UI scale

1680x1050 Windowed

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This should be fixed in a recent version
