### ISSUE TITLE
Scanner suddenly starts going backwards, then stops

### ISSUE THREAD

**Issue by s0ckies** [Andrewthe13th/Inventory_Kamera#465]
### Current Behavior

I am having an issue where, when scanning character development and material items, the scanner works fine for the first few pages then suddenly starts going backwards from the bottom and then stops when it reaches the top of the current page. I have used the scanner successfully many times before, and I even reinstalled and forced a 4.0 update to make sure everything was to be working as expected, with no luck. Not sure what I'm doing wrong, or if the scanner is just experiencing a bug.

https://github.com/Andrewthe13th/Inventory_Kamera/assets/142496346/8e3a45ab-8e39-4988-8604-9bec4801ffbe

### Expected Behavior

The scanner to not skip rows or items

### Reproducing a Behavior

I simply am using the scanner as intended.

### Device OS

Windows 10

### Genshin Impact Version

4.0

### Inventory Kamera Version

1.3.9

### Screen resolution, screen mode, and UI scale

Tried with both 1920 x 1080 Windowed and 1600 x 900 Windowed

### Evidence

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/12368241/InventoryKamera.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This issue should be fixed in the latest release. Please reopen the issue if you find the problem still exists.
