### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by Alb11747** [Andrewthe13th/Inventory_Kamera#47]
1. Pressing enter to stop doesn't work reliably
2. Click on 50ms for Scanner Delay doesn't work and can only be done by dragging. (Increasing size might fix)
3. Format selection should be a Radio Button

Feature Suggestions
Allow for importing character, weapon, and artifacts names and indexes from a JSON file so compatibility doesn't break for future versions without an update (Users can edit). A default list as a backup can still be kept and compiled into the program.

**Comment by Andrewthe13th** [comment]
Good ideas. 
1. Need to fix enter button still
2. I am using a preset slider widget. I'll try making it bigger but dont want to waste too much time on ui. 
3. Good Idea on format selection. 
4. I will try to explain more about where i publish my character,weapon and artifact names so some user can commit changes to it more easily. I dont want to put them on a JSON file as i don't expect user to edit or trust them to do it right. 
Thanks for your input.

**Comment by Alb11747** [comment]
Another idea I had for compatibility is a strict and conformance mode.
Setting can be stored in a window menu or checkbox.
Strict mode (default): Same as how it works now
Conformance mode: Don't check if the name matches in the list,
Transforms strings with spaces to pascal case
(Since in the GOOD format indexes aren't used anyway)
I'm not sure what problems this strategy may cause but this can be very useful for future-proofing and needing lower maintenance for new characters and weapons.

If you're having trouble getting the Traveler name to work you could add an input box where the user types in their name and the program checks against that instead of trying to figure out if it's the Traveler name or not.

**Comment by Alb11747** [comment]
I think the delay for clicking on a weapon should be longer after just scrolling. Sometimes the UI bounces down and up and I think that may cause issues. I haven't seen this issue with artifacts so I'm not sure what's different.
