### ISSUE TITLE
didn't move

### ISSUE THREAD

**Issue by Intereksternal** [Andrewthe13th/Inventory_Kamera#471]
### Current Behavior

he just opened his inventory without moving an inch

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

doesn't scan anything

### Device OS

Windows 11

### Genshin Impact Version

4.0

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1920x1080 window & 3440x1440 full

### Additional notes and remarks

nothing

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
I cannot help if you do not provide any evidence.
