### ISSUE TITLE
Artifact Scanner Won't Start

### ISSUE THREAD

**Issue by KiryuuGaKill** [Andrewthe13th/Inventory_Kamera#472]
### Current Behavior

Object reference not set to an instance of an object.

   at InventoryKamera.InventoryScraper.GetPageOfItems(Int32 pageNum, Boolean acceptLess) in C:\Users\veloz\Source\Repos\Inventory_Kamera_Main\InventoryKamera\scraping\InventoryScraper.cs:line 467

   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count) in C:\Users\veloz\Source\Repos\Inventory_Kamera_Main\InventoryKamera\scraping\ArtifactScraper.cs:line 28

   at InventoryKamera.InventoryKamera.GatherData() in C:\Users\veloz\Source\Repos\Inventory_Kamera_Main\InventoryKamera\data\InventoryKamera.cs:line 148

------

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/12655606/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/12655607/InventoryKamera.log)

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Start scan again, unable to start a scan without The First Days of the City of Kings to figure out if it's causing it, or something with Wanderer.

### Device OS

Windows 11

### Genshin Impact Version

4.0

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1920x1080

### Additional notes and remarks

Sorry if this is a dupe, I couldn't find anything but I am blind sometimes. Video is available upon request since it's apparently too big

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Did you extract the release? I don't you should not be getting those paths in your error report.

**Comment by Cupcak3** [comment]
I am closing this in favor of #487
