### ISSUE TITLE
[BUG] Issue parsing numbers with repeat back-to-back digits

### ISSUE THREAD

**Issue by domysticnom** [Andrewthe13th/Inventory_Kamera#48]
I currently have 811 artifacts and the system only picks up 81 or 11

**Comment by ShadowScaleFTL** [comment]
same problem! I have 221 artifacts, but scan goes only for 22 without any error.

**Comment by ShadowScaleFTL** [comment]
upd. Change my artifacts to 219 and it works well. Seems bug appear only with two same digits near to each other.

**Comment by Cupcak3** [comment]
This issue seems solved with previous releases so I am closing this issue.
