### ISSUE TITLE
Cannot scan artifact locked status

### ISSUE THREAD

**Issue by jajiju** [Andrewthe13th/Inventory_Kamera#481]
### Current Behavior

When scanning artifacts, the scanner always returned "Locked: False", regardless of artifact's Locked status.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Start a scan of Artifacts only, with Minimum Artifact Rarity 5 & Minimum Artifact Level 0, and with Equip Artifacts checked.

### Device OS

Windows 10

### Genshin Impact Version

4.1

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1920x1080 & 1600x900, Fullscreen & Borderless, default UI scale.

### Evidence

Log & example artifact scan:
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/12927051/InventoryKamera.log)
[artifact0.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/12927056/artifact0.zip)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by kree-nickm** [comment]
I have the same issue. I first noticed the issue in version 1.3.10. Avoided it by continuing to use 1.3.9, but that is no longer an option.

**Comment by Cupcak3** [comment]
This is fixed in the latest release
