### ISSUE TITLE
artifact scanner is broken

### ISSUE THREAD

**Issue by Spongman** [Andrewthe13th/Inventory_Kamera#483]
### Current Behavior

1920x1200

it only finds one artifact
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/1088194/8f19cc1a-a7e4-4f2b-b567-f7860dde1f3a)

![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/1088194/e805f859-8e87-4eb4-9d1a-fc000f757935)

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

scan artifacts

### Device OS

Windows 10

### Genshin Impact Version

latest? instructions on how to find this would go a long way here ...

### Inventory Kamera Version

master

### Screen resolution, screen mode, and UI scale

1920x1200 

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Spongman** [comment]
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/1088194/23a8fe7b-efcb-4c29-9cc6-fe3822b5702c)

**Comment by Spongman** [comment]
switching the game to fullscreen 1920x1080 results in "Unable to locate Artifacts item count.".
switching the game to windowed 1920x1080 results in
```
Object reference not set to an instance of an object.
   at InventoryKamera.InventoryScraper.GetPageOfItems(Int32 pageNum, Boolean acceptLess) in C:\play\Inventory_Kamera\InventoryKamera\scraping\InventoryScraper.cs:line 467
   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count) in C:\play\Inventory_Kamera\InventoryKamera\scraping\ArtifactScraper.cs:line 28
   at InventoryKamera.InventoryKamera.GatherData() in C:\play\Inventory_Kamera\InventoryKamera\data\InventoryKamera.cs:line 148
```

**Comment by jofori89** [comment]
I also got this bug.
   at InventoryKamera.InventoryScraper.GetPageOfItems(Int32 pageNum, Boolean acceptLess) in C:\play\Inventory_Kamera\InventoryKamera\scraping\InventoryScraper.cs:line 467
 After debug the source code, i found out a condition, it is set  as **40 items per page**, (8 columns and 5 rows). But my invetory only have 35 per page (7 columns x 5 rows), that made the app could not process.

![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/29175749/2ee2c43b-5c56-49ab-9782-0ebc917d32dd)

**Comment by Cupcak3** [comment]
I am closing this issue in favor of #487
