### ISSUE TITLE
Cursor Scrolls on First Artifact

### ISSUE THREAD

**Issue by rcarlevale** [Andrewthe13th/Inventory_Kamera#486]
### Current Behavior

Starting Inventory Kamera it exits the paimon menu then goes to the artifact menu, and the cursor does nothing besides scroll down on the selected artifact description. This happens wherever genshin may be on my screen.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Have Genshin Impact in 1920x1080 windowed mode on an HDR display. All visual alteration settings are off (Radeon color change, HDR display, etc.)

### Device OS

Windows 10

### Genshin Impact Version

4.2

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1920x1080

### Additional notes and remarks

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/13491853/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/13491854/InventoryKamera.log)

### Evidence

[](https://youtu.be/RnmXoEuX1sE)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/13491937/InventoryKamera.debug.log)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/13491939/InventoryKamera.log)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by wairence** [comment]
set your resolution to 1800x1000

**Comment by Cupcak3** [comment]
I am marking this as duplicate in favor of #487
