### ISSUE TITLE
Game Data missing from Remote Repo

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [Andrewthe13th/Inventory_Kamera#488]
### Current Behavior

When launching Inventory Kamera I get an error stating:
```
Unable to update game data. Please check the log for more details.
```

Checking the log I see the follwing:
```
2023-12-19 14:38:50.756|WARN|MainForm|Could not check for list updates|Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Newtonsoft.Json.Linq.JObject]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
```

Checking the documentation, I see that it's supposed to scrape a remote repo, https://gitlab.com/Dimbreath/animegamedata.
However, the repo has a single, recent commit, with gitlab default `Readme.md` with no further files. Checking the repo again later shows an ever newer commit with the same data. It appears as if the empty repo is just continuously being force-pushed to main, as there's no commit history, or branches.

https://gitlab.com/Dimbreath/animegamedata/-/commits/main/?ref_type=HEADS
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/46251616/f7f636ea-a096-460e-ba0d-ee06bbc1a226)

### Expected Behavior

The scanner to supports game new or edited content

### Reproducing a Behavior

Open application
Options -> Update Lookup Tables

### Device OS

Windows 11

### Genshin Impact Version

4.2

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1920x1080 windowed

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by BlueSpaceCanary** [comment]
It 404s now, but I think it's a simple const change: it looks like that repo's now using `main` instead of `master` as the default branch, so the repoBaseURL const just needs to be updated to point to `https://gitlab.com/Dimbreath/AnimeGameData/-/raw/main/` instead. That base URL will still 404, but e.g. the TextMapEnURL with that base URL works: https://gitlab.com/Dimbreath/AnimeGameData/-/raw/main/TextMap/TextMapEN.json

**Comment by Cupcak3** [comment]
This is fixed in the latest version
