### ISSUE TITLE
HDR not supported

### ISSUE THREAD

**Issue by Sathans** [Andrewthe13th/Inventory_Kamera#498]
### Cause of the issue

Missing game information or instruction

### Describe your issue

The scanner does not work with HDR enabled, please put this in the configuration requirement for windows.

### How can we fix this?

I can help or fix the issue by myself

### Additional notes and remarks

Add another section to specify that hdr is not supported, and also put this in the bug report section.
Or use other scanning methods that works with hdr.

### Preflight Checklist

- [X] I understand that this is not a feature request or enhancement request. Such request is done in the Discussions tab.
- [X] I understand that this is not a question, a crash report, an error report, or a bug report. Such request is done using Bug Report in the Issue tab.
- [X] I am available for further questions.
- [X] I can help with documentation.
- [X] I understand the scanner's codebase.
- [X] I have checked the Issues tab and Discussions tab, and there are none similar to mine.

**Comment by Cupcak3** [comment]
I am closing this issue in favor of #164
