### ISSUE TITLE
Ingame resolution is changed to 1024×768 (or 640x480?) and breaks game settings (scan fails)

### ISSUE THREAD

**Issue by Foul-Tarnished** [Andrewthe13th/Inventory_Kamera#499]
### Current Behavior

When I press scan, the game res is set to 1024×768 (or 640x480??), and nothing happens, except black flash for the screenshots I guess

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Have DLDSR 1.78x and 2.25x enabled (nvidia 3xxx or 4xxx gpu) on a 1080p 16:9 monitor
Set Genshin Impact to 1920x1080 windowed (1620p for dldsr 2x25 is detected as native and is the only one available in fullscreen)

### Device OS

Windows 11

### Genshin Impact Version

4.3?

### Inventory Kamera Version

1.3.12

### Screen resolution, screen mode, and UI scale

1920x1080, windowed, 240Hz, G-sync, 100% scale in windows, one monitor enabled

### Additional notes and remarks

- I have another 1080p monitor, turned off
- I have 2 of these virtual device drivers (1x 2234p, 1x 2234p hdr), but the displays are "disconnected" in display settings
https://github.com/itsmikethetech/Virtual-Display-Driver

game launch parameters : "-screen-fullscreen 1 -window-mode exclusive"

### Evidence
**640x480 is an unsupported resolution.**
???

I log off of windows to stop it, and GenshinData folder is empty, even though it seemed to have (tried) to take screenshots

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Foul-Tarnished** [comment]
I can't change the resolution in-game, it doesn't apply

I disabled dldsr, sign off of windows, relogin, and now genshin looks like this...
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/107711110/2d57441b-6c64-4f77-a8bc-1d101dbbcebb)
And it crash during loading

**Comment by Foul-Tarnished** [comment]
Actually it happens in any case, even with dldsr off in nvcp...

**Comment by Cupcak3** [comment]
This does not seem related to Inventory Kamera so I am going to close this issue. Custom launch options are user-dependent and will not be built into Kamera as edge cases.

**Comment by KEKKO96** [comment]
I have the same problem, also DLDSR is disabled
