### ISSUE TITLE
Artifacts with +sub-stat <10 are not properly scanned

### ISSUE THREAD

**Issue by dudensen1** [Andrewthe13th/Inventory_Kamera#501]
EDIT: Not just ATK, +DEF<10 also won't log, maybe Elemental Mastery as well, although I'd have to check 2star artifacts for that one.

### Current Behavior

Artifacts with sub-stat ATK+ <10 are not properly scanned. Specifically the artifacts seem to be scanned but the sub-stat does not log. I have no idea if it's just this sub-stat or the 3star artifacts or anything of that sort. I can't pin it down, especially since I'm quite new to the game. The reason I'm saying <10 is because I found a similar (closed) issue that was reported about a year ago.

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

I'm pretty sure it's the <10 ATK thing, which is also what the other person found in the past.

### Device OS

Windows 10

### Genshin Impact Version

4.3, 4.4

### Inventory Kamera Version

1.3.12

### Screen resolution, screen mode, and UI scale

1920x1080 fullscreen, 1600x900 windowed

### Evidence

![Untitled](https://github.com/Andrewthe13th/Inventory_Kamera/assets/119273967/4a234baa-c522-4927-9660-0e5ba6d9aaa2)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by dudensen1** [comment]
Just downloaded the version 13.3.3 on Genshin Impact 4.4 and the problem seems to have been fixed. However, I'm now also having the issue with the rounded decimals (there is already an open issue about this).

**Comment by Cupcak3** [comment]
This is fixed in the latest release
