### ISSUE TITLE
[bug] v.1.3.2 can't update lookup tables in GI v4.4

### ISSUE THREAD

**Issue by supernova-ws** [Andrewthe13th/Inventory_Kamera#502]
### Current Behavior

When trying to update lookup table error popup appears

![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/412702/78caeb8b-f26f-4b3a-8ad5-4bf6a021f809)

But no error records logged nor into log window, nor into any of log files in IK `logging` folder

![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/412702/8bf35da6-a88e-463c-88db-8202917ed5b9)

### Expected Behavior

The scanner to supports game new or edited content

### Reproducing a Behavior

1. Upgrade GI to most recent version 4.4
2. Open IK
3. Select `Options`->`Update lookup tables`

### Device OS

Windows 11

### Genshin Impact Version

4.4 OSRELWin4.4.0_R20789045_S20838934_D20758469

### Inventory Kamera Version

1.3.12

### Screen resolution, screen mode, and UI scale

1920x1080p SDR x1.0

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
This is fixed in the latest version
