### ISSUE TITLE
Decimal values are rounded during the scan

### ISSUE THREAD

**Issue by dymm2000** [Andrewthe13th/Inventory_Kamera#503]
### Current Behavior

As described in title. Previous version worked well.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Scan

### Device OS

Windows 10

### Genshin Impact Version

4.4

### Inventory Kamera Version

1.3.13

### Screen resolution, screen mode, and UI scale

1280x720

### Evidence

![1](https://github.com/Andrewthe13th/Inventory_Kamera/assets/12236360/5a6e7dab-fea2-4019-af91-5b0ddd25e416)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by kylelamse** [comment]
Same problem here.  I was going crazy wondering why each decimal point was cut off.

**Comment by pv42** [comment]
Might be related to the regular expression change in  5ba2fcedcc62c298ba416af047b8e63fc4e4b752 :
InventoryKamera/scraping/ArtifactScraper.cs:451
```diff
-    Regex re = new Regex(@"([\w]+\W*)(\d+.*\d+)");
+    Regex re = new Regex(@"^(.*?)(\d+)");
```

**Comment by BlueSpaceCanary** [comment]
> Might be related to the regular expression change in [5ba2fce](https://github.com/Andrewthe13th/Inventory_Kamera/commit/5ba2fcedcc62c298ba416af047b8e63fc4e4b752) : InventoryKamera/scraping/ArtifactScraper.cs:451
> 
> ```diff
> -    Regex re = new Regex(@"([\w]+\W*)(\d+.*\d+)");
> +    Regex re = new Regex(@"^(.*?)(\d+)");
> ```

Yeah, comparing the two matching against the string `15.7`, the old regex [matches the whole string](https://regexr.com/7reag) but the new regex [only matches the characters before the decimal place.](https://regexr.com/7reaj)

**Comment by kylelamse** [comment]
Reverting that line doesn't seem to fix the problem

**Comment by Rettilaa** [comment]
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/39605290/e488da43-ef01-4aea-ad09-a16ebfda9aaf)
Same Issue, numbers after decimal are ignored

**Comment by exliko** [comment]
up, I have the same problem

**Comment by BlueSpaceCanary** [comment]
> Reverting that line doesn't seem to fix the problem when testing it locally

Reverting both that and [the deletion a little further down](https://github.com/Andrewthe13th/Inventory_Kamera/commit/5ba2fcedcc62c298ba416af047b8e63fc4e4b752#diff-d6b09efbf6bb936b461649b3195d151b985b9d7025dc2a960ca85d0abe77b6efL451) fixed it for me in a local build

**Comment by Cupcak3** [comment]
This is fixed in the latest release
