### ISSUE TITLE
Issue to counting

### ISSUE THREAD

**Issue by LuxYiios** [Andrewthe13th/Inventory_Kamera#514]
### Current Behavior

Don't have the right amount on scan

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

Just Use normaly

### Device OS

Windows 10

### Genshin Impact Version

4.5

### Inventory Kamera Version

3.15

### Screen resolution, screen mode, and UI scale

1600x900 / 1920x1080 / 2560x1440

### Evidence

![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/164045331/a4d7b13d-f689-4ce8-9125-41a740623652)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled (or documented) all screen filtering software, plugins, and enhancements while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
Material quantity scanning is known to be a bit shoddy and is a tracked issue already
