### ISSUE TITLE
Scanner crashed immediately after start scanning

### ISSUE THREAD

**Issue by sagelga** [Andrewthe13th/Inventory_Kamera#53]
I currently unable to scan with the 0.9 version of the game. No clue on how.

How to reproduce
- Download a zip file from release
- Unzip a file
- Click "Run" when Windows Defender told me not to
- Click "allow" in user access control
- Go to the Genshin windows
- Setup the screen resolution
- Leave the Genshin windows using Paimon Menu opened
- Click "Scan Genshin" from the scanner

Information about the PC
- OS : Windows 10
- Resolution : 1280 x 720
- Graphics quality : Low (Default)
- Native screen resolution : 2K

**Comment by ShadowScaleFTL** [comment]
try https://github.com/Andrewthe13th/Genshin_Scanner/issues/40

**Comment by sagelga** [comment]
Restart the game? Still failed.

**Comment by Hypn0tyk** [comment]
Have the same issue.  Scanner closes the paimon menu, attacks once, then opens it again, then crashes.

**Comment by mai-pai** [comment]
The application was crashing for me as well on Windows 10.  I found that the OCR engine (Tesseract) requires that the Microsoft Visual C++ redistributable be installed on the system.  I installed the x86 redistributable and it stopped crashing.  The redistributable can be downloaded from Microsoft at the following location: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Andrewthe13th** [comment]
Thanks for the info. I will include that into my readme and maybe project

**Comment by sagelga** [comment]
@mai-pai Thanks for the reply! Unfortuntately, it still failed.
I have installed Visual Studio 2015, 2017, 2019, and 2022 C++ Redistributable packages and it still crash.
is there's anything that I can help? @Andrewthe13th  Maybe some crash log or something like that?

**Comment by mai-pai** [comment]
@sagelga What you can try since the application doesn't have any logging, is to run the application using dnSpy to capture the error to help determine why it's crashing.  That's what I used to determine I was missing the redistributable on my machine.

**Comment by mai-pai** [comment]
@sagelga What you can try since the application doesn't have any logging, is to run the application using dnSpy to capture the error to help determine why it's crashing. That's what I used to determine I was missing the redistributable on my machine.

**Comment by sagelga** [comment]
@mai-pai Interesting...
I compiled the code via VS in debugger mode and it throw me this.

`Failed to find library leptonica.dll`
![devenv_Q9DInMHbc2](https://user-images.githubusercontent.com/13056824/144945574-0567a8f9-9aa8-4b36-805a-91bb1760c28d.png)

Isn't these dependencies should be listed to be install before using?

**Comment by mai-pai** [comment]
@sagelga That's a false positive, I got the same error  when the microsoft redistributable wasn't installed.  When you said you installed the redistributable did you install the x64 version or the x86 version?  This application is 32bit so it needs the 32bit (x86) redistributable.  If you've already installed the redistributable then it's possible "leptonica-1.80.0.dll" is dependent on something else that may not be on your system.

**Comment by sagelga** [comment]
It worked! I only install x64 and got that error.
Since I have install x84 and redo everything, it worked perfectly! Every single thing!

Dear @Andrewthe13th this is quite crucial that you should tell other people to download the C++ redistributable!
Genshin Impact nor other game all requires this, so you have to manually download it in order for it to work,

Since this issue has been resolved, I will close this issue and might send you a PR for the instruction update.
