### ISSUE TITLE
Artifacts not being scanned 9/305

### ISSUE THREAD

**Issue by pogusername** [Andrewthe13th/Inventory_Kamera#54]
![Screenshot 2021-11-11 204558](https://user-images.githubusercontent.com/86986522/141366553-2c3345da-dc30-4d77-9b3b-78c344f34032.png)
Barely able to create builds with it not scanning any besides a few of the purple ones. Willing to test more and send more screenshots if needed.

**Comment by Andrewthe13th** [comment]
Ok

**Comment by MillingtonAllen** [comment]
@pogusername Have you tried setting the delay to the 100ms?  Did it make a difference?  

I'm sure it doesn't help to just say "me too", but I'm missing some some 30 / 1040 artifacts (excluding the two newest sets).  I suspect that the delay needs to be set even higher than the 100ms, but I'm not sure.  I was getting some of the t is not a valid Character Name, but not sure if that's related to artifacts.

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease. Please let us know if these problems have gone away so that we may close this issue.
