### ISSUE TITLE
mouunsmoon and wavebreakersfin is not a valid weapon name

### ISSUE THREAD

**Issue by GenericApe** [Andrewthe13th/Inventory_Kamera#60]
Error: mouunsmoon is not a valid Weapon Name
Error: mouunsmoon is not a valid Weapon Name
Error: mouunsmoon is not a valid Weapon Name
Error: wavebreakersfin is not a valid Weapon Name

New weapons need to be added.

**Comment by Andrewthe13th** [comment]
oh forgot about these weapons. Will implement. Will also try to allow user to update this list by the use of a text file.
