### ISSUE TITLE
Missing weapons, artifacts and characters

### ISSUE THREAD

**Issue by IAlVeiga** [Andrewthe13th/Inventory_Kamera#61]
![imaxe](https://user-images.githubusercontent.com/31918219/142274365-6fa374be-5a2b-4894-89b6-09117c641982.png)
Thoma is not detected correctly. There are missing weapons and artifacts. Also, it seems to have some kind of issue with my username.

**Comment by lxhwes** [comment]
Can confirm similar issues on my end (latest build)

**Comment by Cupcak3** [comment]
This is a very old issue and has been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
