### ISSUE TITLE
1280x720 after ultrawide resolution

### ISSUE THREAD

**Issue by call-me-void** [Andrewthe13th/Inventory_Kamera#62]
Just wanted to notify you, that when genshin resolution is switched from ultrawide (3440x1440 in my case) to 1280x720 the game looks slightly different. The most striking difference is the number of artifact collumns, it equals 6 instead of 7. Also, navigation and pretty much all offsets are off.
I ended up forking and fixing offsets, thinking the devs have updated UI. But it's just a bug/feature of the game. In order for the game to show proper UI one should close it and restart with 1280x720 as the starting resolution (or any 16:9 for that matter).

Maybe it should be stated somewhere in help/wiki. Or even better you can check for this type of misalignment in future versions.

**Comment by call-me-void** [comment]
Also in this type of situation programm just crashes. It think we should process exceptions generated by Convert.ToDecimal. Or maybe use Decimal.TryParse?

**Comment by Andrewthe13th** [comment]
Yea some user recently have figure out this ui bug recently as well. I will need to put a faq or more instructions on how to deal with the issue. Yea i use decimal try parse, I just got to keep looking for more breaking points. I should have designed my program to fail from the beginning instead of realizing how important it is to do so.

**Comment by mynameisdolor** [comment]
How did you fix this? I'm experiencing the same issue (also using widescreen). The artifacts column shows 7 columns, but the scanner is missing 1 column. Thanks in advance for your help.

**Comment by mynameisdolor** [comment]
@call-me-void mentioning.

**Comment by call-me-void** [comment]
@mynameisdolor just fully close the game while it is in1280x720 windowed node. Then open it again.
This should help.

**Comment by Cupcak3** [comment]
I am closing this issue in favor of issue #40's thread
