### ISSUE TITLE
Support for Chinese version

### ISSUE THREAD

**Issue by Yinr** [Andrewthe13th/Inventory_Kamera#63]
The application name of Chinese version client is called `YuanShen.exe`. Can Genshin Scanner also support it?

For example checking the two name below automatically then find the right one.

https://github.com/Andrewthe13th/Genshin_Scanner/blob/29a121bf01f70c9aa24b61ddedf9522ba7195f68/GenshinGuide/Form1.cs#L166

I‘ve just simply changed `GenshinImpact` to `YuanShen` and it works well!

**Comment by Andrewthe13th** [comment]
Thanks for the knowedge. yea i will support it

**Comment by Cupcak3** [comment]
Support has been added in the[ v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease)
