### ISSUE TITLE
Could not find Genshin Process

### ISSUE THREAD

**Issue by MasterEric** [Andrewthe13th/Inventory_Kamera#64]
I got an error if I closed the game before starting the program, stating Process not Found

If I instead leave the game open (in 1280x720) before starting the scanner it works as expected

**Comment by Cupcak3** [comment]
Hi there, I know this issue is old but can you see if this issue still persists in any of the newer releases or prereleases? If it does, can you find the name of the exe responsible for Genshin as it appears under `Details` in Task Manager?

**Comment by Cupcak3** [comment]
I am going to close this issue as no feedback has been given for over a month. Feel free to reopen this issue if you still experience this problem.
