### ISSUE TITLE
It's not really an issue idk

### ISSUE THREAD

**Issue by Mehlzol** [Andrewthe13th/Inventory_Kamera#65]
my screen is square and doesn't have game window setup as 1280x720 mine only has 1152x864, 1024x768 and lower. The other bots aren't english or is harder to understand... (this is really demanding tbh ;-; sorry)

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease. Newer versions have support for 16:9 and 16:10 aspect ratios. Please let us know if you're able to run Genshin in either of those aspect ratios so that we may close this issue.
