### ISSUE TITLE
Scan finished but the json file isnt created

### ISSUE THREAD

**Issue by hifilt** [Andrewthe13th/Inventory_Kamera#68]
Tried changing the folder it would save to, still doesn't appear, but from what I can tell, it finished scanning. It just closes itself afterwards, and I can't find the json file in the folder it's supposed to be in.

**Comment by Andrewthe13th** [comment]
I believe this happens when a character is not found. Please let me know if this still occurs in newer versions.

**Comment by tar1su** [comment]
Tried to Scan after Itto and Gorou's banner and it's happening the same to me. It runs until the end, but the json file isn't created.
