### ISSUE TITLE
[Minor] The tool is unable to work if primary mouse button is set to right in windows settings

### ISSUE THREAD

**Issue by oksoff** [Andrewthe13th/Inventory_Kamera#71]
If player has set right mouse button as primary in windows settings the tool is unable to click while scanning. Seems like it's pressing 'left' button and not 'primary' button.

It's not a problem to change the primary button just when you are running the scan. So this issue is purely informational

**Comment by Cupcak3** [comment]
The mouse simulator library does not check for a primary mouse button. Luckily windows has a way to easily check so a fix will be easy.

**Comment by Cupcak3** [comment]
This has been added in recent versions.
