### ISSUE TITLE
genshin_best_eng training data is missing from the repo

### ISSUE THREAD

**Issue by doxxx** [Andrewthe13th/Inventory_Kamera#74]
After I compiled the latest version, it crashes when I start the scan because `genshin_best_eng.traineddata` is missing from the repo and is not included in the build output dir like `genshin_fast_09_04_21.traineddata` is.

**Comment by Andrewthe13th** [comment]
I will include the file. Just need to publish new build.

**Comment by doxxx** [comment]
Thanks for adding the file!
