### ISSUE TITLE
Not in G.O.O.D format

### ISSUE THREAD

**Issue by Vasilic-Maxim** [Andrewthe13th/Inventory_Kamera#75]
[Seelie](seelie.me) no longer supports formats rather than GOOD. Workflow:
- open the Inventory_Kamera
- in the 'Format' section select 'Seelie'
- press 'Scan Genshin' button
- open [inventory](https://seelie.me/inventory)
- press 'Import' button
- choose file generated by scanner

![Image 036](https://user-images.githubusercontent.com/10743063/144551761-4042e165-951e-4e18-9e44-e61fff2b8c53.png)

**Comment by Andrewthe13th** [comment]
![image](https://user-images.githubusercontent.com/11446437/144553585-cecbb8ce-7bd3-4b40-b653-6cf23fa17070.png)
He still supports that format. You can enter the data in here. I still need to talk with the seelie dev about the GOOD format or support his format still.

**Comment by Vasilic-Maxim** [comment]
It works. Thanks.

**Comment by doxxx** [comment]
That replaces the entire Seelie database. Since the Seelie file exported by InventoryKamera does not include any character data, this erases all the characters in the Seelie database.

**Comment by Andrewthe13th** [comment]
Ok thanks for the report. I still need to talk to the dev of the site. He hasn't responded yet.

**Comment by gbdematos** [comment]
> Ok thanks for the report. I still need to talk to the dev of the site. He hasn't responded yet.

Hi, I just sent you an email. 😊
