### ISSUE TITLE
if you remap keys it doesnt work

### ISSUE THREAD

**Issue by HornetGG** [Andrewthe13th/Inventory_Kamera#76]
i woulld like to have the options to change b and c keys to wichever i like is a little bit tedious to remap keys everytime i use the scanner ty

**Comment by Andrewthe13th** [comment]
Ya thanks for the suggestion. A user has already provided a fix for this issue. We just need to integrate it to this project. While take some time but it is coming.

**Comment by Cupcak3** [comment]
This has been added to recent versions.
