### ISSUE TITLE
Error while scanner char development items

### ISSUE THREAD

**Issue by themen098s** [Andrewthe13th/Inventory_Kamera#77]
While scanning for character development items for seelie, it gives this error:![afbeelding](https://user-images.githubusercontent.com/41344606/144666694-4fc42b67-f6d1-4bc4-9635-177d0b8457c6.png)

**Comment by HornetGG** [comment]
i have it too, if you dont have your MC maxed it happends

**Comment by Andrewthe13th** [comment]
Ah I understand know thanks

**Comment by bagusnl** [comment]
yeah i got this too, quite annoying since it resulting in the program to skip ~2 item rows and missed some items

**Comment by Andrewthe13th** [comment]
I didnt think it would lead to issues. I will hotfix this issue then. Didnt think it was a big deal.

**Comment by Andrewthe13th** [comment]
I added the brillant diamond types for character development items
