### ISSUE TITLE
thoma is not a registered as a Character Name

### ISSUE THREAD

**Issue by raktim2801** [Andrewthe13th/Inventory_Kamera#79]
I am getting the following errors while scanning:

> Error: thoma is not a valid Character Name
> Error: t is not a valid Character Name

Also Details of Thoma is not in the json file.

**Comment by Andrewthe13th** [comment]
Yea forgot to add Thoma will hotfix this issue

**Comment by Andrewthe13th** [comment]
I have hotfixed this issue
