### ISSUE TITLE
Inventory Kamera will not work when Nvidia's Filter is on

### ISSUE THREAD

**Issue by Athenaxdd** [Andrewthe13th/Inventory_Kamera#80]
just as title said; for people when scanning with Nvidia's Filter it would result in artifacts / weapons not being scanned

**Comment by Andrewthe13th** [comment]
I will mention this on the instructions page. I can't make it work with nvadia filter due to using some color to determine value. Such as constellations and rarity of items. It also effects the readability of the scanner. So for future use please turn nvadia filter during scanning process.

**Comment by I3oro** [comment]
How can I turn off Nvidia's Filter? I can't find this option
