### ISSUE TITLE
Scan Speed (V1.0)

### ISSUE THREAD

**Issue by jalil49** [Andrewthe13th/Inventory_Kamera#81]
Ran both versions 0.9 and 1.0, The scanning speed was reduced at 0ms delay settings. I assume the 200ms note in the 1.0 release is related to the addition of a 200ms option to the slider and not something that was suppose to be added to the default delay.

**Comment by jalil49** [comment]
Looked into it myself, seems like there was a reason for the change as it was related to a timing bug according to the commit, increasing the delay from 64 ms to 100 ms.  94a60ff3d9680e70b61ddf46517909d8a4ebbb57
so probably not a bug as it was meant to address something.

**Comment by Andrewthe13th** [comment]
Unfortunately I had to reduce the speed as the locked status would not be picked up on artifacts. I really wanted the scanner to be as fast as possible but it seems like mihiyo gave the lock status an animation that takes time to occur.
