### ISSUE TITLE
Display Mode Incompatibility

### ISSUE THREAD

**Issue by JohnJillky** [Andrewthe13th/Inventory_Kamera#82]
Perhaps I'm just SOL on my device, but I seem to be unable to set my display mode to 1280 x 720. I'm locked at 768 height. I don't know if there's something I can do to adjust this or if there would just need to be added compatibility, which I could understand if that would be too much work.
![Screenshot 2021-12-04 030835](https://user-images.githubusercontent.com/37197441/144702558-21f70240-ecfc-47ae-a45c-9819ce22b905.png)

**Comment by Andrewthe13th** [comment]
Thanks for the screenshot. I heard comments about this but wasn't able to understand why they can't pick 720p. That's really strange. I see if there's a solution somewhere as unfortunately I won't be supporting that resolution as it's not a 16:9 resolution.

**Comment by JohnJillky** [comment]
Is the 1360x768 close enough to 16:9 to be ok?

**Comment by Andrewthe13th** [comment]
![image](https://user-images.githubusercontent.com/11446437/144721642-9151be3c-1093-475f-a0a5-09c5a52761d6.png)
I guess it is. Another user is implementation that fix into my scanner, so we need to wait on him until it done. It could take a while so hopefully you are patient.

**Comment by JohnJillky** [comment]
That's fine. I'm gonna see if I can't force genshin to do 1366 without fullscreen. Hope that ends up working lol
