### ISSUE TITLE
Materials in GOOD format for Seelie AND Genshin Center's Acension Planner

### ISSUE THREAD

**Issue by diogofreitascastro** [Andrewthe13th/Inventory_Kamera#85]
The dev for Genshin Center https://genshin-center.com/planner added a material import lats night but it also imports in GOOD only.
![image](https://user-images.githubusercontent.com/48927378/144719465-9d6185e3-4990-4a37-9d53-f4ea470ceee0.png)
![image](https://user-images.githubusercontent.com/48927378/144719475-fc1a4c7a-67ea-4890-bdf0-bb76204832b5.png)
Ngl I don't enjoy Amenoma's scanner as much so I was hoping you could have the GOOD format for materials too <3
Could the format be changed to GOOD instead of "Seelie" so it works on both sites?

**Comment by Andrewthe13th** [comment]
the issue is I dont know the format. I want to make it in GOOD. Ill need to ask the devs at seelie and genshin center.Thanks for your support.

**Comment by lokyst** [comment]
This file format from the Amenoma dev was imported by Seelie without any issues.

[materials.GOOD.json.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/7654784/materials.GOOD.json.zip)

**Comment by Andrewthe13th** [comment]
Ya I should have looked how he implemented it. I did talk with the dev behind genshin optimizer and he will define the official format of material Json in GOOD shortly. It might change from the way the amenoma dev.

**Comment by Andrewthe13th** [comment]
Thanks for sharing me the link

**Comment by MasterEric** [comment]
Can't wait for this, importing materials is a pain and is currently the most inconvenient thing I have to do when managing my account (artifact scanning used to be the most annoying but is easy now thanks to this app).

**Comment by Cupcak3** [comment]
Recent updates have included material and mora scanning apart from enhancement ores.
