### ISSUE TITLE
"Error: Game Window not set to 1280 x 720 Windowed" when it's set correctly

### ISSUE THREAD

**Issue by Noriiiiiii** [Andrewthe13th/Inventory_Kamera#86]
It may be related to my laptop being wack, its always been when it comes to dimensions. I dont know what its doing wrong.

For extra info my screen looks like this when on 1280 x 720 
![image](https://user-images.githubusercontent.com/95553820/144730231-b13575e9-cc58-47ac-abff-5a1d404098c7.png)
It's the smallest of the correct ratio i can use
![image](https://user-images.githubusercontent.com/95553820/144730266-72668fd6-6413-43f4-bca5-ea56f900cece.png)
My laptop is a hp zbook 14u g6

I just really hope someone knows what to do because the amount of times people who DID know about technology looked at my laptop and were left clueless are too many...

**Comment by Andrewthe13th** [comment]
Are u using a second monitor. I have heard issues due that. Or try rebooting genshin with it set to that resolution.

**Comment by Cupcak3** [comment]
What is the resolution of your monitor when you open Genshin in the 1280x720 windowed mode? Your first screenshot makes me think the 1280x720 game window is the full screen of your laptop, if not bigger. It fills the whole screen and is the same width as your task bar and the taskbar looks like it covers some of the game.

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
