### ISSUE TITLE
Weapon scanning

### ISSUE THREAD

**Issue by RSvlad** [Andrewthe13th/Inventory_Kamera#9]
There seems to be an issue with scanning the first row in the weapons category.

Here's a video of the issue: https://youtu.be/mueiaGYr6UA

Here is the console output:
Error: Found instead of Weapon Level.
Error: mysticenhancementore is not a valid Weapon Name

**Comment by Andrewthe13th** [comment]
Ok. I did not account for so few weapons. Thanks for reporting

**Comment by RSvlad** [comment]
Thank you for maintaining this amazing extractor 😁

**Comment by Cupcak3** [comment]
Andrew seems to have fixed this issue a while ago so I am closing this issue. Please reopen this issue if the problem persists.
