### ISSUE TITLE
Weapon Scanning does not scan the first row and it cannot be changed later in GO (they all get a dull sword)

### ISSUE THREAD

**Issue by Armada99** [Andrewthe13th/Inventory_Kamera#92]

**Comment by Cupcak3** [comment]
This is mostly on GO's end. If GO imports a character without an assigned weapon it defaults to Dull Blade regardless of character weapon type. A partial fix for this is coming soon to Kamera.

**Comment by Cupcak3** [comment]
This issue been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
