### ISSUE TITLE
Feature Suggestion: Filter Scanning by Quality (stars)

### ISSUE THREAD

**Issue by lxhwes** [Andrewthe13th/Inventory_Kamera#93]
A nice feature would be the option to configure the scanner to only scan weapons/artifacts by star rating (example, minimum 4 stars).

**Comment by Cupcak3** [comment]
This feature has been added in the [v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease).
