### ISSUE TITLE
Only Scans Characters

### ISSUE THREAD

**Issue by Fr3aKeD** [Andrewthe13th/Inventory_Kamera#95]
![Screenshot 2021-12-11 114912](https://user-images.githubusercontent.com/28943259/145689734-39ca0abb-8927-4298-b3e9-9f815b9c0a78.png)

It took, MANY, MANY, MANY attempts to even get the scanner to work. it would just go on, get out of escape menu, attack, then the scanner would just crash/exit. i had left it on menu, then i had even left it where it was. it probably took me about 5 to 10 times till it actually worked and when it finally did... It only did the characters.

**Comment by Andrewthe13th** [comment]
The reason why you are having issues. Is cause the scanner to moving too fast. Use the scanner delay slider to make the scanner move slower and in time with your program.

**Comment by Fr3aKeD** [comment]
i just put to 200ms, still did same thing. Just slower.

**Comment by Fr3aKeD** [comment]
i do have a good computer so it should keep up with 200ms for sure. Right when i see the mouse go to where my name is above (No signature), that's when the scanner stops.

**Comment by Cupcak3** [comment]
If your character just attacks I can only assume you have your inventory key rebound. I've pushed code that has an option to rebind your inventory and character screen keys but it doesn't look like that included in a release yet. In the meantime make sure your inventory key is bound to the default B and character screen bound to default C.

**Comment by Fr3aKeD** [comment]
That seemed to have worked. lol. i totally didn't think about that cause I've had that changed for SO darn long. Thank you very much!

I just went to the setting, keybinds and hit Default real quick to see.
