### ISSUE TITLE
[BUG] Materials Quantity parsed incomplete or incorrectly

### ISSUE THREAD

**Issue by Kaponyt** [Andrewthe13th/Inventory_Kamera#96]
Hi!
I thought your project was very good, congratulations!

I just had some OCR issues when scanning to my seelie.me account, I set it to 200ms speed.

At the top the inventory in the seelie, and at the bottom the game inventory:
![image](https://user-images.githubusercontent.com/55726043/145729021-865ef77b-5998-449f-bc54-4a7cb02dd647.png)

**Comment by Cupcak3** [comment]
Thanks for report. Unfortunately this is a known problem as the size of the numbers and the fonts on digits (especially 1's) can sometimes skew the results from the scanner. We are working on finding ways to improve this accuracy. 

In the meantime can you provide the images of some items with expected and actual values? 
Something like this:
 
(Without the red circle)
![image](https://user-images.githubusercontent.com/8845977/145730581-91a495af-a249-413c-bcdf-4d5b89ef7c95.png)
Expected: 7
Parsed: 2

**Comment by Cupcak3** [comment]
This will likely be an ongoing issue but the priority on refining this kind of scanning is low priority. Other duplicate issues will be redirected to this to continue future discussion.

**Comment by Nicolas-GE** [comment]
i'm having this issue on max settings 16:9 1440p

**Comment by Cupcak3** [comment]
[V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0) has improved material quantity scanning so I am closing this issue. It's still not going to be perfect but it's better.
