### ISSUE TITLE
Inventory not reading correctly

### ISSUE THREAD

**Issue by XYZayne** [Andrewthe13th/Inventory_Kamera#98]
Having trouble with the new updated version. The last version worked fine, but now when trying to read my materials / char development items, the scanner will scroll down randomly, scan three or four rows and declare it's done. Obviously this means almost all of my inventory isn't being scanned - any ideas? Everything's up to date and the last version worked perfectly, like I said.

**Comment by sirius16** [comment]
Chiming in to say that I'm also experiencing this issue. It will scan the first 3 character development items then just skip 3 rows. Very strange, it works just fine with the artifacts

**Comment by pixelswirl** [comment]
I was also having this problem, but saw in another thread that it's caused by having event materials (like the alkahest from the latest event) in your inventory.  once I used that, it scanned correctly!  (just posting this here for anyone that ends up in this thread first)

**Comment by sirius16** [comment]
But I've already used my alkahest (are alkahest even in the character
improvement inventory tab. I thought that was only for boss drops and items
that can be upgraded in sets of three

**Comment by Cupcak3** [comment]
This is a very old issue and has likely been fixed by the latest release or prerelease so I am going to close it. Please reopen this issue if the problem persists.
